### ISSUE TITLE
Grafana-Anbindung zum CCU-Historian auf RaspberryMatic nicht möglich

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-historian#107]
s.a. [Forum](https://homematic-forum.de/forum/viewtopic.php?f=38&t=43434&p=435104#p435104)

**Comment by mdzio** [comment]
Ein Test mit der aktuellen RaspberryMatic-Version 2.31.25.20180526 liefert ebenfalls diesen Fehler.

Eventuell sollte auch eine anderen Java-Version (z.B. von Oracle) getestet werden.

**Comment by MalteHillmann** [comment]
Moin!

Ich wollte auch Grafana an CCU-Historian anbinden und hab ein bisschen debugging betrieben.
Eigentlich ist es ganz simpel. Zumindest bei mir:
Statt `./data/history` muss als Datenbank-Pfad der USB-Stick angegeben werden, sofern vorhanden. 
In meinem Fall war dies `./media/usb0/ccu-historian/history`

![postgres-sql](https://user-images.githubusercontent.com/3406318/60145187-8e1b0e00-97c5-11e9-88b8-32d14a695c48.png)

**Comment by mdzio** [comment]
Vielen Dank für die Lösung!

**Comment by TBR-BRD** [comment]
Auf der CCU3 mit USB Stick sieht es so aus: jdbc:h2:./media/usb1/ccu-historian/history
mit login: sa/ccu-historian
