### ISSUE TITLE
Spezifizieren der Systemvoraussetzungen

### ISSUE THREAD

**Issue by IceBoosteR** [mdzio/ccu-historian#111]
Hallo,

für die Verwendung des CCU-Historians würde ich mir gerne weitere Details zu den Systemvoraussetzungen wünschen, damit sich eine adäquate Planung der Serverresourcen durchführen lässt.
So wäre wichtig zu wissen, mit wie viel Arbeitsspeicher oder Datenmenge gerechnet werden kann. Selbstverständlich variien diese Werte, je nachdem wie viele Geräte und Datenpunkte erfasst werden, aber eine grobe Schätzung kann hier ja nicht schaden.

Danke.

**Comment by mdzio** [comment]
Vorab einige Angaben:
* Festplatte: 1 GByte/Jahr
* CPU
  * Minimum: 1 GHz, 2 Kerne
  * Empfohlen: 2 GHz, 2 Kerne
* RAM
  * Minimum: 1 GByte
  * Empfohlen: 2 GByte
