### ISSUE TITLE
"Swinging Door" Algorithmus für die Datenkompression

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-historian#113]
Vorteile:
* Höhere Kompressionsrate für analoge Messungen als bei der Delta-Kompression bei gleicher Qualität.
* Die komprimierten Daten können linear interpoliert dargestellt werden, was bei der Delta-Kompression nicht möglich ist.

**Comment by mdzio** [comment]
Siehe auch Handbuch: [Vorverarbeitung aller Wertaktualisierungen](https://github.com/mdzio/ccu-historian/wiki#vorverarbeitung-aller-wertaktualisierungen) und [Swinging-Door Kompression](https://github.com/mdzio/ccu-historian/wiki#swinging-door-kompression)

**Comment by mdzio** [comment]
Der neue Typ lautet: `PreprocType.SWD_COMPR`

**Comment by tgw-de** [comment]
Kann man den Swinging-Door-Algorithmus nachträglich auf die DB anwenden? Meine DB ist derzeit 42GB groß über mehrere Jahre..

**Comment by mdzio** [comment]
Mit der Kommandozeilenaktion `-recalc` ([s.a. Handbuch](https://github.com/mdzio/ccu-historian/wiki#startparameter)) werden alle Datenpunkte mit den aktuell konfigurierten Vorverarbeitungen neu berechnet. Danach sollte eine Kompaktierung der Datenbank mit der Option `-compact`  durchgeführt werden, um Speicherplatz freizugeben. Der CCU-Historian muss für die Anwendung der Optionen gestoppt sein.

**Comment by tgw-de** [comment]
Hat super geklappt, ich bin jetzt mit meiner Testdatenbank von 32 auf 9GB runter! Danke!

Meine originale Datenbank hat derzeit dieses Problem und lässt mich kein -recalc durchführen:
2020-10-26 15:01:11|WARNING|Invalid content in table DATA_POINTS field CUSTOM (expected JSON object): [DP_ID:4083, T.........

Hab schon eine Anfrage im Forum dazu gestellt:
https://homematic-forum.de/forum/viewtopic.php?f=38&t=54229&p=613851#p613851

**Comment by Omega236** [comment]
Wie führe ich einen recalc bzw compact durch wenn CCU-historian im Docker (xjokay/ccu-historian
) läuft?

**Comment by mdzio** [comment]
Durch Setzen der Umgebungsvariable CONFIG_KEEP_MONTHS im Docker-Container wird vor dem eigentlichen Start des CCU-Historian eine Wartung durchgeführt. Nacheinander wird der CCU-Historian mit den Optionen `-clean`, `-recalc` und `-compact` aufgerufen.

Die Frage sollte aber besser im [docker-ccu-historian Projekt](https://github.com/x-jokay/docker-ccu-historian) gestellt werden.

Siehe auch [docker-entrypoint.sh](https://github.com/x-jokay/docker-ccu-historian/blob/main/docker-entrypoint.sh).
