### ISSUE TITLE
Import von CUxD DEVLOG-Dateien

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-historian#117]
Einigen Anwendern, die bisher mit CUxD Zeitreihen aufgezeichnet haben, würde es helfen, die bereits vorhandenen DEVLOG-Dateien in den CCU-Historian importieren zu können.

**Comment by tigeriltis** [comment]
Ich würde diese Funktion gerne verwenden.

**Comment by mdzio** [comment]
PeterAC aus dem Homematic-Forum hat das [CSV-Import-Skript für CUxD-Devlog-Dateien](https://homematic-forum.de/forum/viewtopic.php?p=575266#p575266) angepasst.
