### ISSUE TITLE
Synology-Paket: CCU-Historian wird nicht automatisch gestartet

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-historian#125]
Der CCU-Historian wird nicht automatisch gestartet, wenn die Synology startet.

**Comment by mdzio** [comment]
Anwender des Synology-Pakets sollen sich mal melden, ob der Fehler bei jedem auftritt.

**Comment by AndreasKlingbeil** [comment]
Der Fehler tritt bei mir auf

**Comment by mdzio** [comment]
Es ist noch zu klären, ob dies bei jedem Neustart so ist, oder ob es nur nach einer Aktualisierung der DSM-Software passiert.

**Comment by AndreasKlingbeil** [comment]
Offenbar tritt es nach Aktualisierung der DSM-Software auf. Danach lief CCU-Historian völlig instabil. Nach Deinstallation und erneuter Installation des CCU-Historian läuft dieses jetzt schon über einige Tage wieder stabil.

**Comment by mdzio** [comment]
Der Fehlereintrag ist bereits sehr alt. Er wird nun geschlossen. Bitte bei Bedarf einen neuen Eintrag erstellen.
