### ISSUE TITLE
Zweite Zeitachse für die gleichzeitige Darstellung eines zweiten Zeitbereichs.

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-historian#13]

**Comment by martinrieder** [comment]
Ich verstehe #260 so, dass es auch mit einer Zeitachse funktionieren sollte. Es ist quasi nur eine Modulo-Operation erforderlich. Kann man das mit der neuen Berechnungsfunktion realisieren?

**Comment by mdzio** [comment]
Das stimmt. Mit den Berechnungsfunktionen ist dies bereits möglich. Mir war das gar nicht bewusst. Danke für den Hinweis. Die entsprechende Funktion ist bereits vorhanden ist: **shift**

```groovy
// Die Zeitreihe wird zeitlich verschoben. Bei einer positiven Zeitdauer
// wird ein älterer Zeitbereich angefragt, und die Zeitstempel auf den
// aktuellen Zeitbereich verschoben. (Die Kurve wird beispielweise in einer
// Trend-Darstellung nach rechts verschoben). Die Zeitdauer wird in Stunden
// angegeben.
Expression shift(Number duration)
```

[Siehe auch Handbuch.](https://github.com/mdzio/ccu-historian/wiki/Skriptumgebung)

[Datumsarithmetik kann mit Hilfe der Date-Klasse erfolgen.](https://docs.groovy-lang.org/latest/html/groovy-jdk/java/util/Date.html)
