### ISSUE TITLE
Achsenbeschriftung für konstante Datenpunktwerte

### ISSUE THREAD

**Issue by Damian411** [mdzio/ccu-historian#130]
Im Diagramm für "SET_POINT_TEMPERATURE" werden die Werte falsch angezeigt (s. Screenshot) --> "1.2E1" statt "19"
Die Browser Firefox und Chrome zeigen das selbe Verhalten. 

![image](https://user-images.githubusercontent.com/32341615/45927781-ad37f700-bf38-11e8-9e21-5754ffdbbdad.png)

Dadurch lässt sich ein direkter Vergleich von Soll- und IST-Temperatur nicht generieren:
![image](https://user-images.githubusercontent.com/32341615/45927873-b5913180-bf3a-11e8-93a7-934f94ee869b.png)

**Comment by mdzio** [comment]
`1.2E1` ist die wissenschaftliche Darstellung für den Zahlenwert 12. Zurzeit wird insbesondere bei konstanten Werten automatisch die  wissenschaftliche Darstellung verwendet. Dies ist so in der verwendeten Bibliothek zur Generieren der Trend-Grafiken eingebaut. Es sollte aber behoben werden können.

Die zwei Temperaturen werden auf unterschiedlichen Achsen dargestellt, da sich entweder der Messbereichsanfang, das Messbereichsende oder die Einheit (das wird wohl hier der Fall sein) unterscheiden. Wenn die selbe Asche verwendet werden soll, so müssen diese Werte in der Datenbanktabelle DATA_POINTS manuell geändert werden.

**Comment by Damian411** [comment]
Beide Umsetzungen würden das Problem lösen und wären sehr hilfreich. Auch wenn im Falle der unterschiedlichen Einheiten die Ursache nach meinem Verständnis eher in einer inkonsequenten Deklarierung in der CCU zu finden ist. Ist sehen keinen Grund, warum ACTUAL_TEMPERATURE keine Einheit hat und SET_POINT_TEMPERATURE hingegen die Einheit "°C". Beide sollten gleich sein.

**Comment by mdzio** [comment]
Dieser Eintrag ist ein Duplikat von #12.
