### ISSUE TITLE
Datenbankgröße limitieren

### ISSUE THREAD

**Issue by iuliusmaximilian** [mdzio/ccu-historian#135]
Kann man die Datenbankgröße irgendwie limitieren dass alte Einträge automatisch gelöscht werden?

**Comment by mdzio** [comment]
Eine automatische Limitierung der Datenbankgröße gibt es noch nicht und ist auch erst einmal nicht geplant.

Es können aber über den speziellen Startparameter *-clean* bereits alte Zeitreihen-Einträge gelöscht werden (s.a. [Startparameter](https://github.com/mdzio/ccu-historian/wiki#startparameter)). Dieser Aufruf müsste dann z.B. einmal im Jahr manuell erfolgen.
