### ISSUE TITLE
Trend Designs in separate Datei(en) auslagern

### ISSUE THREAD

**Issue by cmoehler** [mdzio/ccu-historian#142]
Idealer Weise könnte man in der Config einen Pfad auf ein Verzeichnis mit Trend Design Dateien eintragen. Jede in diesem Verzeichnis vorhandene Datei (.txt oder was andere Endung) könnte eines oder mehrere Designs enthalten die von Historian eingebunden werden.  Dies würde die wartung der einzelnen Trend Designes erleichtern.

Ist das eventuell jetzt schon mittels #include in der configurationsdatei realisierbar?

Falls die Trend Designes ein separates Handling erhalten würden, müsste bei einer Änderungen an einem Design vieleicht die Datenbank nicht jedes mal getrennt und wieder verbunden werden. Das kostet doch einiges an Zeit und Nerven wenn man am erstellen eines neuen Designs ist und beim Trennen und neu Starten gehen auch immer Daten verloren die in dieser Zeit nicht aufgezeichnet werden :-)

**Comment by cmoehler** [comment]
Falls die Trend Designes ein separates Handling erhalten würden, müsste bei einer Änderungen an einem Design vieleicht die Datenbank nicht jedes mal getrennt und wieder verbunden werden. Das kostet doch einiges an Zeit und Nerven wenn man am erstellen eines neuen Designs ist und beim Trennen und neu Starten gehen auch immer Daten verloren die in dieser Zeit nicht aufgezeichnet werden :-)

**Comment by mdzio** [comment]
Das Inkludieren von anderen Dateien wird zurzeit nicht unterstützt. 

Generell soll der CCU-Historian aber um die Möglichkeit erweitert werden, ihn über benutzerdefinierte Skripts erweitern zu können (z.B. auch für die Anbindung von externen Datenbanken).

**Comment by cmoehler** [comment]
Dachte beim includieren an so etwas wie **#include <filename>** in der ccu-historian.config Datei. Also praktisch die Aufteilung der .config Datei in einzelne Dateien.

Würde die Verwaltung der Trend Designes übersichtlicher gestalten.

**Comment by cmoehler** [comment]
Da bei jeder Aenderung an der configuration die Datenbank getrennt und wieder verbunden wird, ist es praktisch nicht mehr sinnvoll möglich die einzelnen Trend-Designs anzupassen, da ich nach jeder Aenderung minutenlang warten muss bis die Datenbank wieder neu verbunden wurde.
Gibt es eine Chance auf eine Lösung bzw. habe ich eine solche eventuell übersehen?

**Comment by mdzio** [comment]
Im Installationsverzeichnis (bzw. das gewählte Verzeichnis mit der Konfigurationsoption base.scriptDir) kann eine Datei trenddesigns.groovy erstellt werden. Diese kann z.B. wie folgt gefüllt werden:
```
trendDesigns.default.renderers=[
  {
    stroke=new BasicStroke(10)
  }
]
```
Jede Änderung wird bei der nächsten Trendanzeige wirksam.

**Comment by bs0001** [comment]
Hallo,
irgendwie bekomme ich es nicht hin.
Gerne möchte ich eine dunkle Variante bei der Darstellung verwenden:
Handbuch, Teil: Beispiel 3: Hintergrund- und Skalenfarben, Skalenbeschriftungen ändern, Legende entfernen
Habe das Coding im Hauptverzeichnis des CCUH in der Datei trenddesigns.groovy abgelegt.
Was genau ist noch alles zu tun, damit das neue Design für die unterschiedlichen Diagramme gezogen wird?
Wie muss genau der Eintrag in der ccu-historian.config sein?

Sorry, irgendwie stehe ich leider im Wald.

**Comment by cmoehler** [comment]
Genial, vielen Dank für die Implementierung!!!

Ich habe, nach langer Zeit, die aktuelle Version installiert und dabei erfreut festgestellt, dass dieser Punkt schon länger implementiert wurde.
Allerdings musste ich erst alle TrendDesiggns in die trenddesigns.groovy auslagern bis es funktioniert hat. Könnte aber auch an falschen Bezeichnern meiner Definitionen gelegen haben.

Bei mir ist es im Moment leider so, dass beim Aufruf eines Charts mit BEZEICHNER, in welchem ich aber z.B. nur die Linienstärke definiert habe, diese korrekt dargestellt wird, jedoch die von mir ebenfalls in trendDesigns.default. festgelegten Definitionen wie z.B. Hintergrundfarbe etc. nicht verwendet werden. Für diese Teile des Charts werden dann vermutlich "ganz interne" Definitionen (weisser Hintergunde etc.) verwendet. Bedeutet das im Umkehrschluss, dass diese Definitionen dann für alle BEZEICHNER Charts nochmals definiert werden müssen? Also die in trendDesigns.default gemachten Angaben nicht als absolutes default Design behandelt werden?

**Comment by mdzio** [comment]
Alle Einstellungen müssen in allen Designs überschrieben werden. _default_ gibt für andere Designs keine Einstellungen vor. _default_ ist nur der BEZEICHNER, der verwendet wird, wenn in der URL kein Designs vorgegeben ist.

**Comment by cmoehler** [comment]
Ok, danke für die Erklärung.
Da bei den meisten Anwendern das "angepasste" Grunddesign (Hintergrund, Schriftfarben, Skalenfarben etc.) vermutlich für alle Charts verwendet wird, wäre es eine tolle Sache wenn bei benannten Designs, die selbst definierten"default" Einstellungen verwendet würden wenn die entsprechenden Definitionen beim bennanten Chart nicht vorhanden sind.
Das hätte, zum Einen den Vorteil, dass man nur die 'default' ändern muss wenn sich mal was am "Grunddesign" ändert und zum Zweiten, wären die einzelnen Trenddesigns viel kompakter und dadurch auch wesentlich übersichtlicher, wenn nur die "Chart relevanten" Anpassungen wie Skallierungen und Achsbeschriftungen etc. drinstehen müssten. Da ich viele Trenddesigns habe, ist das File voll von sich wiederholenden Standarddefinitionen und erschwehrt damit das auffinden der relevanten Zeilen leider sehr.
Also wenn sich das noch implementieren liesse, wäre das schön. 
Eventuell müsste ich mir mal für Notepad++ eine "Trenddesign" Sprache basteln um es farblich übersichtlicher zu gestalten und eventuell einzelne Designs wegklappen zu können.
Vielen Dank für deine tolle Arbeit.
