### ISSUE TITLE
Bezeichnungen für Datenpunkte

### ISSUE THREAD

**Issue by bs0001** [mdzio/ccu-historian#144]
Hallo,
es wäre prima, wenn man eine individuelle Bezeichnung für die Datenpunkte vornehmen könnte.
Ich habe bspw. mehrere Temperatursensoren und die Gerätenamen sind etwas schwierig umzusetzen, für welchen Raum dieser nun das Diagramm anzeigt.
Aus BidCos4711.Temperature wäre es daher schön, wenn man Garage-Temperatur machen könnte.
VG
Bernd

**Comment by RoMe0610** [comment]
Diesem Wunsch kann ich mich nur anschließen!
Ich nutze die Diagramme auch in einer Visualisierung und gerade hier werden Konstrukte aus Präfix, Funkprotokoll, Gerätebezeichnung, Kanalnummer und Datenpunktnamen einfach nur sperrig und für den Endanwender unübersichtlich. Eine prägnante Bezeichnung wie "Außentemperatur Ost" und "Außentemperatur West" wäre da wünschenswert. Umgekehrt könnte bei nur einem Datenpunkt die Legende überhaupt wegfallen.

**Comment by mdzio** [comment]
Dies ist teilweise bereits umgesetzt. Das Thema wird unter #50 weiter verfolgt.
