### ISSUE TITLE
Web-UI auf Synology nicht aufrufbar

### ISSUE THREAD

**Issue by tis-cs** [mdzio/ccu-historian#151]
Hallo,

ich habe die Installation standardmäßig inkl. Ersteinrichtung durchgeführt. 
Das Paket läuft anschließend auch, allerdings wird mir ein ERR_CONNECTION_REFUSED zurückgegeben, sobald ich http://ip:8084 aufrufe. Musste den Port ändern, da unter 8080 schon was läuft.

/var/log/synopkg.log sagt:

2019/01/22 11:17:33	start ccu-historian: begin to start version 2.0.0
2019/01/22 11:17:33	start ccu-historian 2.0.0 Begin pre-load apparmor
2019/01/22 11:17:33	start ccu-historian 2.0.0 End pre-load apparmor ret=[0]
2019/01/22 11:17:33	start ccu-historian 2.0.0 Begin start-stop-status start
2019/01/22 11:17:33	start ccu-historian 2.0.0 End start-stop-status start ret=[0]
2019/01/22 11:17:33	start ccu-historian: start version 2.0.0 successfully, result 0

Danke!

**Comment by mdzio** [comment]
Kann in diesem Fall jemand mit einem Synology-NAS helfen, da ich keins besitze.

**Comment by drMaxxi** [comment]
Ich habe eine Synology NAS und kein Problem - die aktuelle Version läuft gut. Falls ein Port bereits von einer Anwendung belegt ist, kann man denselben für keine zusätzliche benutzen und es ist notwendig einen anderen Port auszuwählen.

**Comment by tis-cs** [comment]
Ich habe es auf einem 918+ installiert und einen anderen Port (8084) statt default angegeben, da unter 8080 bereits etwas läuft. Gibt es an irgendeiner Stelle noch die Möglichkeit nach einem Log zu schauen oder so? Dass die Version auf einem anderen Gerät läuft bezweifle ich ja nicht, bringt mich so aber erst mal nicht weiter.

Danke für weitere Unterstützung.

**Comment by Sweatchcuk** [comment]
Hallo,
gleiches Problem. Seit dem Synology Update auf DSM 6.2.1-23824 Update 4 ist der Zugriff auf die Web-UI nicht mehr möglich. Verwende eine DS116.

Firewall hab versuchsweise deaktiviert, hab leider nichts geholfen.

Danke

**Comment by mdzio** [comment]
Der Fehlereintrag ist bereits sehr alt. Er wird nun geschlossen. Bei Bedarf bitte einen neuen Eintrag erstellen.
