### ISSUE TITLE
Raspberrymatic-Paket: Datenbank wir nach Neustart der CCU gelöscht

### ISSUE THREAD

**Issue by AndreasKlingbeil** [mdzio/ccu-historian#155]
Hallo!
Nach einem Neustart der CCU wir die Datenbank gelöscht und neu angelegt. Läßt sich das Start-Verhalten  ändern?
CCU-Historian 2.0.1
aktuelle Firmware: 3.41.11.20190126
CCU3 (Charly)
LG Andreas

**Comment by AndreasKlingbeil** [comment]
Ich habe verschiedene USB-Sticks getestet. Offenbar lag es am verwendeten USB-Laufwerk. Derzeit läuft CCU-Historian korrekt.

**Comment by mdzio** [comment]
Ein USB-Stick wird zwingend für das AddOn voraus gesetzt. Es sollte allerdings eine Prüfung und eine Warnmeldung eingebaut werden.
