### ISSUE TITLE
/media/usb0 Nutzung nur wenn USB Stick wirklich existent ist

### ISSUE THREAD

**Issue by jens-maus** [mdzio/ccu-historian#157]
CCU Historian loggt als CCU Addon auch ohne jeglichen installierten USB Stick in das `/media/usb0` Verzeichnis. Das hat aber zur folge das das `/media` tmpfs das ja komplett im RAM liegt erstens nach einem Reboot wieder komplett leer ist, oder nach längerer Nutzung den kompletten RAM des RaspberryPi aufbraucht. Besser wäre hier eine Prüfung durchzuführen ob `/media/usb0` ein aktuell gemountetes Verzeichnis ist und nur wenn das der Fall ist sollte `/media/usb0` genutzt werden. Ansonsten müsste eine Fehlermeldung ausgegeben werden um den Nutzer zu signalisieren das der USB Stick nicht installiert ist.

**Comment by jens-maus** [comment]
#155 scheint sich z.B. auf das hier dargestellte Problem zu beziehen.

**Comment by rucksman** [comment]
Toll wäre, wenn es als Alternative die Möglichkeit gäbe, statt eines USB Sticks ein gemountetes Laufwerk zu verwenden. Ich hatte bisher CuxD Highcharts im EInsatz und möchte nun wegen fehlender Weiterentwicklung zu CCU Historian wechseln. Für CuxD Highcharts hatte auf meinem kleinen Home-Server ein Verzeichnis eingerichtet und dann in raspberrymatic gemountet. Genau das gleiche wäe für CCU Historian auch toll.

**Comment by mdzio** [comment]
Generell kann das Datenbankverzeichnis über die Konfigurationsoption `database.dir` in der Datei `ccu-historian.config` beliebig geändert werden.

**Comment by rucksman** [comment]
Grade entdeckt und funktioniert, danke. Jetzt muss ich nur noch herausfinden, warzm meine HMIP devices nicht gefunden werden, aber das ist ein anderes Thema.

**Comment by mdzio** [comment]
Die Frage ist, wie kann dem Benutzer ein fehlender USB-Stick signalisiert werden. Die Prüfung könnte im Tcl-Skript config.cgi, das beim Aufruf der Historian-Seiten aus der Web-UI heraus aufgerufen wird, erfolgen. Zudem könnte auch die Firewall-Ports dort geprüft werden.
