### ISSUE TITLE
Gibt es eine Möglichkeit recalc und compact auch ohne stundenlangen Ausfall von ccu-historian zu nutzen?

### ISSUE THREAD

**Issue by cwapenhans** [mdzio/ccu-historian#159]
Hallo,

durch die Datenbankverkleinerungs läufe fehlt mir fast ein Tag in der Historie.

Ist es möglich, einen Teil auch laufen zu lassen, ohne ccu-historian offline zu schalten?

Grüße
  Christian

**Comment by mdzio** [comment]
Das ist zurzeit schwierig zu realisieren. Aber durch geplante interne Umbauten, wird es wahrscheinlich irgendwann leichter umzusetzen.

**Comment by mdzio** [comment]
Work around:
* Die Datenbank auf einen zweiten Rechner kopieren und dort `-recalc` und `-compact` durchführen, oder auf demselben Rechner in einem anderen Verzeichnis.
* Währenddessen den ursprüngliche CCU-Historian weiter aufzeichnen lassen.
* Wenn `-recalc` und `-compact` abgeschlossen sind, die Daten des letzten Tages aus dem ursprünglichen CCU-Historian exportieren (ab V2.7.0-beta3 möglich).
* Die neue Datenbank zum ursprünglichen CCU-Historian kopieren.
* Die Datenlücke importieren (ab V2.7.0-beta3 möglich).

**Comment by mdzio** [comment]
Die Umsetzung ist zu aufwändig. Ein Workaround existiert. Deshalb wird der Eintrag geschlossen.
