### ISSUE TITLE
automatisches Backup ... pfad Angabe auf Synology NAS

### ISSUE THREAD

**Issue by roe1974** [mdzio/ccu-historian#163]
Hi
Ich versuche ein automatisches Backup einzurichten......
Historian liegt auf:

/volume1/@appstore/ccu-historian

Ziel verzeichnis wäre:
/volume1/hmbackup/historian

sollte dann die config so aussehen ?

database.backup='/volume1/hmbackup/historian/db_%Y-%M-%D.zip'

Bitte um kurze Info :-)

PS: Ich habe unter devices.device1.type=CCU2  noch die CCU2 stehen ... nutze aber inzwischen ein Raspberrymatic mit Funkmodul .... sollte ich da CCU3 eintragen ? In der doc steht nur "CUSTOM_CCU" wenn KEIN Funkmodul eingebaut ist ........

lg Richard

**Comment by mdzio** [comment]
Die vorgeschlagene Option `database.backup` sollte so richtig sein.

Die CCU-Typen _CCU2_ und _CCU3_ werden vom CCU-Historian identisch behandelt. RaspberryMatic mit Funkmodul verhält sich wie eine _CCU2_ bzw. _CCU3_. Für RaspberryMatic ohne Funkmodul muss HM-IP über _CUSTOM_CCU_ abgeschaltet werden.
