### ISSUE TITLE
Neue Werte als Standard "Inaktiv und Versteckt"

### ISSUE THREAD

**Issue by Newbie-2** [mdzio/ccu-historian#167]
Was muss ich einstellen, das neue Werte als Standard in der Datenpunktliste als "Inaktiv und Versteckt" 
aufgenommen werden ? 
Ich finde es sehr aufwendig (auch bei der Erstinstallation) erst einmal alle 150 Datenpukte manuell auf "Inaktiv und Versteckt" anzuklicken, um dann im Anschluss die 20 Werte die mich interessieren als "Aktiv und Sichtbar" auszuweisen. 
Aus meiner Sicht wäre es besser, das ich aktiv werden muss um einen Datenpunkt aufzuzeichnen und nicht um ihn auszublenden, oder nicht aufzeichnen zu lassen.

**Comment by mdzio** [comment]
Am besten wäre die Möglichkeit, wenn das Verhalten bei neuen Datenpunkten konfigurierbar ist.

**Comment by cRemE-fReSh** [comment]
Vll. auch erweitert um eine Parameterabhängigkeit. Damit kann man beispielsweise für STICKY_UNREACH automatisch "Inaktiv und Versteckt" wählen, für neue Devices den STATE aber "aktiv und sichtbar" lassen.

**Comment by mdzio** [comment]
Es gibt nun eine neue Konfigurationsoption _historian.defaultActive_. Diese kann hierfür auf _false_ gesetzt werden.

**Comment by Newbie-2** [comment]
Via which link can I download the version the 2.4.0-beta.3

**Comment by mdzio** [comment]
This version is not yet released. But you will find it under the following address in the next days: https://github.com/mdzio/ccu-historian/releases

**Comment by mdzio** [comment]
Just released 2.4.0-beta.3.

**Comment by mdzio** [comment]
Die zusätzlichen Informationen wie Raum, Gewerk und Anzeigename sollten dennoch ausgelesen werden.

**Comment by libertyx82** [comment]
Wenn ich das richtig sehe dann setzt die Option

`historian.defaultActive=false`

Neue Datenpunkte auf inaktiv und versteckt?

Wären nicht zwei Optionen besser? also z.B.

```
historian.defaultActive=
historian.defaultHidden=
```

**Comment by mdzio** [comment]
Es gibt jetzt die Konfigurationsoptionen `historian.defaultDisabled `(ersetzt `defaultActive`) und `historian.defaultHidden`.
