### ISSUE TITLE
CCU-Addon MONIT Unterstützung

### ISSUE THREAD

**Issue by wakr70** [mdzio/ccu-historian#173]
Hallo Mathias,

es wäre super wenn der neue Watchdog service MONIT auch von CCU-Historian unterstützt werden würde:

Ein Beispiel das bei mir bereits funtioniert:

neu Datei erstellt für MONIT-Konfiguration:

**/usr/local/etc/monitCCUHistorian.cfg**

```
# historian daemon monitoring
check process ccu-historian with pidfile /var/run/ccu-historian.pid
    group historian
    start = "/etc/config/rc.d/ccu-historian start"
    stop = "/etc/config/rc.d/ccu-historian stop"
    restart = "/etc/config/rc.d/ccu-historian restart"
# restart after 3 cycles
    if not exist for 3 cycles then restart
# ccu-historian port
    if failed port 8082 for 3 cycles then restart
# H2 database port
    if failed port 8083 for 3 cycles then restart
# alarm message after 1 cycles
    if 1 restart within 1 cycles then
      exec "/bin/triggerAlarm.tcl 'ccu-historian restarted' WatchDog-Alarm"
```

Beim Spielen waren noch folgende zusätzlichen Einträge hilfreich:
```
set httpd port 2812
    allow admin:admin
    allow 10.0.0.0/255.255.255.0
```
Damit kann man dann über Port 2812 auf der CCU ein Monitor-Page öffnen mit einigen Infos und auch Start/Stop/Restart/Monitoren ein/aus ...

LG
Walter

**Comment by mdzio** [comment]
Danke für die Erstellung der Monit-Konfiguration. Damit aber nicht verschiedene Varianten des Add-Ons (CCU3 und RaspberryMatic) gepflegt werden müssen, kann die Monit-Unterstützung vielleicht besser selbst als Add-On selbst verpackt werden. Oder vielleicht macht das Installationsskript diese Unterscheidung. Ich denke, das Letztere ist wohl besser.

**Comment by wakr70** [comment]
Ich glaub das es ins Installationsskript gehört und auch die aktuelle oder neue Config bei der Erstellung miteinbeziehen sollte, damit die richtigen Port und Adressen dahinterstehn.

**Comment by jens-maus** [comment]
> Danke für die Erstellung der Monit-Konfiguration. Damit aber nicht verschiedene Varianten des Add-Ons (CCU3 und RaspberryMatic) gepflegt werden müssen, kann die Monit-Unterstützung vielleicht besser selbst als Add-On selbst verpackt werden. Oder vielleicht macht das Installationsskript diese Unterscheidung. Ich denke, das Letztere ist wohl besser.

Da braucht es eigentlich keine Unterscheidung. Die CCU3 hat zwar (noch) keine `monit` Unterstützung, aber sie stört es auch nicht wenn die Datei `/usr/local/etc/monitCCUHistorian.cfg` dort liegt. Die ignoriert sie ja einfach weil sie nichts damit anfangen kann. Vorteil ist dann sobald die CCU3 dann auch mal `monit` Unterstützung bekommt ist die Datei schon an der richtigen stelle.

**Comment by jens-maus** [comment]
Allerdings würde ich die Datei wie folgt aussehen lassen:

```
# historian daemon monitoring
check process ccu-historian with pidfile /var/run/ccu-historian.pid
    group addon
    start = "/etc/config/rc.d/ccu-historian start"
    stop = "/etc/config/rc.d/ccu-historian stop"
    restart = "/etc/config/rc.d/ccu-historian restart"
    if not exist for 1 cycles then restart
    if failed port 8082 for 5 cycles then restart
    if failed port 8083 for 5 cycles then restart
    if 1 restart within 1 cycles then
      exec "/bin/triggerAlarm.tcl 'ccu-historian restarted' WatchDog-Alarm"
```

Beachten müsste man allerdings auch noch das die Nutzung des Port 8083 ja meines Wissens Optional ist und daher ggf. die Prüfung ob unter 8083 etwas lauscht oder nicht man ggf. deaktivieren sollte.
