### ISSUE TITLE
called unknown instance 'getParamsetDescription' 'CENTRAL' ()

### ISSUE THREAD

**Issue by roe1974** [mdzio/ccu-historian#174]
in meinem log (RM) und im historian taucht plötzlich ein Datenpuntk auf
CUxD, Gerät "CENTRAL", Paramter "PONG"

woher kommt das ?

lg Richard

**Comment by mdzio** [comment]
An die Schnittstellen der CCU kann ein PING gesendet werden, um die Ereignisübertrragung zu testen. Die Schnittstellen antworten dann mit einem PONG. Dieses PONG ist allerdings wie eine Wertänderung von einem normalen Sensor verpackt. Der CCU-Historian ignoriert diese Wertänderung nun. Eine aktuelle RM-Version auch, soweit ich weiß.
