### ISSUE TITLE
CCU-Historian in Verbindung mit PHP-Server

### ISSUE THREAD

**Issue by bs0001** [mdzio/ccu-historian#176]
Hallo,

ich möchte mir gerne auf meinem Raspberry (Stretch 9), auf dem ich piVCCU3 und ccu-historian betreibe noch einen PHP-Server 7.3 installieren.
z.B. mittels folgender Anleitung:
https://tecadmin.net/install-php-debian-9-stretch/

Kommt sich das irgendwie mit piVCCU3 (dürfte ja nicht, da es ja im Container läuft) bzw. mit ccu-historian in die Quere oder kann das Paket problemlos installiert werden?

Viele Grüße
Bernd

**Comment by mdzio** [comment]
Das ist grundsätzlich mögloch. Es muss nur darauf geachtet werden, dass keine Netzwerk-Ports von Applikationen doppelt belegt sind (z.B. Port 80). Alle Netzwerk-Ports vom CCU-Historian können über die Konfigurationsdatei (ccu-historian.config) angepasst werden:
* database.webPort=8082
* database.tcpPort=9092
* database.pgPort=5435
* webServer.port=80
* devices.historianBinRpcPort=2099
* devices.historianXmlRpcPort=2098

(Manche Ports werden nur optional geöffnet.)

**Comment by bs0001** [comment]
Hallo,

 

Danke für die Info!

Ich habe die PHP-Installation durchgeführt und musste dann den neuen Webserver auf Port 81 umleiten, damit ich ccu-historian aufrufen kann.

Nun kann ich auch PHP-Dateien, allerdings aus dem Verzeichnis „/var/www/html/“ aufrufen, denn ich meine <IP-Adresse>:81/php-datei.php aufrufe.

 

Rufe ich allerdings mit dem normalen Aufruf <IP-Adresse>/php-datei.php auf (wenn die Datei auch im Verzeichnis „/opt/ccu-historian/webapp/historian“ drinnen liegt), dann wird sie mir nicht angezeigt.

Heißt ja, dass der Webserver des ccu-historian keine PHP-Dateien ausführen kann, oder?

 

Ist es irgendwie möglich, dass mein anderer Webserver, der unter Port 81 erreichbar ist, ebenfalls aus dem Verzeichnis „/opt/ccu-historian/webapp/historian“ seine Daten liest und nicht aus dem Standard-Apache-Verzeichnis „/var/www/html/“?

Was müsste ich dann anpassen?

 

Besten Dank und schöne Ostern!

Bernd

 

 

Von: mdzio <notifications@github.com> 
Gesendet: Dienstag, 16. April 2019 21:12
An: mdzio/ccu-historian <ccu-historian@noreply.github.com>
Cc: bs0001 <bs0001@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [mdzio/ccu-historian] CCU-Historian in Verbindung mit PHP-Server (#176)

 

Das ist grundsätzlich mögloch. Es muss nur darauf geachtet werden, dass keine Netzwerk-Ports von Applikationen doppelt belegt sind (z.B. Port 80). Alle Netzwerk-Ports vom CCU-Historian können über die Konfigurationsdatei (ccu-historian.config) angepasst werden:

*	database.webPort=8082
*	database.tcpPort=9092
*	database.pgPort=5435
*	webServer.port=80
*	devices.historianBinRpcPort=2099
*	devices.historianXmlRpcPort=2098

(Manche Ports werden nur optional geöffnet.)

**Comment by mdzio** [comment]
Du musst die Konfiguration des anderen Web-Servers anpassen, damit er Dateien aus dem gewünschten Verzeichnis bereit stellt.

Dynamische Web-Seiten kann der CCU-Historian allerdings auch selber verarbeiten. Er nutzt dies auch selber für die Web-Oberfläche. Ein bisschen [Dokumentation dazu findest Du im Handbuch](https://github.com/mdzio/ccu-historian/wiki#eigene-web-seiten).
