### ISSUE TITLE
Backup-Problem

### ISSUE THREAD

**Issue by 19Homer73** [mdzio/ccu-historian#179]
Hallo,

nach dem Update auf Version 2.2.0 beta 4 funktioniert das automatische Backup der Datenbank nicht mehr.

Folgender Eintrag habe ich im config-File (der selbe, der früher funktioniert hatte) stehen:
**database.backup='db_%Y-%M-%D.zip'**
Es wird kein Backup der Datenbank erstellt.

Vielen Dank im Voraus für Eure Hilfe,
Homer

**Comment by mdzio** [comment]
Bitte noch ein paar mehr Informationen: Auf welchem System läuft der CCU-Historian? Läuft der CCU-Historian als CCU-AddOn?
Kannst Du bitte eine detaillierte Log-Datei, [wie im Handbuch beschrieben](https://github.com/mdzio/ccu-historian/wiki#erstellung-eines-fehlerprotokolls), erstellen.

**Comment by 19Homer73** [comment]
Hallo,
mein Historian läuft seit zwei Jahren auf einem Raspberry Pi 3B, ohne Probleme.
Erst seit dem letzten Update, kommt es zu dem o. g. Problem.
Eine LOG-Datei kann ich leider nicht erstellen...
Mein config-File sieht folgenermaßen aus:
// CCU-Historian Konfiguration
// 
// Hinweise:
// Kommentarzeilen starten mit zwei Schrägstrichen (//). Alle Zeichen nach den Schrägstrichen
// werden ignoriert. Zeichenketten als Optionswert müssen von einfachen Anführungszeichen (')
// umschlossen sein. Weitere Informationen sind auch im Abschnitt 3 des Handbuchs zu finden.
//
// Liste der zur Verfügung stehen Konfigurationsoptionen mit ihren jeweiligen Standardwerten:
//
// logSystem.consoleLevel=Level.INFO
logSystem.fileLevel=Level.FINEST
// logSystem.fileName='./ccu-historian-%g.log'
logSystem.fileLimit=10000000
// logSystem.fileCount=5
logSystem.binRpcLevel=Level.FINER
database.dir='/opt/ccu-historian/data'
// database.name='history'
// database.user='sa'
// database.password='ccu-historian'
database.backup='db_%Y-%M-%D.zip'
// database.webEnable=true
// database.webPort=8082
// database.webAllowOthers=false
// database.tcpEnable=false
// database.tcpPort=9092
// database.tcpAllowOthers=false
// database.pgEnable=false
// database.pgPort=5435
// database.pgAllowOthers=false
webServer.port=8080
webServer.dir='/opt/ccu-historian/webapp'
// webServer.logLevel=Level.WARNING
webServer.historianAddress='192.168.178.9'
// webServer.trendDesigns ... (s.a. Abschnitt 7.4.1 im Handbuch)
// webServer.apiKeys=[]
// webServer.menuLinks ... (s.a. Abschnitt 4.4 im Handbuch)
historian.metaCycle=21600000 // 6 Stunden
// historian.bufferCount=5000
historian.bufferTime=21600000 
// devices.historianBinRpcPort=2099
// devices.historianXmlRpcPort=2098
devices.historianAddress='192.168.178.9'
// 
// Für jede Zentrale bzw. jedes Gerät müssen folgende zwei Optionen gesetzt werden
// (s.a. Abschnitt 3.2 im Handbuch):
// devices.device<Nr.>.type=<CCU1, CCU2 oder BINRPC> 
// devices.device<Nr.>.address='<IP-Adresse>'
//
// Optional können noch folgende Optionen gesetzt werden:
// devices.device<Nr.>.plugin<Nr.>.type=<CUXD oder HMWLGW>
// devices.device<Nr.>.sysVarDataCycle=30000
// devices.device<Nr.>.reinitTimeout=300000
// devices.device<Nr.>.writeAccess=false
// devices.device<Nr.>.watchdogProgram=''
// devices.device<Nr.>.watchdogCycle=300000 // 5 Minuten
// Bei Anbindung von mehreren Zentralen muss ein Präfix je Zantrale gesetzt werden!
// devices.device<Nr.>.prefix=''
//
// Es muss im Folgenden mindestens eine Zentrale bzw. Gerät konfiguriert werden:

// Typ der Zentrale: CCU1 oder CCU2
devices.device1.type=CCU2
// IP-Adresse der Zentrale
devices.device1.address='192.168.178.33'

// Falls CUxD verwendet wird, die Kommentarzeichen (//) vor folgender Zeile entfernen:
devices.device1.plugin1.type=CUXD

// Falls das HomeMatic Wired LAN Gateway verwendet wird, die Kommentarzeichen (//) vor 
// folgender Zeile entfernen:
// devices.device1.plugin1.type=HMWLGW

// Falls CUxD UND das HMWLGW verwendet wird, die Kommentarzeichen (//) vor folgenden
// zwei Zeilen entfernen:
// devices.device1.plugin1.type=CUXD
// devices.device1.plugin2.type=HMWLGW

// Zum Freischalten der Web-Links zu den Beispiel-Web-Seiten, die Kommentarzeichen (//) vor folgenden
// zwei Zeilen entfernen:
webServer.menuLinks.link1.text='DutyCycle letzte 24h'
webServer.menuLinks.link1.address='http://192.168.178.9:8080/query/trend.gy?i=242&w=1280&h=480'
webServer.menuLinks.link2.text='WZ letzte 24h'
webServer.menuLinks.link2.address='http://192.168.178.9:8080/query/trend.gy?i=111&w=1280&h=480'
webServer.menuLinks.link3.text='H2-HighChart'
webServer.menuLinks.link3.address='/custom/h2-highchart/H2-HighChart.gy'

**Comment by 19Homer73** [comment]
> 
> 
> Hallo,
> mein Historian läuft seit zwei Jahren auf einem Raspberry Pi 3B, ohne Probleme.
> Erst seit dem letzten Update, kommt es zu dem o. g. Problem.
> Eine LOG-Datei kann ich leider nicht erstellen...
> Mein config-File sieht folgenermaßen aus:
> // CCU-Historian Konfiguration
> //
> // Hinweise:
> // Kommentarzeilen starten mit zwei Schrägstrichen (//). Alle Zeichen nach den Schrägstrichen
> // werden ignoriert. Zeichenketten als Optionswert müssen von einfachen Anführungszeichen (')
> // umschlossen sein. Weitere Informationen sind auch im Abschnitt 3 des Handbuchs zu finden.
> //
> // Liste der zur Verfügung stehen Konfigurationsoptionen mit ihren jeweiligen Standardwerten:
> //
> // logSystem.consoleLevel=Level.INFO
> logSystem.fileLevel=Level.FINEST
> // logSystem.fileName='./ccu-historian-%g.log'
> logSystem.fileLimit=10000000
> // logSystem.fileCount=5
> logSystem.binRpcLevel=Level.FINER
> database.dir='/opt/ccu-historian/data'
> // database.name='history'
> // database.user='sa'
> // database.password='ccu-historian'
> database.backup='db_%Y-%M-%D.zip'
> // database.webEnable=true
> // database.webPort=8082
> // database.webAllowOthers=false
> // database.tcpEnable=false
> // database.tcpPort=9092
> // database.tcpAllowOthers=false
> // database.pgEnable=false
> // database.pgPort=5435
> // database.pgAllowOthers=false
> webServer.port=8080
> webServer.dir='/opt/ccu-historian/webapp'
> // webServer.logLevel=Level.WARNING
> webServer.historianAddress='192.168.178.9'
> // webServer.trendDesigns ... (s.a. Abschnitt 7.4.1 im Handbuch)
> // webServer.apiKeys=[]
> // webServer.menuLinks ... (s.a. Abschnitt 4.4 im Handbuch)
> historian.metaCycle=21600000 // 6 Stunden
> // historian.bufferCount=5000
> historian.bufferTime=21600000
> // devices.historianBinRpcPort=2099
> // devices.historianXmlRpcPort=2098
> devices.historianAddress='192.168.178.9'
> //
> // Für jede Zentrale bzw. jedes Gerät müssen folgende zwei Optionen gesetzt werden
> // (s.a. Abschnitt 3.2 im Handbuch):
> // devices.device<Nr.>.type=<CCU1, CCU2 oder BINRPC>
> // devices.device<Nr.>.address=''
> //
> // Optional können noch folgende Optionen gesetzt werden:
> // devices.device<Nr.>.plugin<Nr.>.type=
> // devices.device<Nr.>.sysVarDataCycle=30000
> // devices.device<Nr.>.reinitTimeout=300000
> // devices.device<Nr.>.writeAccess=false
> // devices.device<Nr.>.watchdogProgram=''
> // devices.device<Nr.>.watchdogCycle=300000 // 5 Minuten
> // Bei Anbindung von mehreren Zentralen muss ein Präfix je Zantrale gesetzt werden!
> // devices.device<Nr.>.prefix=''
> //
> // Es muss im Folgenden mindestens eine Zentrale bzw. Gerät konfiguriert werden:
> 
> // Typ der Zentrale: CCU1 oder CCU2
> devices.device1.type=CCU2
> // IP-Adresse der Zentrale
> devices.device1.address='192.168.178.33'
> 
> // Falls CUxD verwendet wird, die Kommentarzeichen (//) vor folgender Zeile entfernen:
> devices.device1.plugin1.type=CUXD
> 
> // Falls das HomeMatic Wired LAN Gateway verwendet wird, die Kommentarzeichen (//) vor
> // folgender Zeile entfernen:
> // devices.device1.plugin1.type=HMWLGW
> 
> // Falls CUxD UND das HMWLGW verwendet wird, die Kommentarzeichen (//) vor folgenden
> // zwei Zeilen entfernen:
> // devices.device1.plugin1.type=CUXD
> // devices.device1.plugin2.type=HMWLGW
> 
> // Zum Freischalten der Web-Links zu den Beispiel-Web-Seiten, die Kommentarzeichen (//) vor folgenden
> // zwei Zeilen entfernen:
> webServer.menuLinks.link1.text='DutyCycle letzte 24h'
> webServer.menuLinks.link1.address='http://192.168.178.9:8080/query/trend.gy?i=242&w=1280&h=480'
> webServer.menuLinks.link2.text='WZ letzte 24h'
> webServer.menuLinks.link2.address='http://192.168.178.9:8080/query/trend.gy?i=111&w=1280&h=480'
> webServer.menuLinks.link3.text='H2-HighChart'
> webServer.menuLinks.link3.address='/custom/h2-highchart/H2-HighChart.gy'

Es wird kein Log-File erstellt... Ich weiß nicht mehr weiter...

**Comment by 19Homer73** [comment]
Problem gefunden!!!
SD-Karte voll -> Daten gelöscht, läuft wieder!
