### ISSUE TITLE
Bidcos-Wired Geräte werden nicht angezeigt

### ISSUE THREAD

**Issue by gituser-rk** [mdzio/ccu-historian#181]
In der Liste der Datenpunkte werden bei mir nur Geräte vom Typ BidCos-RF, HmIP-RF und SysVar angezeigt.
Getestete CCU-Historian Version: 2.1.0 und 2.2.0-beta.4
Andere (iobroker) können über die XML-Schnittstelle die Werte der Bidcos-Wired Geräte sehen/schreiben.
Raspberrymatic Version: 3.45.7.20190504
Verwendetes CCU-Historian Paket: ccu-historian-addon-2.2.0-beta.4.tar.gz

**Comment by mdzio** [comment]
Für Geräte an der BidCos-Wired-Schnittstelle muss eine zusätzliche Konfigurationoption gesetzt werden (s.a. [Konfiguration der angeschlossenen Geräte](https://github.com/mdzio/ccu-historian/wiki#konfiguration-der-angeschlossenen-geräte) im Handbuch):
```
devices.device1.plugin1.type=HMWLGW
```
Der Pfad zur Konfigurationsdatei unter RaspberryMatic: `/usr/local/addons/ccu-historian/ccu-historian.config`

[Weitere Informationen zum CCU-Historian auf RaspberryMatic.](https://homematic-forum.de/forum/viewtopic.php?f=38&t=40872#p423714)
