### ISSUE TITLE
Grafik .. gleiche Y-skala für HM-Gerät und Variable

### ISSUE THREAD

**Issue by roe1974** [mdzio/ccu-historian#182]
Ich möchte gerne den Luftfeuchtewert (0-99%) eines Thermostats und die Helligkeit Balkon (Variable 0-99%) mit einer Y-Skala darstellen.
Obwohl der MIN und MAX Wert gleich ist, kommen zwei Y-Skalen.
Ist der Grund da es sich um eine Variable und einem Wert aus einem HM Gerät handelt ?

lg Richard

**Comment by mdzio** [comment]
Minimum, Maximum und Einheit der Datenpunkte müssen identisch sein, dann wird die selbe Y-Skala verwendet.

Weitere Informationen sind bei den [Tricks & Tricks](https://github.com/mdzio/ccu-historian/wiki/Tipps-&-Tricks#gemeinsame-skalen-f%C3%BCr-datenpunkte) zu finden.

**Comment by mdzio** [comment]
Siehe auch #132.

**Comment by roe1974** [comment]
MIN und MAX sind identisch ......
nur ist bei der Variable der Datentyp "FLOAT" und der Wetterkanal des Thermostats ist vom Datentyp "INTEGER"
D.h. es ist nicht nur der MIN / MAX Wert entscheidend ... richtig ?

lg RIchard

**Comment by mdzio** [comment]
Ich habe nochmal im Quelltext nachgeschaut (trend.gy, Zeile 104), und es ist tatsächlich so wie von Dir beschrieben. Der Datentyp wird auch verglichen. 

Jetzt muss ich nur noch überlegen, warum ich damals den Typ mit aufgenommen habe.

Könntest Du testweise mal die Zeile 104 von
```
		def axisKey=[dataPoint.attributes.type, dataPoint.attributes.unit, dataPoint.attributes.minimum, dataPoint.attributes.maximum]
```
nach
```
		def axisKey=[dataPoint.attributes.unit, dataPoint.attributes.minimum, dataPoint.attributes.maximum]
```
abändern.

**Comment by roe1974** [comment]
dann funktoniert es .....
aber jetzt eine frage ... warum fragst du das überhaupt ab ?
ich kann doch mehrere y-achsen definieren wenn ich möchte ... warum muss überhaupt min/max gleich sein wenn ich die gleiche y achse will ?
beispiel: Variable A hat min/max 0/99 und Variable B hat min/max 0/50
Die können doch trotzdem die gleiche y-achse haben ???

lg Richard

**Comment by mdzio** [comment]
Y-Achsen können nicht festgelegt werden. Die Zuordnung wird immer automatisch durchgeführt. Eventuell verwechselst Du es mit Datenpunktgruppen.

Den Typ als Kriterium habe ich wohl aufgenommen, da die Typen ACTION, BOOL und ALARM alle Einheit=leer, Minimum=0,0 und Maximum=1,0 haben. Die ACTION-Datenpunkte müssen aber gesondert behandelt werden (wg. der Symboldarstellung).

Ich habe aber schon eine Idee, wie das unter einen Hut gebracht werden kann.

**Comment by roe1974** [comment]
@mdzio  ...... 
Könnte man jetzt mit dieser Änderung ein HM Thermostat (Temperatur Range Min/Max -10/+50) und einen HM Temperatursensor (Temperatur Range Min/Max -40/+80) auf der gleichen Y-Skala darstellen ?

lg RIchard

**Comment by mdzio** [comment]
Dann werde ich es nochmal abändern: Wenn ein Datenpunkt eine Einheit besitzt (z.B. °C), dann wird Minimum und Maximum ignoriert. Dadurch landen alle Temperaturen immer auf der selben Skala. Wenn ein Datenpunkt keine Einheit besitzt, dann werden Mininum und Maximum ausgewertet.

**Comment by roe1974** [comment]
das klingt perfekt !
lg richard

**Comment by mdzio** [comment]
Für einen Vorabtest kann die Datei trend.gy mit [dieser Version](https://raw.githubusercontent.com/mdzio/ccu-historian/master/ccu-historian/src-webapp/query/trend.gy) ersetzt werden.
