### ISSUE TITLE
Keine Graphen in Synology Version

### ISSUE THREAD

**Issue by muellerjm** [mdzio/ccu-historian#185]
Es werden keine Graphen angezeigt. Trotz aktuellem OS, Java 8, etc..

**Comment by mdzio** [comment]
Ist denn die Web-Oberfläche vom CCU-Historian erreichbar?

**Comment by muellerjm** [comment]
ja, einwandfrei. Es sind nur die Platzhaltericons zu sehen. Ich habe eine Synology mit 2 Festplatten. Im Logfile sehe ich nur ein Warning und das ein Zeitstempel nicht passt 01.0.1.970 (nur bei 2 Einträgen).

**Comment by mdzio** [comment]
Wie sieht die Fehlermeldung in der Log-Datei genau aus?

**Comment by muellerjm** [comment]
Hallo,
schon mal vielen Dank für die Unterstützung. Ich weiß das zu schätzen...

Ich finde 4 Zeilern mit dem Suchwort "Error"

019-08-02 10:42:57|WARNING|Returning error message 'No such property: methodName for class: java.lang.String', 0
2019-08-02 10:43:07|WARNING|Returning error message 'No such property: methodName for class: java.lang.String', 0

Fontconfig error: Cannot load default config file

at org.eclipse.jetty.io.UncheckedPrintWriter.setError(UncheckedPrintWriter.java:107)

**Comment by mdzio** [comment]
**Fontconfig error** deutet auf eine Headless-Java-Variante hin. Das bedeutet, dass diese Variante keine Schriften (z.B. für die Legenden der Trends) verarbeiten kann.

Was gibt denn der Befehl _java -version_ aus?

**Comment by muellerjm** [comment]
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (linux-gnu build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

oh... da habe ich auch was im Homematic Forum gelesen. Gibt es da wohl eine andere Version für die Synology?

Dankeschön

**Comment by muellerjm** [comment]
Das war es. Vielen Dank!. Man muss in der Synology im Paket ein Update machen. Ich meine nicht die Aktualisierung im Paketzentrum! Man muss das Paket im Paketmanager öffnen. Darin ist dann die Aktualisierung des Javas... Schön versteckt....
