### ISSUE TITLE
Kommandozeilenoption zum Leeren inaktiver Historien

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-historian#198]

**Comment by mdzio** [comment]
Dies könnte aber auch über die Skriptumgebung erreicht werden.

**Comment by cRemE-fReSh** [comment]
Finde ich eine super Idee! Dann wird man einfacher den lästigen Kram los, der sich immer mal wieder "einschleicht" (z.B. UNREACH, STICKY_UNREACH, LOWBAT,...), bevor man ihn deaktivieren kann.
+1 Vote

**Comment by mdzio** [comment]
Über die Skriptumgebung kann es mit [diesem Skript](https://github.com/mdzio/ccu-historian/wiki/Skripte#histrorien-von-inaktiven-datenpunkten-löschen) erreicht werden.
