### ISSUE TITLE
h2db version 1.4.199 erzeugt Probleme

### ISSUE THREAD

**Issue by nhulsch** [mdzio/ccu-historian#199]
Beim Update von 2.2.2 auf 2.2.3 ging mir die Datenbank bereits kaputt und musste neugemacht werden.
Von 2.2.3 auf 2.3.0 ging die Datenbank ebenfalls wieder kaputt (Größe 5MB), was ich mir einfach nicht erklären kann, da ich in der Vergangenheit nie damit Probleme hatte.
Es sind immer die gleichen Fehlerbilde:

> Caused by: java.lang.IllegalStateException: Reading from nio:/media/usb1/ccu-historian/history.mv.db failed; file length 5320704 read length 1024 at 19618479 [1.4.199/1]

Auch die Nutzung des Recover Tools von H2 brachte den identischen Fehler:
> /opt/java/bin/java -cp /usr/local/addons/ccu-hist*/ccu-hist*/lib/h2-1.4.199.jar org.h2.tools.Recover
> Exception in thread "main" java.lang.IllegalStateException: Reading from nio:/media/usb1/ccu-historian/history.mv.db failed; file length 5320704 read length 1024 at 19618479 [1.4.199/1]

Führe ich den identischen recover Befehl mit der noch vorhandenen 1.4.197 aus, wird die "korrupte" Datenbank ohne Probleme gelesen und mit ein Dump-File erzeugt.

Ich gehe also davon aus, dass irgendein Verhalten in 1.4.199 "kaputt" ist, aktuell ist Version 1.4.200.

**Comment by nhulsch** [comment]
Nachtrag, das aus der 1.4.197 erstelle Dumpfile lies sich mit der 1.4.199 wieder zu einer Datenbank formen:
>  /opt/java/bin/java -cp /usr/local/addons/ccu-hist*/ccu-hist*/lib/h2-1.4.199.jar org.h2.tools.RunScript -url jdbc:h2:./history -script history.h2.sql -checkResults

Danach lies sich die 2.3.0 auch ohne weiteres mit den alten Daten starten.

**Comment by mdzio** [comment]
Ist die korrupte Datenbank noch greifbar? Dann bitte einmal per E-Mail zuschicken.
Ich werde die H2-Datenbank in der nächsten Version mal auf 1.4.200 aktualisieren.

**Comment by nhulsch** [comment]
Leider nicht, hab mir das Original mit Tests zwischen .197 und .199 kaputt gespielt (Downgrade von einer .199 in .197 als .db File geht schief ;) ), sodass ich nur noch den Dump hatte.

**Comment by roe1974** [comment]
Habe auf der Synology auf 2.3.0 upgedatet und stehe jetzt vor dem selben Problem .... defekte db :(
Im Synology Paket ist noch die 1.4.199 enthalten..... was mache ich jetzt am besten ... ?!?!

**Comment by mdzio** [comment]
Die eingebettete Datenbank wurde in der CCU-Historian V2.3.1 auf die V1.4.200 aktualisiert. Ich schließe mal diesen Eintrag, bis ein ähnlicher Fehler mit der V2.3.1 auftritt.
