### ISSUE TITLE
Hohe CPU Auslastung durch DB Dateizugriff seit V2.3.1

### ISSUE THREAD

**Issue by cRemE-fReSh** [mdzio/ccu-historian#203]
Hallo,

Seit der V2.3.1, in der lt. Release Notes offensichtlich auch etwas an der DB gemacht wurde, ist folgendes zu beobachten:

- Hohe CPU Load (>20%)
- Ständige DB Schreibaktivitäten
- Ständig schwankende DB Größe

Ich bin wohl nicht der einzige:
https://homematic-forum.de/forum/viewtopic.php?f=38&t=55167

Ich setze auf einer Synology DS918+ die Docker Images von xjokay ein.
Testweise habe ich 3 Versionen parallel (auf Basis des gleichen DB Files, etwa 1,6GB) getestet: V2.2.0, V2.3.0, V2.31.
Die V2.2.0 und V2.3.1 dümpelt im Idle bei etwa ~2% herum, teilweise weniger.
Die V2.3.1 konstant >20% und beschäftigt die Festplatte, was das Zeug hält.
![CPU_Load_Idle](https://user-images.githubusercontent.com/42785404/70951836-cc9ed080-2064-11ea-868c-e9561bf0660c.png)

Edit: Auch bei mir ist seit dem Update auf die V2.3.1 die Datenbankgröße um mehr als die Hälfte halbiert. Dass Daten fehlen, konnte ich aber nicht feststellen. Das sieht eher nach besserem Housekeeping der DB aus... Evtl. ist auch das die Ursache für die massive Auslastung.
Beim Suchen noch was gefunden. Evtl. hilfts: https://github.com/h2database/h2database/issues/2206

Wenn ich mir Infos helfen kann, bitte melden!

Viele Grüße

**Comment by roe1974** [comment]
Genau das gleiche hier auf einer DS218+ .... Der historian Prozess rennt bei 25-30% CPU Auslastung ... und das permanent :-(

**Comment by roe1974** [comment]
... komme ich irgendwie auf die 2.3.0 (installiert auf der SYN via spk file) zurück ?
lg RIchard

**Comment by mdzio** [comment]
Bleibt die CPU-Last auch über längere Zeit so hoch? Z.B. über 24 Stunden?

**Comment by roe1974** [comment]
Ja ... ist seit dem die 2.3.1 läuft ... die ganze Zeit.
Es ist mir aufgefallen, da die Platten die ganze Zeit schreiben (hörbar in der Nacht).
Laut Ressourcen-Monitor ist die CPU Last permanent so hoch ....
lg Richard

**Comment by roe1974** [comment]
Hier der graph dazu .... seit der Installation von 2.3.1 konstant oben ...
![Unbenannt](https://user-images.githubusercontent.com/30420568/71090901-573a1980-21a4-11ea-97de-90f57e712547.JPG)
lg Richard

**Comment by cRemE-fReSh** [comment]
Kann ich auch bestätigen.

**Comment by mdzio** [comment]
Ich kann das Problem leider auf Linux mit Java 8 oder Windows mit Java 12 nicht nachvollziehen. Ein Synology-NAS habe ich leider nicht. Den Ersteller des Pakets werde ich mal kontaktieren.

Eventuell hilft ein Java-Update auf der Synology.

**Comment by roe1974** [comment]
java ist aktuell ....
könnte man auf 2.3.0 zurück ? ... oder reicht es die h2-1.4.200.jar gegen die 199er auszutauschen ?
lg richard

**Comment by mdzio** [comment]
Das Austauschen nur der Datei h2-1.4.200.jar reicht nicht. Es muss auch die ccu-historian.jar ausgetauscht werden.

**Comment by roe1974** [comment]
dann würde es gehen ?

**Comment by mdzio** [comment]
Ja. Oder einfach die V2.3.0 darüber installieren.

**Comment by cRemE-fReSh** [comment]
Java ist auf aktuellster Version. Daran kann es nicht liegen (AdoptOpenJDK 8u232).

**Comment by roe1974** [comment]
@cRemE-fReSh .... wie hast du 8u232 auf die SYN bekommen ? ... mit "boardmitteln" bekommt man nur 211 drauf ?!?!?

**Comment by cRemE-fReSh** [comment]
Offtopic...  Auf der Synology bekommt man die 231 drauf. Dazu Java8 aus dem Paketinstallier installieren, bei Oracle die aktuellste Version runterladen und über die App installieren.
Bei mir aber läufts auf der Synology im Docker. Da bin ich auf der 232.

**Comment by x-jokay** [comment]
Hab das Release `2.3.1` als Container gelöscht, `latest` entspricht wieder `2.3.0`.

**Comment by mdzio** [comment]
In der CCU-Historian V2.3.2 wird wieder die V1.4.199 anstatt der V1.4.200 der H2Datenbank verwendet.
