### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by mahiso** [mdzio/ccu-historian#206]
CCU-Historian: V2.3.0
Docker Image mit openjdk:11-jre als Basis.
Beim Start des CCU Historian erfolgt folgende Warnung:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/opt/ccu-historian/lib/groovy-2.5.8-indy.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by mdzio** [comment]
Ab der Java Version 9 erscheint diese Warnmeldung, da die vom CCU-Historian verwendete Groovy-Version 2.5  noch nicht das Java-Modul-System unterstützt. Diese Warnmeldung kann ohne Bedenken ignoriert werden. Der CCU-Hisstorian kann mit den Java-Versionen 8 bis 13 verwendet werden.

Abhilfe schafft erst die Umstellung auf Groovy-Version 3.0.
