### ISSUE TITLE
Interne Energie Counter Variablen in CCU loggen?

### ISSUE THREAD

**Issue by oriziena** [mdzio/ccu-historian#207]
Hallo,

ich betreibe verschiedene Energiezähler, diese legen ja interne Programme in der CCU an um den Zählerwert nach Stromausfall eines Gerätes nicht zu verlieren. 

Ist es möglich diese Werte auch im Historian mitzuloggen? 

Hier mal ein Beispiel:
object oSysVarEnergyCounter = dom.GetObject('svEnergyCounter_22099_00089A499F8B7A:5');

Natürlich könnte ich in dem Programm einfach die Werte in eine eigene Variable schreiben... allerdings wäre das ja  nicht gerade sparsam. Freue mich auf eine Antwort... 

Danke und Grüße
Ori

**Comment by oriziena** [comment]
@mdzio großartig, vielen dank... gibt es bereits einen Plan, wann 2.4.0-beta.1 publiziert wird ?  gerne teste ich die Änderung in meinem Aufbau ....

historian läuft als addon auf der rasperrymatic...

**Comment by roe1974** [comment]
Sehr cool ..... die Wettersensoren haben auch solche Variablen ;)

**Comment by mdzio** [comment]
Ich denke, dass diese Version am nächsten Wochenende veröffentlicht wird.

**Comment by oriziena** [comment]
@mdzio darf ich nochmals nach der neuen beta fragen? ... ;(

**Comment by mdzio** [comment]
Bitte zu probieren!

**Comment by oriziena** [comment]
@mdzio bisher keine auffälligkeiten...

interne sensoren stehen zu auswertung in der DB bereit..
cpu usage des rpi ist auch im grünen bereich bisher...
