### ISSUE TITLE
Exception: connect timed out ( CCU-Historian V2.4.0-beta.2 )

### ISSUE THREAD

**Issue by Raschi01** [mdzio/ccu-historian#210]
2020-03-13 14:09:17|SEVERE |Exception: connect timed out
2020-03-13 14:09:17|SEVERE |Detail: java.net.SocketTimeoutException: connect timed out
        at mdz.hc.itf.hm.HmScriptClient.execute(HmScriptClient.groovy:352)
        at mdz.hc.itf.hm.HmScriptClient.getSystemVariableValues(HmScriptClient.groovy:104)
        at mdz.hc.itf.hm.HmSysVarInterface$_readVariables_closure3.doCall(HmSysVarInterface.groovy:120)
        at mdz.hc.itf.hm.HmSysVarInterface$_readVariables_closure3.call(HmSysVarInterface.groovy)
        at mdz.Exceptions.lambda$0(Exceptions.java:84)
        at mdz.Exceptions.catchToLog(Exceptions.java:74)
        at mdz.Exceptions.catchToLog(Exceptions.java:84)
        at mdz.hc.itf.hm.HmSysVarInterface.readVariables(HmSysVarInterface.groovy:118)

Ich hoffe einem Unwissenden kann geholfen werden. DANKE

**Comment by mdzio** [comment]
Der CCU-Historian kann keine Verbindung zur CCU herstellen.

Stimmen die IP-Adressen in der ccu-historian.config? Ist die Firewall in der CCU richtig konfiguriert?

**Comment by Raschi01** [comment]
Er bekommt eine Verbindung. Alle Ports sind offen. Es werden auch alle Datenpunkte geloggt. Nur in zyklischen Abständen die Info und nach 1 - 2 Tagen bleibt der Historian stehen. Dann Neustart. Danach wieder das gleiche. Er startet alles bis zur Info Port 80. Danach wieder die Rythmische Ausgabe. 

Mit freundlichem Gruß
         Hans-Jörn Raschendorfer 

-----Original Message-----

**Comment by mdzio** [comment]
Wie groß sind die zyklischen Abstände der Fehlermeldung? Werden die Systemvariablen der CCU aufgezeichnet?

**Comment by Raschi01** [comment]
Hallo. Leider erst jetzt. Nach dem Neustart dauert es etwas. Dann fängt es plötzlich an. Nicht immer gleicher Abstand jedoch meist alle 15 sec. 

Die System Variablen werden fehlerlos abgefragt. 
Gruß 

Mit freundlichem Gruß
         Hans-Jörn Raschendorfer 

-----Original Message-----

**Comment by mdzio** [comment]
Vielleicht hilft eine detaillierte Log-Datei weiter (s.a. [Handbuch](https://github.com/mdzio/ccu-historian/wiki#erstellung-eines-fehlerprotokolls)). Eine Aufzeichnung von einem Tag sollte reichen.

**Comment by Raschi01** [comment]
Hallo. 
Mache ich. Mich wunder halt nur das die Ausgabe, die ich geschickt habe alle 15 sec. Kommt. Muss ja einen Grund haben. Der Historian funktioniert ja soweit. Es werden alle Werte mitgeschrieben. Wenn auch die Stabilität merkwürdig ist. Ab und zu ist der Webserver nicht zu erreichen. Dann hilft nur ein Neustart des Historian.

Mit freundlichem Gruß
         Hans-Jörn Raschendorfer 

-----Original Message-----

**Comment by Raschi01** [comment]
Hallo. Ich habe mal eine Logdatei angefügt. Hier ist in jedem Fall der Fehler zu sehen. Ich wollte schon Bilder schicken. Das ging nicht. Auch bleibt der Historian ab und zu Stehen oder startet nicht richtig. Die Ausgabe ist bis Web Server port:80 alles korrekte. Man denkt OK. Alles in Ordnung. Ruft man die Webseite auf werden keine Device angezeigt. Nür die Überschrift der Webseite. Nach Neustart ist alles wieder ok. 
connect timed out

Mit freundlichem Gruß
         Hans-Jörn Raschendorfer 

-----Original Message-----

**Comment by Raschi01** [comment]
Hallo Mathias. 
Danke für die Unterstützung. Ich habe den Fehler gefunden. Mein D-LAN Netz war instabil. Fehler beseitigt. Historian, Fehler weg. 

Mit freundlichem Gruß
         Hans-Jörn Raschendorfer 

-----Original Message-----

**Comment by Raschi01** [comment]
Hallo Mathias. 
Ich melde mich noch mal. 
Der Historian ist ein tolles Programm, wenn es läuft. 
Aber so wie ich es sehe bleibt bei jeder Unterbrechung im Netzwerk stehen. Es gibt keinerlei Anzeigen im Dosfenster. 
Der Webserver kann erreicht werden, zeigt jedoch keine Datenpunkte. 
Nun strg + C im Fenster des Historian und er läuft wieder. 
Gibt es keine Möglichkeit das er sich nach dem nicht erreichen der Raspberrymatic sich wieder selbst verbindet? Ich dachte ich hätte ein Programm, was jetzt 1 Jahr vor sich hinläuft. Hier sehe ich jeden Tag nach. 
Das Problem sind bei mir die Devolo D-LAN Adapter. Hier Abe ich warum auch immer ab und zu keine Verbindung. Schreibe ich mit einem Dauerping mit. Ganz kurze Unerreichbarkeit. Für den Historian der Tot. 

Mit freundlichem Gruß
         Hans-Jörn Raschendorfer 

-----Original Message-----

**Comment by mdzio** [comment]
Der CCU-Historian überwacht stetig die Verbindung zur CCU und baut sie auch nach Verbindungsabbrüchen wieder auf. Die CCU baut über Netzwerk ein Rückkanal zum CCU-Historian auf. Die CCU reagiert aber sehr empfindlich auf Netzwerkprobleme, da sie direkte Auswirkungen auf z.B. die Programmausführung der CCU haben.

Generell muss also für eine stabile Netzwerkverbindung gesorgt werden. WALN und Power-Line machen da nur Probleme.

Vielleicht finde ich in der Log-Datei noch Hinweise, um die Wiederherstellung der Verbindung zu verbessern. Bitte per E-Mail an info Klammeraffe ccu-historian.de schicken.
