### ISSUE TITLE
Connection timeout / Java prozess hängt

### ISSUE THREAD

**Issue by pzystorm** [mdzio/ccu-historian#211]
Hi,
ich habe auch ein komisches Problem und bräuchte ein bisschen Hilfe.
Seit ein paar Tagen startet ccu-historian nicht mehr (2.2.2) und lässt sich auch nicht mehr updaten.

Rufe ich Port 8082 im Browser auf, kriege ich einen Timeout.
Rufe ich über die RaspberryMatic Oberfläche --> Systemsteuerung --> ccu-historian --> Einstellungen auf (http://ipblabla/addons/ccu-historian/config.cgi?sid=blabla) kriegen ich auch einen Timeout.

Die Logs sagen das:
```
2020-03-27 16:37:21|INFO   |Starting web server
2020-03-27 16:37:21|INFO   |jetty-7.2.2.v20101205
2020-03-27 16:37:22|INFO   |NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
2020-03-27 16:37:22|INFO   |Started SelectChannelConnector@0.0.0.0:8082
2020-03-27 16:37:22|INFO   |Web server port: 8082
2020-03-27 16:37:38|WARNING|Device BidCos-RF.CENTRAL.PONG does not exist
2020-03-27 16:37:38|WARNING|Device BidCos-RF.OEQ0629480:0.CONFIG_PENDING does not exist
2020-03-27 16:37:38|WARNING|Device BidCos-RF.PEQ0626030.DUTY_CYCLE does not exist
2020-03-27 16:37:55|WARNING|Value  is not valid for data type ENUM of data point SysVar.9692.VALUE
2020-03-27 16:38:25|WARNING|Value  is not valid for data type ENUM of data point SysVar.9692.VALUE
2020-03-27 16:38:55|WARNING|Value  is not valid for data type ENUM of data point SysVar.9692.VALUE
2020-03-27 16:39:25|WARNING|Value  is not valid for data type ENUM of data point SysVar.9692.VALUE
```

Ist die Warning schlimm? Was soll mir das sagen?

Und wenn ich mir das history file angucke:
```
# ls -alh /usr/local/sdcard/ccu-historian/
total 1G
drwxr-xr-x    2 root     root        4.0K Oct  6 22:57 .
drwxr-xr-x    4 root     root        4.0K Aug  5  2018 ..
-rw-r--r--    1 root     root        1.1G Mar 27 16:37 history.mv.db
-rw-r--r--    1 root     root        2.9K Aug  5  2018 history.trace.db
```
Ist 1Gb schon an der Grenze, was das Ding handhaben kann?

Der Java-Prozess scheint sich nämlich komplett aufzuhängen.
Wenn ich mir mit "ps faux | grep historian" die PID raussuche und mit kill -15 versuche, den Prozess zu beenden, klappt es nicht. Nur mit "kill -9" klappts.

Hat jemand ne Idee? :)

![image](https://user-images.githubusercontent.com/765650/77776381-365c4c80-704e-11ea-9e51-594bc9720972.png)

**Comment by mdzio** [comment]
Sehe ich das auf den Screen-Shot richtig, dass Du etliche CCU-Historian-Prozesse hast? Das darf natürlich nicht sein. Bitte alle Prozesse mal beenden und den CCU-Historian nur einmal starten.

Das Herunterfahren des CCU-Historians dauert bei großen Datenbanken länger. 2 Minuten sollten dem CCU-Historian gegeben werden. kill -9 kann die Datenbank beschädigen.

Die Datenbankgröße ist in Deinem Fall unproblematisch.

Die Warnungen können ignoriert werden.

**Comment by pzystorm** [comment]
Vielen Dank schon mal für die Antworten :)

Der Screenshot ist von htop. htop listet grundsätzlich Prozesse UND die Threads.
Es läuft nur ein Prozess mit der PID 1053. Der Rest sind Threads.

Kann man irgendwie einen DB-Check machen, ob das File ok ist?
Ich kenne mich mit dieser H2 MvStore Datenbank nicht so gut aus. Aber da es scheint es gar kein Command Line Tool zu geben... ?! 

Noch eine Frage: Ich habe zwei verschiedene H2 Versionen im ccu2-historian Verzeichnis gefunden, 197 und 199:
```
root@ccu2:/usr/local/addons/ccu-historian/ccu-historian/lib# ls -al
total 22068
drwxr-xr-x    2 root     root          4096 Oct  6 22:57 .
drwxr-xr-x    4 root     root          4096 Mar 27 17:09 ..
-rw-r--r--    1 root     root         41123 Jun 13  2018 commons-cli-1.2.jar
-rw-r--r--    1 root     root         53820 Oct  6 17:47 commons-cli-1.4.jar
-rw-r--r--    1 root     root       5548389 Oct  6 17:47 groovy-2.5.8-indy.jar
-rw-r--r--    1 root     root       7164868 Jun 13  2018 groovy-all-2.4.15.jar
-rw-r--r--    1 root     root         75356 Oct  6 17:47 groovy-cli-commons-2.5.6.jar
-rw-r--r--    1 root     root         11690 Oct  6 17:47 groovy-dateutil-2.5.6.jar
-rw-r--r--    1 root     root        132857 Oct  6 17:47 groovy-json-2.5.6.jar
-rw-r--r--    1 root     root         26634 Oct  6 17:47 groovy-servlet-2.5.6.jar
-rw-r--r--    1 root     root         83837 Oct  6 17:47 groovy-sql-2.5.6.jar
-rw-r--r--    1 root     root        100940 Oct  6 17:47 groovy-templates-2.5.6.jar
-rw-r--r--    1 root     root         80626 Oct  6 17:47 groovy-test-2.5.8-indy.jar
-rw-r--r--    1 root     root        222029 Oct  6 17:47 groovy-xml-2.5.6.jar
-rw-r--r--    1 root     root         63631 Oct  6 17:47 groovy-xmlrpc-0.8.jar
-rw-r--r--    1 root     root       1916539 Jun 13  2018 h2-1.4.197.jar
-rw-r--r--    1 root     root       2166760 Oct  6 17:47 h2-1.4.199.jar
-rw-r--r--    1 root     root       1282424 Oct  6 17:47 ivy-2.4.0.jar
-rw-r--r--    1 root     root         32374 Oct  6 17:47 javax.el-api-1.1.2.jar
-rw-r--r--    1 root     root        115567 Oct  6 17:47 javax.servlet.jsp_2.1.0.v201004190952.jar
-rw-r--r--    1 root     root        326291 Oct  6 17:47 jcommon-1.0.23.jar
-rw-r--r--    1 root     root       1429819 Oct  6 17:47 jetty-all-7.2.2.v20101205.jar
-rw-r--r--    1 root     root       1570157 Oct  6 17:47 jfreechart-1.0.19.jar
-rw-r--r--    1 root     root         97693 Oct  6 17:47 servlet-api-2.4.jar
```
Soll ich die ältere mal löschen?
Oder ist das egal und es wird immer die neueste geladen?

Und... Warum klappt das Update auf die neue ccu2-historian Version per RaspberryMatic GUI nicht? Wie kann ich da gucken, woran es liegt, dass er nicht updated? Was habe ich da noch für Möglichkeiten?

**Comment by pzystorm** [comment]
Ok, habs nun reparieren können...
Ich habe mal alle alten Libs vom Juni gelöscht und nur die Dateien vom Oktober drauf gelassen.
Dann habe ich nochmal ein Update auf 2.3.0 versucht - das klappte dann.

Dann hab ich Port 8082 in der Firewall-Config freigeben müssen...
Und dann kam auch endlich wieder die GUI von ccu2-historian und zeigte mir Datensätze.

Jetzt sieht der Hauptprozess so aus:
```
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
 1065     1 root     S     612m  63%   3% /opt/java/bin/java -Xmx512m -Djava.util.prefs.userRoot=/usr/local/addons/ccu-historian -Djava.util.prefs.systemRoot=...
```
d.h. er belegt nur 63% Memory, sorgt aber für keine hohe CPU Load mehr.

**Comment by mdzio** [comment]
Info: VSZ gibt die Größe des virtuellen Adressraums zurück, der gar nicht komplett genutzt wird. RSS gibt die tatsächliche RAM-Belegung zurück und sollte viel geringer sein.
