### ISSUE TITLE
V2.4.0-beta.2 Fehler: The database has been closed [90098-199]

### ISSUE THREAD

**Issue by oriziena** [mdzio/ccu-historian#213]
Hi,

die datenbank stürzt im laufenden betrieb irgendwann ab...

was genau hilft dir am meisten an debugdaten? ich werde mal logmeldung meines rapsi an einen externen syslog server schicken um meine sd nicht überzubelasten... vielleicht kommt dabei was raus.

grüße
ori

<img width="1251" alt="Bildschirmfoto 2020-03-30 um 17 48 52" src="https://user-images.githubusercontent.com/2290949/77933175-cd274400-72ae-11ea-8de1-e746b7251bac.png">

**Comment by FUEL4EP** [comment]
Hi,

bei mir half bei derselben Fehlermeldung das Anlöten von einem 470uF/10V Elko und einem 0,15uF Kondensator an die Pins 5V/GND der GPIO Steckerleiste des Raspberry Pis. Näheres siehe

http://www.johnes.eu/rpi/pages/power/kondensator.php

Als USB Stick sollte nur ein USB2.0 Stick mit maximal 32GByte verwandt werden. Sonst kann der erhöhte Strombedarf zu Spannungseinbrüchen führen, die dann dern USB Stick auf readonly schalten. Ich hatte eine entsprechende Meldung unter /var/log/messages bekommen.

Gruß

Ewald

**Comment by oriziena** [comment]
@FUEL4EP danke.

In der Tat, der Stick hatte sich am USB Port verabschiedet... Allerdings lief das komplette Setup ja monatelang problemlos... Daher bin ich jetzt irgendwie überrascht, dass es ein "Strom/Hardware" Thema sein sollte..

Aktuell hab ich auch nur einen 8GB USB 2.0 Stick aktiv...

**Comment by mdzio** [comment]
Bitte nochmal melden, falls der Fehler wieder auftaucht.
