### ISSUE TITLE
Abfrage über CCU - Stromzähler

### ISSUE THREAD

**Issue by Wolf6660** [mdzio/ccu-historian#214]
Hi,

ich habe mir das Skript von diesem Beitrag kopiert (https://homematic-forum.de/forum/viewtopic.php?f=38&t=43360)

Habe von Skripts nicht so viele Ahnung!!! Habe mal von oben nach unten über WriteLine durchgeschaut, ab wann nichts mehr ankommt. Bin bis zum foreach Befehl gekommen und da bekomme ich keine Rückmeldung mehr. Über diverse Suchen im Netzt konnte ich keine Lösung finden bzw. verstehe ich das nicht so wirklich. 

`

foreach(x, hist_string.Split(","))
{
  EndValue = x.ToFloat();
}`

Hier noch das komplette Skript

`string SysVar = "marcel_Tag"; !Systemvariable in die geschrieben werden soll

integer tage = 7; !Zeitraum in Tagen

string hist_ip = "192.168.0.3"; !IP Adresse ccu-Historien
string port = "8082"; ! Port ccu-Historien
string para_id = "802"; !ccu-historian Datenpunkt ID
string cuxd = "CUxD.CUX2801001:1"; !CUxD Exec Device

!#######################################
!Ab hier keine Änderungen mehr vornehmen
!#######################################

integer t = system.Date("%F %X").ToTime().ToInteger();
string endtime = t.ToString() + "000";
t = t - ( tage * 86400 );
string starttime = t.ToString() + "000";

string query = "http://" + hist_ip + ":" + port + "/query/jsonrpc.gy?j={%22id%22: 123, %22method%22: %22getTimeSeries%22,%22params%22: [" + para_id +
"," + starttime + "," + endtime + "]}";

dom.GetObject(cuxd + ".CMD_SETS").State("wget -q -O - '"#query#"'");
dom.GetObject(cuxd + ".CMD_QUERY_RET").State(1);
string hist_string = dom.GetObject(cuxd + ".CMD_RETS").State();

boolean error = hist_string.Contains("error");

if (error)
{
dom.GetObject(SysVar).State(-99); 
quit;
}

hist_string = hist_string.StrValueByIndex(":", 4).Replace('],"dataPoint"', '').Replace('[', '');

real StartValue = hist_string.StrValueByIndex(",", 0).ToFloat();

real EndValue = StartValue;

foreach(x, hist_string.Split(","))
{
  EndValue = x.ToFloat();
}

real delta = EndValue - StartValue;
dom.GetObject(SysVar).State(delta);
`

Vielleicht kann mir hier jemand behilflich sein? Danke

**Comment by mdzio** [comment]
Ich habe selber kein CUxD installiert und nicht so viel Zeit HM-Skript zu debuggen. Folgendes ist mir aber aufgefallen: Die Variable x wird nicht deklariert. Ich denke, dass folgende Zeile vor der foreach-Schleife noch eingefügt werden muss.
```
string x;
```
