### ISSUE TITLE
Unterstützung für CCU3 Authentication

### ISSUE THREAD

**Issue by x-jokay** [mdzio/ccu-historian#215]
Hellu

Evtl. wäre es eine gute Idee, wenn man die CCU3 Authentication unterstützen könnte.

![ccu3_authentication](https://user-images.githubusercontent.com/18613935/80128561-245ec280-8596-11ea-9bab-ce41b2d1df52.png)

Wird z.B. auch von [TinyMatic](https://www.tinymatic.de/) supported.

![tinymatic_authentication](https://user-images.githubusercontent.com/18613935/80128638-3fc9cd80-8596-11ea-9fd7-ddfa5766573d.png)

Wäre gut, wenn diese Werte auch mittels Konfigurationsoptionen gesetzt werden könnten, z.B.

```sh
devices.device1.username='my-ccu3-username'
devices.device1.password='my-ccu3-password'
```

**Comment by mdzio** [comment]
Die Authentifizierung sollte nun doch mal angegangen werden. Das Issue #183 bezieht ebenfalls darauf.
