### ISSUE TITLE
PostgreSQL Schnittstelle unter Node-RED nicht nutzbar

### ISSUE THREAD

**Issue by armin34320** [mdzio/ccu-historian#220]
CCU Historian is a great tool.

I have running it within Raspberrymatic on a Tinkerboard-S.

Everything works fine.

Now i wanted to get data out of CCU-Historian into my Redmatic installation on the same machine.

I tried different Node-RED contributions to access a PostgreSQL database:
  - node-red-contrib-re-postgres 0.2.2
  - postgrestor 0.0.2

Both fail to get a connection.
After some investigation i found:
  - Windows ODBC driver is only working with an old version (as stated in the documentation)
 - ODBC Managemant Studio is working and also getting data out of my CCU-Historian (so my configuration is ok)
 - Driver states a DBMS Version 8.2.23 emulated from the CCU-Historian (very old)

![grafik](https://user-images.githubusercontent.com/47714897/81048007-d1510d80-8ebb-11ea-9965-4e05f7b5428e.png)

I now suppose that the Node-RED interface does not accept this very old DBMS Version.
Same is for the old PgAdmin III tool under Windows. This tool also show the same errors on trying to connect to CCU-Historian PostgreSQL interface.

I use 
 - CCU-Historian V2.3.0 
 - Raspberrymatic 3.51.6.20200229 
 - RedMatic Version 5.5.3

Question is now:

- **is there an updated Version of the CCU-Historion PostgreSQL interface available?**

**Comment by mdzio** [comment]
The embedded database only emulates a PostgreSQL database. However, depending on the driver used, special SQL commands are sent to the database, which are not yet known to the emulation. 

The emulation is part of the embedded database H2Database and can not be modified or updated by me.

**Comment by armin34320** [comment]
Ok. Thanks very much for this info.
