### ISSUE TITLE
Add-On: trenddesigns.groovy wird nicht gefunden

### ISSUE THREAD

**Issue by bs0001** [mdzio/ccu-historian#221]
Hallo,
irgendwie bekomme ich es nicht hin.
Gerne möchte ich eine dunkle Variante bei der Darstellung verwenden:
Handbuch, Teil: Beispiel 3: Hintergrund- und Skalenfarben, Skalenbeschriftungen ändern, Legende entfernen
Habe das Coding im Hauptverzeichnis des CCUH in der Datei trenddesigns.groovy abgelegt.
Was genau ist noch alles zu tun, damit das neue Design für die unterschiedlichen Diagramme gezogen wird?
Wie muss genau der Eintrag in der ccu-historian.config sein?

Sorry, irgendwie stehe ich leider im Wald.

Gerne kannst Du diese Anfrage nach der Beantwortung gleich wieder schließen.

**Comment by mdzio** [comment]
Die Beispiele im Handbuch gelten für den Einsatz in der _ccu-historian.config_. Wenn sie in der Datei _trenddesigns.groovy_ abgelegt werden sollen, so ist das Präfix `webServer.` von den Optionen zu entfernen.

**Comment by bs0001** [comment]
,,, ich habe mir eine trenddesigns.groovy-Datei angelegt. Habe auch den Abschnitt aus dem threat #142 mit eingebaut. Den webserver.-Präfix habe ich entfernt. Datei hängt auch hier dran.
Die trenddesigns.groovy-Datei liegt im Unterverzeichnis webapp von ccu-historian.
Wie muss nun der korrekte Eintrag in der Datei ccu-historian.config aussehen, dass die Änderungen mit dem dunklen Skin funktionieren?

[trenddesigns.zip](https://github.com/mdzio/ccu-historian/files/4673874/trenddesigns.zip)

**Comment by mdzio** [comment]
Ich habe Deine `trenddesigns.groovy` erfolgreich getestet. Sie muss aber **nicht** im webapp-Verzeichnis abgelegt werden sondern im Installationsverzeichnis des CCU-Historians. Sie muss also neben der Datei `ccu-historian.jar` liegen. Dies kann bei Bedarf mit der Konfigurationsoption `script.baseDir` angepasst werden.

**Comment by bs0001** [comment]
Hallo Mathias,
Danke für die schnelle Rückmeldung.
Habe die trenddesigns.grrovy-Datei ins Hauptverzeichnis gelegt und auch den CCU-Historian neu gestartet. Die Darstellung ist immer noch im hellen Design wie vorher. Muss ich in der URL noch einen Parameter mitgeben, damit das neue Design in der groovy-Datei verwendet wird?
VG
Bernd

**Comment by mdzio** [comment]
Ich habe Deine trenddesigns.groovy unverändert in das Installationsverzeichnis kopiert. Und die Änderungen wurden angezeigt. Wenn Du das Log-Level auf FINEST erhöhst, erscheinen auch Log-Meldungen, die das Lesen oder Fehlen der Datei trenddesigns.groovy anzeigen.

**Comment by bs0001** [comment]
Hallo Mathias,
habe sogar das loglevel auf ALL gestellt. Es wird leider nichts geschrieben. Habe auch noch das Verzeichnis log angelegt mit kompletter Berechtigung zum Schreiben. 
Irgendwie scheint noch was nicht zu passen. Hast Du noch eine Idee?

**Comment by mdzio** [comment]
Hast Du die Option `logSystem.fileLevel=Level.FINEST` gesetzt?
Gib bitte den Inhalt Deiner ccu-historian.config bekannt. Auf welchem System betreibst Du den Historian? Auf RaspberryMatic beispielsweise liegt die Log-Date unter /var/log.

**Comment by bs0001** [comment]
Hallo Mathias,
Danke für die Rückmeldung. Nachdem ich Deine genannte Option eingebaut habe, werden auch Logs geschrieben. Ich hatte mich zuvor von dieser Option verleiten lassen: logSystem.binRpcLevel=Level.FINEST
Das hatte natürlich nicht zum gewünschten Ergebnis geführt.

Wenn ich nun die ccu-historian-0.log durchsuche nach trend oder groovy oder trenddesigns.groovy, dann wird nichts gefunden. Muss ich diese noch in der ccu-historian.config bekannt geben, dass diese verwendet werden soll?
Wie müsste dann die Option in der config-Datei lauten?

Das System läuft auf einem Raspi 3B+ und piVCCU3.

**Comment by mdzio** [comment]
Du verwendest also den Historian als Add-On. Dann steht in der `ccu-historian.config` die Option `base.scriptDir='/usr/local/addons/ccu-historian`. Ich bemerke aber gerade, dass diese Einstellung falsch ist. Sie sollte `base.scriptDir='/usr/local/addons/ccu-historian/ccu-historian` heißen. In der nächsten Version sollte dies behoben sein. Du kannst den Eintrag aber ersteinmal manuell abändern.

**Comment by bs0001** [comment]
Hallo Mathias,

ich habe den CCUH nicht als CCU3-Addon laufen. Die CCUH Diagramme werden über eine andere IP aufgerufen als die CCU3.

base.scriptDir='/opt/ccu-historian

Oder ist es nicht erforderlich und mein Problem liegt woanders?

**Comment by mdzio** [comment]
Dann ändere bitte den Konfigurationseintrag ab:
```
base.scriptDir='/opt/ccu-historian'
```
Und noch einmal testen.

**Comment by bs0001** [comment]
... Es hat scheinbar nun doch funktioniert. 
Das Ergebnis sieht zwar alles andere als schön aus aber ich kann es nun ja in der groovy Datei ändern. 
Bekommt man den gesamten Bereich dunkel, also auch den Kopfbereich? 

Demmnach sollte bei der zukünftigen Auslieferung und in der Anleitung der base.scriptDir Eintrag mit aufgenommen werden. 

Anbei der Screenshot vom aktuellen Ergebnis. 


![Screenshot_20200528-213708](https://user-images.githubusercontent.com/46260437/83185539-6fd33600-a12b-11ea-8c68-3957c24beef3.png)

**Comment by mdzio** [comment]
`trenddesigns.groovy` bestimmt nur das Aussehen der Diagrammfläche. Das Aussehen der umgebenden Web-Seite kann in der Datei `historian.css` abgeändert werden. Dazu muss man sich allerdings mit [CSS](https://de.wikipedia.org/wiki/Cascading_Style_Sheets) auskennen.

**Comment by bs0001** [comment]
Hab schon in der groovy Datei einiges rausgeworfen.
Sieht nun so aus:
![Screenshot_20200528-220027](https://user-images.githubusercontent.com/46260437/83187626-bbd3aa00-a12e-11ea-8b04-606722ecfe8c.png)

Die Beschriftung auf der Y-Achse gefällt mir noch nicht. Teilweise ist der Kontrast sehr schlecht. Dunkelblau und schwarz kommt nicht so gut. 
Muss ich mal schauen, wie man das noch in Griff bekommt. 

Die historian.css Datei ist die im Verzeichnis webapp/historian, oder?

**Comment by mdzio** [comment]
Ja.

**Comment by bs0001** [comment]
.... als Coding Grundlage kann ich mich an der Datei unter webapp/custom/h2-highcharts orientieren, oder?
Dann einfach die andere Datei mit den gewünschten CSS Einträgen ergänzen. 

Wird die CSS Datei bei einem Update überschrieben?

**Comment by bs0001** [comment]
... unter /webapp/custom/h2-highchart liegt ja bereits eine modifizierte css Datei.
Was muss ich tun, wenn ich mir eine eigene erstellen möchte und wie rufe ich diese auf?
Habe im Handbuch gesucht, aber nichts gefunden.

**Comment by mdzio** [comment]
Du kannst vorläufig Einträge zur Datei webapp/historian/historian.css hinzufügen. Bei einem Update wird diese Datei natürlich überschrieben.

**Comment by bs0001** [comment]
... kann ich auch eine custom css direkt aufrufen, z.B. wie erwähnt die h2-highchart?
Alternativ könnte ich mir ja auch eine eigene machen, ähnlich wie h2_highchart (z.B. als Kopiervorlage verwenden).

**Comment by mdzio** [comment]
Du kannst unter `webapp/custom` beliebige Dateien ablegen. Diese werden bei einem Update auch nicht überschrieben. Aber die Standard-Seiten vom CCU-Historian verwenden halt `webapp/historian/historian.css`.

**Comment by bs0001** [comment]
... Was hat das dann für einen Sinn, wenn ich die custom Daten nicht direkt aufrufen kann?

**Comment by mdzio** [comment]
Es ist bisher nicht vorgesehen, dass Teile der Standard-Web-Oberfläche unter `webapp/historian` angepasst werden können. Unter `webapp/custom` können komplett neue Web-Oberflächen abgelegt werden wie z.B. H2-Highchart. Für H2-Highchart wurden Dateien aus `webapp/historian` kopiert und geändert. Die Oberflächen sehen zwar gleich aus, sie haben aber keine gemeinsamen Dateien.

**Comment by bs0001** [comment]
... Danke für die Info. Habe ich mir schon gedacht. Wie aber kann ich die custom Variante aufrufen? Oder ist es die Lösung, sich eine custom Variante zu erstellen und dann die original Daten damit zu überschreiben?
Wäre doch gut, wenn man in der config Datei angeben könnte, welches Design verwendet werden soll oder sehe ich das falsch?

**Comment by mdzio** [comment]
Ich werde mal die in #227 beschriebene Möglichkeit einbauen. Bis dahin muss die Datei `webapp/historian/historian.css` geändert oder erweitert werden.

**Comment by bs0001** [comment]
... das wäre klasse, vielen Dank!!

**Comment by MichaelN0815** [comment]
Ich habe versucht das oben beschriebene nachzuvollziehen, inkl. anlegen einer trenddesigns.groovy in \usr\local\addons\ccu-historian\ccu-historian\ und Anpassung der ccu-historian.config  auf base.scriptDir='/usr/local/addons/ccu-historian/ccu-historian'

meine trenddesigns.groovy enthält:
`trendDesigns.logik=new TrendDesign(
	rangeAxes: [
		{
			// 1. Y-Skala 
			setRange(0,30)
		},
		{
			// 2. Y-Skala 
			setRange(0, 30)
		},
		{
			// 3. Y-Skala 
			setRange(0, 30)
		},
		{
			// 4. Y-Skala 
			setRange(-5, 20)
		},
		{
			// 5. Y-Skala 
			setRange(0, 3)
		}
	]
)`

Im LOG finde ich
`2020-08-25 18:23:27|FINER  |Web server: Generating trend
2020-08-25 18:23:27|FINER  |Executing script trenddesigns.groovy `

Es erscheint ein Diagramm, das sieht aber aus wie immer, ohne Anpassung der Skala. Was mache ich falsch?

**Comment by mdzio** [comment]
Ändere bitte mal Deine trenddesigns.groovy wie folgt ab (s.a. [Handbuch Abschnitt "Anpassung der Trend-Darstellung"](https://github.com/mdzio/ccu-historian/wiki#anpassung-der-trend-darstellung) ):
```
trendDesigns.logik.rangeAxes=[
  {
    // 1. Y-Skala 
    setRange(0,30)
  },
  {
    // 2. Y-Skala 
    setRange(0, 30)
  },
  {
    // 3. Y-Skala 
    setRange(0, 30)
  },
  {
    // 4. Y-Skala 
    setRange(-5, 20)
  },
  {
    // 5. Y-Skala 
    setRange(0, 3)
  }
]
```

Damit das Trend-Design verwendet wird, muss der URL-Parameter `t=logik` gesetzt sein. Zum Testen kann auch das Vorgabe-Trend-Design angepasst werden: `trendDesigns.logik.rangeAxes= ...`

**Comment by MichaelN0815** [comment]
Danke. Keine Ahnung, wo ich das her kopiert habe. Man muss eben alles kontrollieren. Und nach dem x-ten mal neu laden hat es dann auch funktioniert.

**Comment by MichaelN0815** [comment]
Aber so richtig bekomme ich meinen Wunsch und die Wirklichkeit nicht zur Deckung:

`
trendDesigns.logik.rangeAxes=[
		{
			// 1. Y-Skala Temp, auto
			
		},
		{
			// 2. Y-Skala Temp, auto
			
		},
		{
			// 3. Y-Skala Temp, auto
			
		},
		{
			// 4. Y-Skala Sonnenstatuts, 0-3
			setRange(0,3)
		},
		{
			// 5. Y-Skala Temp Auto
		
		},
		{
			// 6. Y-Skala Sonnenschein 0/1
			setRange(0,1)
		},
		{
			// 7. Y-Skala Sperre 0/1
			setRange(0,1)
		},
		{
			// 8. Y-Skala Level
			setRange(0,1)
		},
		{
			// 9. Y-Skala Status 0/1
			setRange(0,1)
		},
		{
			// 10. Y-Skala Status 0/1
			setRange(0,1)
		},
		{
			// 11. Y-Skala Status 0/1
			setRange(0,1)
		},
		{
			// 12. Y-Skala Sonnenwinkel, auto
			setRange(0,360)
		},
		{
			// 13. Y-Skala Sonnenwinke, auto
			setRange(-60,60)
		}
	]
`
Die 1. drei Kurven sollen automatisch skaliert sein: passt
Dann, im nächsten Block kommt eine Werteliste, die Werte von 0-3 annehmen kann. Die Skala zeigt auch 0-3 an, aber der rosa Strich liegt bei ~1,6 obwohl die Variable den Wert 0 hat.  Da passen also Skala und Datenpunkt nicht zusammen. Wozu die Skala mit +/-5E-9 hingehört???? So ganz habe ich noch nicht verstanden, wie ich einem Datenpunkt eine Skala zuordnen kann. Habe ihn der Doku dazu auch nichts gefunden. 

![Unbenannt](https://user-images.githubusercontent.com/68965895/91304044-2d140f00-e7a9-11ea-95a6-9cbbbfe79b7f.jpg)
