### ISSUE TITLE
Einfache Abfrage von Werten aus HM-Skripten auf der CCU

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-historian#224]
Es können zwar Einträge aus der Historian-Datenbank über die JSONRPC-Schnittstelle abgefragt werden, dies ist aber bisher nur recht aufwändig über ein HM-Skript zu realisieren: Die JSON-Anfrageparameter müssen in der URL kodiert und die JSON-Rückgabe muss per HM-Skript zerlegt werden.

Der Historian sollte eine zusätzliche URL anbieten, um Abfrageparameter einfacher zu übermitteln. Die Rückgabe sollte für eine einfachere Verarbeitung in HM-Skript formatiert werden.

Zusätzlich sollte der Historian bereits Berechnungen durchführen (z.B. Minimum, Maximum, Durchschnitt, ...).

**Comment by mdzio** [comment]
Die Dokumentation ist im [Handbuch](https://github.com/mdzio/ccu-historian/wiki#text-schnittstelle) zu finden.

**Comment by dagirgl** [comment]
Vielen Dank für die "Abkürzung"! Klasse Funktion! Eine Frage dazu noch. Wollte kein eigenes Issue dazu aufmachen. Hoffe, das ist okay...

Ich nutze folgende Abfrage (DP = Außentemperatur):

https://historian/query/text.gy?dp=209&b=z%2B6h&e=14h&ag=min&ag=max&ag=avg

Da wird ein Mittelwert (ag=avg) von *18.498786827380957* angezeigt. Der Graph zu dem Datenpunkt sieht so aus:

![trend_dp209](https://user-images.githubusercontent.com/16902192/87059005-11f53c00-c209-11ea-9975-ea75c53059ea.png)

Graph-URL:
https://historian/historian/trend.gy?gh1=1&dp1=209&g1=1&b=z%2B6h&e=14h&update-timerange=1

Da passt der errechnete Mittelwert nicht. Wenn ich mir alle Datenpunkte per CSV herunterlade und z.B. in Excel den Mittelwert bilde, bekomme ich einen tatsächlichen Mittelwert von *22,9885496* heraus.

Wie wird der Mittelwert hier gebildet? Muss ich bei den Zeitangaben anders herangehen?
