### ISSUE TITLE
text.gy fehlt in den Release Packets

### ISSUE THREAD

**Issue by BlackDuck888** [mdzio/ccu-historian#228]
Die für Web Text Schnittstelle notwendige Datei ist nicht Bestandteil der Release Packages.

**Comment by mdzio** [comment]
Ja, das Feature wurde zwar bereits implementiert. Die nächste Version vom CCU-Historian (V2.4.0) wurde aber noch nicht veröffentlicht. Diese kommt in den nächsten Tagen.
