### ISSUE TITLE
"Glätten" der Grafik .... möglich ? (ähnlich Grafana)

### ISSUE THREAD

**Issue by roe1974** [mdzio/ccu-historian#229]
Hallo zusammen

Gibt es eine Möglichkeit die Grafiken im Historian zu "glätten" ?
Hier Historian:
<img width="553" alt="Unbenannt" src="https://user-images.githubusercontent.com/30420568/85284141-f65f0700-b48e-11ea-9722-9f9f71555341.png">
Hier Grafana:
<img width="605" alt="Unbenannt2" src="https://user-images.githubusercontent.com/30420568/85284224-1db5d400-b48f-11ea-8216-de3d1118e458.png">

Vorteil von Historian wäre es baut wesentlich schneller die Grafik auf als Grafana ....

lg Richard

**Comment by mdzio** [comment]
Die Datenpunkte ACTUAL_HUMIDITY, ACTUAL_TEMPERATURE, AIR_PRESSURE, BRIGHTNESS, CURRENT, ENERGY_COUNTER, FREQUENCY, HUMIDITY, ILLUMINATION, LUX, POWER, RAIN_COUNTER, SUNSHINEDURATION, TEMPERATURE, VOLTAGE, WIND_SPEED sollten interpoliert dargestellt werden, wenn keine Delta-Kompression für diese aktiviert ist.

Ich habe da aber noch einen Fehler entdeckt, wodurch dies nicht geschieht.

(Database.groovy:699 sollte nochmal für alle Datenbanken ausgeführt werden. DataPointStorageUpader.groovy sollte das Continuous-Flag für neue Datenpunkte setzen.)

**Comment by roe1974** [comment]
Dh für Sysvar Datenpunkte (DC, CCU Temp, etc.) gibt es keine interpolierte Darstellung ?
lg Richard

**Comment by mdzio** [comment]
Zurzeit gibt es sie nicht. Das ist aber ein Punkt der noch berücksichtigt werden sollte.

**Comment by roe1974** [comment]
könnte man das nicht als flag bei der datenpunktkonfiguration machen ? ... also pro datenpunkt „interpolation“ ein/aus schalten ?
lg Richard

**Comment by mdzio** [comment]
Für die vorgesehenen Gerätedatenpunkte (z.B. TEMPERATURE) konnte ich keinen Fehler feststellen. Sie werden interpoliert dargestellt, wenn keine Delta-Kompression aktiviert ist. Bitte dies mal überprüfen!
Eine interpolierte Darstellung bei Delta-Komprimierten macht keinen Sinn. Die dargestellte Kurve weicht von der tatsächlichen Kurve gerade bei großen Deltas stark ab.
Eine Lösung wäre eine neue Komprimierungsart (s.a. #113).
Für Systemvariablen muss aber noch eine Möglichkeit zur Konfiguration angeboten werden.

**Comment by roe1974** [comment]
Ok ... überprüfe ich ... aber "swinging door" ist noch nicht implementiert ... oder ?

**Comment by roe1974** [comment]
OK, ohne Delta-Kompression funktoniert es .....
Eine Frage: Wie kann ich die "Legende" der Y-Achsen deakivieren ... ?

**Comment by roe1974** [comment]
Also wenn es jetzt noch eine Interpolierung bei SysVar Datenpunkte gäbe wäre es perfekt :-)

**Comment by mdzio** [comment]
Swinging-Door Kompression ist jetzt implementiert (s.a. #113) und erscheint mit der nächsten Release. Dadurch können analoge Messwerte komprimiert und interpoliert dargestellt werden.

**Comment by Baxxy13** [comment]
> Swinging-Door Kompression ist jetzt implementiert

Habe ich gleich ausprobiert und für gut befunden. Es wäre schön wenn sich die Methode auch auf OPERATING_VOLTAGE Datenpunkte anwenden ließe um diese ebenfalls interpoliert darzustellen.

**Comment by mdzio** [comment]
Systemvariablen vom Typ `Zahl` (bzw. `FLOAT`) werden ab der nächsten Version automatisch interpoliert dargestellt. Wie immer darf für eine interpolierte Darstellung keine Delta-Kompression aktiv sein.

`OPERATING_VOLTAGE` wird ebenfalls ab der nächsten Version interpoliert dargestelllt.
Workaround Skript für die aktuelle Version (4444 durch die gewünschte Historian-ID ersetzen):
```
def dp=database.getDataPoint(4444)
dp.continuous=true
dp.noSynchronization=true
database.updateDataPoint(dp)
println "Erledigt"
```

**Comment by roe1974** [comment]
Kann sein dass boolean (true/false) jetzt auch interpoliert dargestellt wird ?
<img width="273" alt="Unbenannt" src="https://user-images.githubusercontent.com/30420568/100213483-f87e3380-2f0e-11eb-8ea2-720015f0d78a.PNG">
Die blaue Linie ist ein Ventil-Zustand. Wurde um 6h00 eingeschaltet und um 8h00 ausgeschaltet.
Warum wird das jetzt so dargestellt ?

**Comment by mdzio** [comment]
Bitte mal unter _Werkzeuge_ → _Skriptumgebung_ folgendes Skript ausführen (28 durch die Historian-ID Deines BOOL-Wertes ersetzen):
```
println database.getDataPoint(28)
```

**Comment by roe1974** [comment]
Sorry !!! .. Kommando zurück ....
Ich hatte in der Zwischenzeit statt dem Schalter (on/off) eine Systemvariable genommen Typ Zahl die ich mit 0% und 100% befülle (Aus gründen der Y-Achse) .... die wird natürlich interpoliert .... 
SORRY Mein Fehler ;-)
