### ISSUE TITLE
Zusammenführen von zwei Datenbanken

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-historian#234]
Zeitreihen aus einer anderen CCU-Historian-Datenbank sollen einfach importiert werden können. Da die IDs der Datenpunkte beim Start einer neuen Datenbank neu vergeben werden, kann nicht einfach ein Backup erstellt und eingespielt werden,

**Comment by michaelkrause-SAP** [comment]
Ich würde hier gerne noch hinzufügen, dass eine 

1. Sicherung der **Konfiguartion** im Source-System und Restore im Target System und
2. Sicherung der **Daten im Source-System und Restore im Target System super wären
beste Grüße Michael

**Comment by mdzio** [comment]
Hinweis: Eine Migration zwischen den Systemen ist einfach. Die Datenbankdatei und Konfigurationsdatei kann einfach kopiert werden. Oder es kann auch ein Backup erstellt werden und auf dem Zielsystem wieder hergestellt werden.

**Comment by mdzio** [comment]
Dies kann nun mit der Export-/Import-Funktion über die Web-UI des CCU-Historians gelöst werden.
