### ISSUE TITLE
Massenkonfiguation inaktiver Datenpunkte (ähnlich versteckte Datenpunkte)

### ISSUE THREAD

**Issue by PaulMerk** [mdzio/ccu-historian#235]
zur Massenkonfiguration versteckter Datenpunkte gibt es ja bereits ein Skript im Wiki. 
Ich kann mir vorstellen, dass man vergleichsweise einfach dieses Skript umschreiben kann für inaktive Datenpunkte (dp.historyHidden --> ???)

**Comment by mdzio** [comment]
Ein Skript, das dies bewerkstelligt, ist nun bei den [Tipps & Tricks](https://github.com/mdzio/ccu-historian/wiki/Skripte#inaktive-datenpunkte-verstecken) zu finden.
