### ISSUE TITLE
In DATA_POINTS Feld custom wird nicht gespeichert über jsonrpc.gy

### ISSUE THREAD

**Issue by wakr70** [mdzio/ccu-historian#236]
Hallo Matthias,

habe mit der aktuellen Version ein Problem mit der jsonrpc.gy in Zeile 222: `custom.each { k, v ->` ist custom nicht definiert.

meiner Meinung nach fehlt vor dieser Zeile:
		`def custom=updateDp.attributes?.custom`

wenn ich das bei mir einbaue, funktioniert das speichern von Default-Werten in Custom wieder.

Danke und LG
Walter

**Comment by mdzio** [comment]
Tatsächlich hat sich dort ein Fehler eingeschlichen, obwohl auch Test-Code dafür vorhanden ist.
