### ISSUE TITLE
Mitloggen der Servicemeldungen/Alarmmeldungen (Anzahl) ... möglich ?

### ISSUE THREAD

**Issue by roe1974** [mdzio/ccu-historian#239]
Hallo
Könnte man die Anzahl der Servicemeldungen /Alarmmeldungen im CCU Historian sichtbar machen / mitloggen ?
lg Richard

**Comment by mdzio** [comment]
Um an diese Information zu kommen, müsste der CCU-Historian HM-Skripte auf der CCU ausführen. Da ist es besser, ein HM-Skript innerhalb eines CCU-Programms auszuführen, das eine Systemvariable mit der Anzahl beschreibt. Die Systemvariable wird dann vom CCU-Historian archiviert.

**Comment by roe1974** [comment]
aber wieso zeigt eine app wie @home (iOS) diese infos an ? ... siehe:
![image](https://user-images.githubusercontent.com/30420568/94856586-7bfc3680-0430-11eb-8046-8adbf39cbfa8.jpeg)
lg Richard

**Comment by mdzio** [comment]
Ich nehme an, dass die App ein HM-Skript über die *Remote Homematic-Script API* auf der CCU ausführt. Sicherlich könnte der CCU-Historian das gleiche machen und die Anzahl als Zeitreihe speichern. Diese Erweiterung wäre aber sehr aufwändig. Und das gleiche Skript könnte auch direkt in einem CCU-Programm ausgeführt werden, um eine Systemvariable zu beschreiben. Irgendwo im Forum müsste das Skript zu finden sein.
