### ISSUE TITLE
Fehlerhafte Anleitungen zur Benutzung des Recover-Werkzeugs

### ISSUE THREAD

**Issue by alexhass** [mdzio/ccu-historian#241]
Mein ccu historian sagt seine db wäre korrupt. Jetzt habe ich versucht diese zu reparieren, aber bekomme immer einen Fehler. Ich vermute beim addon fehlt eine library? Oder wo liegt diese?

Error: Could not find or load main class org.h2.tools.Recover

Ok, das ist das richtige Kommando. Überall fliegen falsche und halbe Anleitungen rum... echt übel.
```
/usr/local/etc/config/rc.d/ccu-historian stop
cd /usr/local/addons/ccu-historian/ccu-historian
/opt/java/bin/java -cp lib/h2-1.4.199.jar org.h2.tools.Recover -dir /media/usb0/ccu-historian -db history
```

**Comment by mdzio** [comment]
Bitte kurz angeben, wo die fehlerhaften Anleitungen zu finden sind. Dann kann ich sie vielleicht korrigieren.

**Comment by alexhass** [comment]
Also ich habe beim projkt nur eine Anleitung für Windows gefunden...

Dann ha ich mir super mühsehlig über Google den Rest der bröckchen aus homematic foren einträgen zusammengetragen... und da waren echt giele fehler drin. Also jeder pfad falsch usw. Neuere version vom recovery tool angegeben, usw.

Am ende nachdem das oben auch nicht funktioniert hat, hab ich aufgegeben und den db pfad umbenannt und mit einer neuen db gestartet. Ich fände es super, wenn jemand mal eine vollständige Anleitung für die ccu3 schreiben könnte, die einfach funktioniert.

Ich kenne mich mit h2 dbs wirklich null aus...

**Comment by alexhass** [comment]
Am Anfang des Cases war ich noch grün hinter den Ohren bei dem Thema... Die Anleitung im Projekt bezieht sich nicht auf eine CCU. Ich musste mir sehr mühsam die Pfade zusammensuchen, Wo java liegt war auch anders als in dem Wiki und nichts was in der Windows Anleitung drin stand war übertragbar auf die CCU oder hätte dort funktioniert. Hinzu kamen noch versionierte h2-1.4.199.jar. In der Anleitung stand ne andere Build nummer... ok... transfer usw. Ich hatte einfach keinen Spaß und am Ende hat der Restore nicht funktioniert und ich habe aufgegeben und einfach den Ordner auf dem USB Stick umbenannt und neu initialisieren lassen.

Das war alles ärgerlich, weil wirklich viele Daten verloren gegangen sind. Ich würde mir wünschen, dass es mal Beginner-Safe dokumentiert wird, wie es funktionieren sollte von Anfang bis Ende bezogen auf einen CCU z.b. mit Raspmatic

**Comment by mdzio** [comment]
Die komplette Dokumentation des CCU-Historians sollte von den verschiedenen Stellen in das [Wiki auf GitHub](https://github.com/mdzio/ccu-historian/wiki) verschoben werden.

Das Verschieben folgender Quellen ist geplant:
* [Tipps & Tricks zum CCU-Historian im HomeMatic-Forum](https://homematic-forum.de/forum/viewtopic.php?f=38&t=40872)
* [Noch vorhandene Anleitungen auf ccu-historian.de](https://ccu-historian.de/index.php?n=CCU-Historian.TippsAmpTricks)

**Comment by mdzio** [comment]
Mit den folgenden zwei Anleitungen sollte ein Recover nun besser dokumentiert sein:
* [Wiederherstellung einer defekten Datenbank](https://github.com/mdzio/ccu-historian/wiki/Tipps-&-Tricks#wiederherstellung-einer-defekten-datenbank)
* [Installation als Add-On auf einer CCU3 oder RaspberryMatic](https://github.com/mdzio/ccu-historian/wiki/CCU3-AddOn)

**Comment by Trapper12** [comment]
Hi,
ich habe den historian als Paket auf der Synology laufen DSM 6.
Hatte Stromausfall, das hat wohl die Datenbank beschädigt. 
Habe keine Anleitung zum Wiederherstellen auf einer Synology gefunden und gedacht, ich könnte das über eine win Version machen und dann die wiederhergestellte Datenbank in das Synology Verzeichnis kopieren. Klappt aber wohl nicht :-)

Habe die 3.02.bin.zip geladen und in ein Verzeichnis auf einem Windows Rechner entpackt. Habe dann den Ordner data hinzugefügt und hier die history.mv.db von der Synology reinkopiert. Habe dann gemäß Wiki recovered.
Der Befehl: java -cp lib\h2-2.1.212.jar org.h2.tools.Recover -dir data -db history
bringt folgendes Ergebnis 
![Bild1](https://user-images.githubusercontent.com/34746380/224299157-8eba1aa7-a4b1-4d61-b8ec-796b5d5deecf.png)

In dem Verzeichnis data wird die history.mv.txt angelegt, jedoch nicht die history.h2.sql. Alles Weitere funktioniert dann natürlich nicht mehr. 
Brauche Hilfe

Gruß
Klaus
