### ISSUE TITLE
Falsches Standardaggregat (first anstatt avg) bei der Text-Schnittstelle

### ISSUE THREAD

**Issue by duffy6** [mdzio/ccu-historian#243]
https://homematic-forum.de/forum/viewtopic.php?t=59588

**Comment by mdzio** [comment]
Bitte mal die komplette Zeitreihe von der Heizleistung als CSV exportieren und zur Verfügung stellen. Und dann noch einen Tag angeben, an dem die Berechnung nicht stimmt.

**Comment by duffy6** [comment]
siehe:
https://homematic-forum.de/forum/viewtopic.php?t=59588#p611915
