### ISSUE TITLE
CCU-Paket: CCU-Link unter Zentralen ist falsch

### ISSUE THREAD

**Issue by alexhass** [mdzio/ccu-historian#249]
Nach der installation von Historian  auf RaspMatic/CCU3 ist der Link unter Zentralen falsch und zeigt auf localhost 127.0.0.1. Das müsste aber auf den jeweils aktuellen Hostnamen der CCU zeigen.

**Comment by Geddespark** [comment]
> Nach der installation von Historian auf RaspMatic/CCU3 ist der Link unter Zentralen falsch und zeigt auf localhost 127.0.0.1. Das müsste aber auf den jeweils aktuellen Hostnamen der CCU zeigen.

Habe genau das gleiche Problem

**Comment by brgrvrm** [comment]
Ich habe v2.5.2 auf meiner CCU3 mit RaspberryMatic installiert und folgende Einträge in der ccu-historian.config.

webServer.historianAddress='192.168.8.103'
devices.device1.type=CCU3
devices.device1.address='127.0.0.1'
devices.historianAddress='127.0.0.1'

Damit läuft ccu-historian und zeichnet Daten auf schreibt diese in die Datenbank. Der Link im Menü Zentralen funktioniert allerdings nicht, weil er auf 127.0.0.1 verlinkt und nicht auf die CCU3 mit 192.168.8.103.

Ändere ich devices.device1.address='192.168.8.103' funktioniert der Link im Menü Zentralen, aber ccu-historian zeichnet keine Daten mehr auf.
