### ISSUE TITLE
Falmot Ventilpositionen raw value vs %

### ISSUE THREAD

**Issue by alexhass** [mdzio/ccu-historian#250]
Falmot liefert ventilpositionen in werten von 0.00 bis 1,00. 1= 100%.

Ccu historian zeigt in h2-highcharts seine skala bis 100% und die werte mit kleiner 1% an. Wie kann man die werte skallieren, damit es zu den % angaben passt? Also alle werte mit 100 multiplizieren?

**Comment by mdzio** [comment]
In der CCU ist als Einheit 100% und als Wertebereich 0 bis 1,0. 0,5 bedeutet also 50%. Werte kleiner als 1,0 sind also korrekt.

Wenn eine andere Darstellung gewünscht ist, kann eine Systemvariable mit dem Bereich 0 bis 100 und der Einheit % angelegt und per Skript (Ursprungswert * 100) gefüllt werden.

**Comment by alexhass** [comment]
Problem ist, dass die Grafik in Y Richtung 100% anzeigt und dann mit werten von 0-1 füllt. 

Das heisst Du hast immer eine Flatline in der man *nichts* erkennen kann.

Systemvariable ist ein Problem, weil es keinen passenden Auslöser gibt. Vieleicht verstehe ich aber einfach nur nicht woran ich es binden könnte ausser Zeit.

**Comment by mdzio** [comment]
Eventuell liegt noch ein Problem in der Erweiterung H2-Highcharts vor. Dann müsste aber ein Issue [dort](https://github.com/wakr70/CCU-Historian-HC) erstellt werden. @wakr70

**Comment by wakr70** [comment]
Hallo alexhass,
einfach auf die Linie clicken und bei Faktor 100 eingeben, danach via Default Button abspeichern, dann sollte es funktionieren.
LG wak
