### ISSUE TITLE
Link erzeugen > Menü erstellen?

### ISSUE THREAD

**Issue by alexhass** [mdzio/ccu-historian#251]
Wie erzeugt man links, die sich irgendwo verewigen? Also entweder im ccu historian menü oder direkt in der ccu? Will mir zuindest nicht überall bookmarks im browser erstellen... sowas geht ja auch mal verloren.

Vieleicht verstehe ich es aber einfach nur nicht, wie es geht?

**Comment by mdzio** [comment]
Verweise können zum Menü _Extras_ hinzugefügt werden (s.a. [Handbuch Eigene Verweise auf Web-Seiten](https://github.com/mdzio/ccu-historian/wiki#eigene-verweise-auf-web-seiten)). Dies ist durch das Editieren der `ccu-historian.config` möglich. Eventuell wird dies später über die Web-Oberfläche möglich sein.

**Comment by alexhass** [comment]
Warum nur „eventuell“? 

Mir kommt das vor wie eines der wichtigsten basis features, die dem Historian momentan fehlen. Oder anders gesagt ein heftiger usability fail und das wo der Rest der Oberfläche nun wirklich sehr gefällig ist...
