### ISSUE TITLE
Uhrzeit der automatischen Backups der DB konfigurierbar machen 

### ISSUE THREAD

**Issue by Baxxy13** [mdzio/ccu-historian#253]
Ich nutze momentan die automatische Backupfunktion mittels 
`database.backup='/media/usb0/CCU-Historian-DB-Backup/%Y-KW%W-TestCCU'`

Das klappt auch wunderbar, das Backup wird jeden Sonntag morgen um 00:00:xx angelegt. 

Schön wäre es wenn man die Uhrzeit konfigurieren könnte, also z.B. Sonntag morgen um 00:10 Uhr

**Comment by mdzio** [comment]
Über die geplanten Aufgaben (s.a. #358) kann nun ein Backup zu beliebigen Zeitpunkten ausgeführt werden.

Beispiel für ein Backup um 02:30 Uhr :
```
database.tasks.backup.enable=true
database.tasks.backup.cron="0 30 2 * * ?"
database.tasks.backup.script={
	def timestamp=new Date().format("YYYYMMddHHmmss")
	def fileName="db-backup_${timestamp}.zip"
	database.createBackup(fileName)
}
```
