### ISSUE TITLE
Werte unter Cursor-Position bei Hover über Diagram-Kurve anzeigen

### ISSUE THREAD

**Issue by Wookbert** [mdzio/ccu-historian#254]
Es wäre schön, wenn man mit der Maus über Kurven fahren könnte, und dabei on-the-fly den Messwert samt Datum und Uhrzeit angezeigt bekäme, so wie man das bei vielen Aktien-Plattformen kennt:

![image](https://user-images.githubusercontent.com/3104762/98387607-ea48a000-2051-11eb-82bf-f241c4682d13.png)

Durch Klicken an der Stelle einfrieren, durch erneutes Klicken wieder aufheben und zum Hover-Mode zurückkehren. Das für jede Kurvengruppe unabhängig voneinander, und alternativ (per Checkbox zuschaltbar) synchron, wenn man z.B. der Werte zu einem ganz bestimmten Zeitpunkt, von mehreren einzeln, übereinander dargestellter Temperaturkurven, miteinander vergleichen will:

![image](https://user-images.githubusercontent.com/3104762/98388074-8d011e80-2052-11eb-8551-cfd64e484f5c.png)

**Comment by mdzio** [comment]
Der CCU-Historian besitzt zwei mögliche Trend-Darstellungen: Einmal die Standard-Trend-Darstellung, die als PNG-Bild vom CCU-Historian erstellt und an den Web-Browser geschickt wird. Technisch ist eine Lineal-Funktionalität hier nicht möglich.

Unter _Extras_ → _H2-HighChart_ ist aber eine zweite Trend-Darstellung zu finden, die bereits diese Funktionalität mitbringt.
