### ISSUE TITLE
Automatische Konfiguration zum Speicherplatzsparen

### ISSUE THREAD

**Issue by mikes222** [mdzio/ccu-historian#255]
Meine historian-Datenbank ist mittlerweile 2GB groß. Laut dieser Story hier:
https://homematic-forum.de/forum/viewtopic.php?t=45169
ist das noch nicht besorgniserregend. Trotzdem wäre es gut, wenn die vorgeschlagene Konfiguration für die Deltakompression 

    0,5 für Ein/Aus-Signale (z.B. WORKING, UNREACH, STICKY_UNREACH, MOTION, INSTALL_TEST, CONFIG_PENDING, LOWBAT, SABOTAGE)
    0,5 für ganzzahlige Datenpunkte (z.B. ERROR, ERROR_CODE, BRIGHTNESS, HUMIDITY, STATE, ARMSTATE, SUNSHINE_DURATION, DIRECTION)
    0,01 für Fließkommadatenpunkte (z.B. VALUE, RAIN_COUNTER, ACTUAL_TEMPERATURE, LEVEL, TEMPERATUR, ENERGY_COUNTER, POWER, CURRENT, WIND_SPEED, ILLUMINATION, FREQUENCY, VOLTAGE, LUX, OPERATING_VOLTAGE)
    keine Delta-Kompression für Tastendrücke (z.B. PRESS_SHORT, PRESS_LONG)

    Mit der Kommandozeilenoptionen -recalc und danach -compact (s.a. Handbuch Abschnitt 5.1) sollte einmal im Jahr die Datenbank optimiert werden. 

per Menüpunkt auf alle Werte angewendet werden kann, die noch keine Kompression haben. Sonst müsste ich jetzt alle Werte manuell filtern und überall die Deltakompression einstellen wo dies noch nicht geschehen ist. Bei mittlerweile 140 Geräten ist das eine Menge Aufwand. Und wenn neue Geräte dazukommen, müsste ich von Zeit zu Zeit wieder filtern und die neuen Werte umkonfigurieren. 

Also technischer formuliert:
- ein Menüpunkt "Kompression konfigurieren"
- ein Dialogfeld, in dem man auswählen kann, welche Kompression man haben möchte (zB. die 0.1 für Fließkommadatenpunkte mag vielleicht nicht jeder oder nicht jeder mit 0.1) und auf welche Datenpunkte sie angewendet werden soll
- Umstellung aller betreffenden Datenpunkte, die noch keinerlei Kompression eingestellt haben
- recalc und compact der Datenbank

**Comment by mdzio** [comment]
Eine Massenkonfiguration der Delta- und Swinging-Door-Kompression ist bereits jetzt schon möglich. Dies erfolgt über _Werkzeuge_ → _Skriptumgebung_ mit [diesem Skript](https://github.com/mdzio/ccu-historian/wiki/Skripte#massenkonfiguration-der-delta--und-swinging-door-kompression). Dies kann jeder Anwender auch individuell anpassen. Eine Konfigurationsmöglichkeit über die Web-Oberfläche des CCU-Historians würde nie alle Anwendungsfälle abdecken.

Über die Web-Oberfläche kann bisher kein -compact oder -recalc ausgelöst werden. Dies wird aber bereits im Eintrag #159 behandelt.

Ich denke, dass damit alle Punkte erledigt sind oder bereits in anderen Einträgen weiter verfolgt werden. Bei Bedarf kann dieser Eintrag wieder geöffnet werden.
