### ISSUE TITLE
Möglichkeit zum erfassen der Metadaten für Inaktive Datenpunkte

### ISSUE THREAD

**Issue by Baxxy13** [mdzio/ccu-historian#256]
Ich nutze das Historian Add-On auch auf meinem Test / Spielesystem.
Hier werden sehr häufig Geräte An/Abgelernt und SysVars angelegt / umbenannt / gelöscht.
Damit der Historian nicht "zugemüllt" wird sind die Parameter
_historian.defaultDisabled=true
historian.defaultHidden=true_
gesetzt.
 
Dadurch werden zwar alle (neuen) Datenpunkte "aufgenommen" und sind in der Datenpunktkonfiguration sichtbar, aber es werden keine Metadaten dazu geschrieben. Am wichtigsten wäre mir hier der Name.
Bei den Gerätedatenpunkten geht das noch in Ordnung (kann man anhand der SN zuordnen) aber bei SysVars ist das sehr mühsam da diese als Name / Adresse nur ihre ISE_ID aus der Zentrale bekommen welche wiederum nicht so einfach herauszufinden ist.

Schaut man dem Historian mit einem hohen LogLevel auf der Konsole zu sieht man aber das die Metadaten (zumindest der SysVars) irgendwie erfasst werden und z.B. die Namen im Klartext sichtbar sind.

**Gesucht wird nun eine Möglichkeit die Metadaten zu erfassen / zu aktualisieren ohne den jeweiligen Datenpunkt aktiv setzen zu müssen.**

- idealerweise gäbe es eine zusätzliche Option in der Konfig die das ermöglicht

-  oder eine Scriptlösung die manuell über die Scriptumgebung ausgeführt wird und dann alle Metadaten aktualisiert / ausfüllt 

Grüße, Baxxy

**Comment by MichaelN0815** [comment]
Ich sehe hier auch Verbesserungspotential. Wäre schön, wenn das umgesetzt werden kann.

**Comment by mdzio** [comment]
Eine Idee ist, auch wenn `historian.defaultDisabled=true` gesetzt ist, die Metadaten **einmalig** auszulesen. Änderungen an den Metadaten werden dann aber nicht nachverfolgt (z.B. Umbenennungen).

**Comment by mdzio** [comment]
Es wurde wie oben beschrieben umgesetzt: Auch wenn `historian.defaultDisabled=true` gesetzt ist, werden die Metadaten **einmalig** ausgelesen.
