### ISSUE TITLE
CCU-Historian nach Energiesparplan betreiben

### ISSUE THREAD

**Issue by 104mapo** [mdzio/ccu-historian#257]
Ich nutze CCU-Historian für Synology und einer CCU2. Leider gehen die Festplatten und das NAS durch CCU-Historian nicht in Standby. Der Stromverbrauch ist daher nicht ganz unerheblich. Ich würde gern das gesamte NAS Nachts ausschalten um Energie zu sparen. Gibt es eine Möglichkeit CCU-historian beizubringen, dass die Daten auf der CCU zwischenspeichert werden und nach dem wiedereinschalten des NAS abgeholt werden? Ich habe bereits ein SD_Karte in der CCU und logge über Cuxd. Die Auswertung ist dort aber eher schlecht und alles hängt auf der SD-Karte.
Danke, Martin

**Comment by mdzio** [comment]
Das könnte nur realisiert werden, wenn ein Teil vom CCU-Historian auf der CCU läuft. Das ist aber für den CCU-Historian nicht geplant. 

Langfristig soll dies aber im [CCU-Jack](https://github.com/mdzio/ccu-jack) umgesetzt werden. Für die nötige Anbindung existiert bereits der Eintrag #191 .
