### ISSUE TITLE
Min/max mit Angabe Datum und/oder Uhrzeit

### ISSUE THREAD

**Issue by duffy6** [mdzio/ccu-historian#259]
Mittels text.gy ist es ja seit kurzem möglich sich min, Max, Differenz und Durchschnitt anzeigen zulassen.
Wäre es möglich ein weiteres Aggregat (ag) zu schaffen, das noch zusätzlich die Uhrzeit/Datum ausgibt, WANN das Min/Max aufgetreten ist?

Bsp:

....url..../text.gy......&ag=min_when

**Comment by mdzio** [comment]
[Dokumentation ist im Handbuch zu finden.](https://github.com/mdzio/ccu-historian/wiki#text-schnittstelle)
