### ISSUE TITLE
Selektion für gleiche Zeitbereiche der Vergangenheitswerte

### ISSUE THREAD

**Issue by bs0001** [mdzio/ccu-historian#260]
Hallo,
ist es möglich über eine entsprechende Auswahl im Feld Zeitbereich zu sagen, dass mir bspw. die letzten 5 Jahre für Monat November angezeigt werden?
Es gibt ja Datenpunkte, bei denen macht ein Vergleich mit entsprechenden Vorjahreszeiträumen Sinn.
Wäre prima, wenn sowas gehen würde.
VG
Bernd

**Comment by mdzio** [comment]
Zurzeit ist so etwas nicht möglich. Die Idee dazu existiert bereits im Eintrag #13.
