### ISSUE TITLE
CCU-Historian kann auf der neuesten Synology DSM 7.0 nicht installiert werden

### ISSUE THREAD

**Issue by elac99** [mdzio/ccu-historian#261]
Bei der Installation des spk Paketes kommt die Meldung: "Ungültiges Dateiformat. Bitte wenden Sie sich an den Entwickler des Pakets."

**Comment by mdzio** [comment]
Ich besitze selber kein Synology-NAS. Das Problem müsste mal von jemanden mit einem Synology-NAS untersucht werden. Falls es das NAS unterstützt, kann auch das Docker-Image vom CCU-Historian verwendet werden (siehe [xjokay/ccu-historian](https://hub.docker.com/r/xjokay/ccu-historian)).

**Comment by elac99** [comment]
Ich habe das Docker Image installiert. Nun funktioniert auch CCU-Historian mit der neuesten Version der DSM 7.0 auf Synology.
Danke für den Tipp.

**Comment by duffy6** [comment]
Wobei natürlich eine Unterstützung des SPK Pakets geeigneter für Endkunden wäre.

Viele Synology Boxen unterstützen zudem gar keine Docker-Images!!!

**Comment by Faustilein** [comment]
DSM 7.0 erlaubt keine Pakete mehr die mit Root-Rechten ausgeführt oder installiert werden. Ich bin auch auf Docker umgestiegen.

**Comment by mdzio** [comment]
Ich habe selbst kein Synology-NAS, und es gibt zurzeit kein Maintainer des Synology-Pakets. Wann und ob das Problem behoben wird, ist zurzeit nicht absehbar.

**Comment by hotroot** [comment]
Moin zusammen,

nachdem ich vorgestern mein Synology NAS etwas überstützt auf DSM 7 aktualisiert hatte, musste ich auch feststellen, dass CCU Historian nicht mehr funktionierte. Heute habe ich mich mal hingesetzt und das SPK auseinandergenommen und für DSM 7 angepasst. Wirklich viel musste ich gar nicht anpassen. Das diff hänge ich hier mal an: [ccu-historian-2.6.0.spk.patch.txt](https://github.com/mdzio/ccu-historian/files/6642956/ccu-historian-2.6.0.spk.patch.txt)

Vorgehen:

1. ccu-historian-2.6.0.spk entpacken
2. Patch anwenden
3. SPK neu erzeugen und installieren.

Die Installation läuft soweit durch CCU Historian wird auch gestartet, wirft allerdings Fehler. Da ich nicht wirklich Ahnung von Java habe bin ich hier mit meinem Latein am Ende:

```
2021-06-12 23:05:23|INFO   |CCU-Historian V2.6.0
2021-06-12 23:05:23|INFO   |(C)MDZ (info@ccu-historian.de)
2021-06-12 23:05:25|INFO   |Starting base services
2021-06-12 23:05:26|INFO   |Connecting to database
2021-06-12 23:06:50|INFO   |Starting database web server
2021-06-12 23:06:50|INFO   |Setting up device 1
2021-06-12 23:06:50|INFO   |Creating HM script client for http://homematic-ccu2.fritz.box:8181/tclrega.exe
2021-06-12 23:06:50|INFO   |Setting up plug-in 1
2021-06-12 23:06:51|INFO   |Configured following interfaces: BidCos-RF, HmIP-RF, SysVar, CUxD
2021-06-12 23:06:51|INFO   |Starting interfaces
2021-06-12 23:06:51|INFO   |Starting BIN-RPC server on port 2099
2021-06-12 23:06:51|INFO   |Starting XML-RPC server on port 2098
2021-06-12 23:06:51|INFO   |Connecting to homematic-ccu2.fritz.box:8701
2021-06-12 23:06:51|INFO   |Starting historian
2021-06-12 23:06:51|INFO   |Starting web server
2021-06-12 23:06:52|INFO   |Web server port: 8080
2021-06-12 23:06:54|SEVERE |Exception: No signature of method: java.lang.Object.clone() is applicable for argument types: () values: []
Possible solutions: collect(), collect(groovy.lang.Closure), collect(java.util.Collection, groovy.lang.Closure), any(), find(), print(java.io.PrintWriter)
2021-06-12 23:06:54|SEVERE |Detail: groovy.lang.MissingMethodException: No signature of method: java.lang.Object.clone() is applicable for argument types: () values: []
Possible solutions: collect(), collect(groovy.lang.Closure), collect(java.util.Collection, groovy.lang.Closure), any(), find(), print(java.io.PrintWriter)
	at mdz.hc.DataPoint.clone(DataPoint.groovy)
	at mdz.ccuhistorian.Historian$_update_closure9.doCall(Historian.groovy:155)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at mdz.ccuhistorian.Historian.update(Historian.groovy:155)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at mdz.ccuhistorian.Historian$_updateDataPointMeta_closure3$_closure12.doCall(Historian.groovy:114)
	at mdz.ccuhistorian.Historian$_updateDataPointMeta_closure3$_closure12.doCall(Historian.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.ccuhistorian.Historian$_updateDataPointMeta_closure3.doCall(Historian.groovy:110)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at mdz.ccuhistorian.Historian.updateDataPointMeta(Historian.groovy:109)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at mdz.ccuhistorian.Historian$_run_closure2.doCall(Historian.groovy:103)
	at mdz.ccuhistorian.Historian$_run_closure2.doCall(Historian.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.ccuhistorian.Historian.run(Historian.groovy:102)
```

Der Web Server wird, wie man im Log sehen kann, gestartet und ist auch erreichbar. Die Datenpunktliste wird auch geladen aber bei der Anzeige der Trenddiagramme erscheint folgende Fehlermeldung:
```
Fehler: No signature of method: mdz.ccuhistorian.webapp.TrendParameters.clone() is applicable for argument types: () values: [] Possible solutions: clone(), collect(), collect(groovy.lang.Closure), collect(java.util.Collection, groovy.lang.Closure), any(), find() 
```

Der Fehler im Log wiederholt sich andauernd, vermutlich immer dann wenn ein neuer Wert gespeichert werden soll, denn der CSV-Export funktioniert zwar noch, enthält allerdings keine neuen Daten.

Folgende Java-Version kommt bei mir zum Einsatz:
```
# java --version
openjdk 16.0.1 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-24)
OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
```

Installiert habe ich sie mittels https://github.com/rednoah/java-installer

Vielleicht hilft es ja, ein funktionierendes DSM 7 Paket zu erzeugen.

**Comment by mdzio** [comment]
Danke für den Patch und das Testen.

Ich werde mir die Fehlermeldungen mal anschauen.

**Comment by mdzio** [comment]
Die Fehlermeldungen hängen wohl mit der neuen Java Version 16 zusammen. Ich habe dazu einen separaten Eintrag erstellt (siehe #291).

**Comment by mdzio** [comment]
Kannst Du sagen, ob die Änderungen dann noch mit DSM 6.0 funktionieren?

Ansonsten müssten zwei separate Pakete für 6 und 7 zur Verfügung gestellt werden.

**Comment by hotroot** [comment]
Da man die os_min_ver auf (mindestens) 7.0-40000 würde ich sagen nein. Auch von dem Java-Installer gibt es ein dediziertes DSM 7 Paket.

**Comment by mdzio** [comment]
So, ich habe den Patch eingebaut, sodass automatisch auch eine Distribution für DSM 7 gebaut wird.

Hier ist ein erstes Ergebnis. Bitte mal testen:
[ccu-historian-dsm7-2.7.0-beta.2.spk.zip](https://github.com/mdzio/ccu-historian/files/6644585/ccu-historian-dsm7-2.7.0-beta.2.spk.zip)

**Comment by hotroot** [comment]
funktioniert fast. die Versionsnummer schmeckt dem DSM nicht:
```
2021-06-13T22:59:14+02:00 DiskStation synoscgi_SYNO.Core.Package.Installation_1_upload[4899]: pkgverify.cpp:245 Failed to load pkg info, version=[2.7.0-beta.2], correct-format=[^\d+(\.\d+){0,5}(-\d+)?$]
```

Nachdem ich die INFO-Datei manuell geändert habe (der Einfachheit halber in 2.7.0-2) lief die Installation durch und der Historian wurde gestartet. Neue Werte kommen auch an, allerdings funktioniert die Trend-Anzeige noch nicht. Im CSV-Export sind jedoch die neuen Datenpunkte enthalten. Die Details dazu packe ich der übersicht halber in #291

**Comment by mdzio** [comment]
So, nächster Versuch:
[ccu-historian-dsm7-2.7.0-3.zip](https://github.com/mdzio/ccu-historian/files/6650966/ccu-historian-dsm7-2.7.0-3.zip)

**Comment by hotroot** [comment]
Also irgendwas scheint DSM 7 an dem von dir erzeugten spk zu stören. Wenn ich das spk hochlade, scheint das INFO file nicht entpackt zu werden:
```
2021-06-14T23:04:22+02:00 DiskStation synoscgi_SYNO.Core.Package.Installation_1_upload[9687]: pkgtool.cpp:1299 Failed to extract package INFO, from=[/volume1/@tmp/upload_tmp.96870] to=[/volume1/@tmp/ZXbd2H]
2021-06-14T23:04:22+02:00 DiskStation synoscgi_SYNO.Core.Package.Installation_1_upload[9687]: pkgtool.cpp:1327 Failed to query info
```
Wenn ich das spk entpacke, ist die Dateireihenfolge wie folgt:
```
# tar xvf ../ccu-historian-dsm7-2.7.0-3.spk 
package.tgz
LICENSE
INFO
WIZARD_UIFILES/
conf/
scripts/
PACKAGE_ICON.PNG
PACKAGE_ICON_256.PNG
WIZARD_UIFILES/uninstall_uifile
WIZARD_UIFILES/uninstall_uifile_ger
WIZARD_UIFILES/upgrade_uifile
WIZARD_UIFILES/upgrade_uifile_ger
conf/privilege
WIZARD_UIFILES/install_uifile.sh
WIZARD_UIFILES/install_uifile_ger.sh
scripts/postinst
scripts/postuninst
scripts/postupgrade
scripts/preinst
scripts/preuninst
scripts/preupgrade
scripts/start-stop-status
```
Ich nutze zum packen folgendes Kommando (Quellen liegen im Unterverzeichnis ccu-historian-beta):
```
# tar -cvf ccu-historian-beta.spk -C ccu-historian-beta $(ls ccu-historian-beta)
conf/
conf/privilege
INFO
LICENSE
PACKAGE_ICON_256.PNG
PACKAGE_ICON.PNG
package.tgz
scripts/
scripts/start-stop-status
scripts/postupgrade
scripts/postuninst
scripts/preuninst
scripts/preinst
scripts/postinst
scripts/preupgrade
WIZARD_UIFILES/
WIZARD_UIFILES/uninstall_uifile_ger
WIZARD_UIFILES/install_uifile_ger.sh
WIZARD_UIFILES/upgrade_uifile_ger
WIZARD_UIFILES/upgrade_uifile
WIZARD_UIFILES/uninstall_uifile
WIZARD_UIFILES/install_uifile.sh
```
Das resultierende spk kann ich dann problemlos installieren.

Die Trendanzeige funktioniert leider immer noch nicht. Auf der CCU Historian Webseite erscheint kein Fehler mehr, sondern der Graph wird einfach nicht angezeigt. Im Log gibt es allerdings Fehler: 
[ccu-historian.log](https://github.com/mdzio/ccu-historian/files/6651370/ccu-historian.log)

**Comment by mdzio** [comment]
Die TAR-Erstellung schaue ich mir nochmal an.

Der Fehler bei der Trend-Erstellung hängt wahrscheinlich mit der eingesetzten Java-Version zusammen (siehe auch #271 #185). Für die Trend-Generierung werden Schriftarten benötigt, die nicht in allen Java-Paketen enthalten sind. (Bei diesen Paketen steht meistens "headless" dabei).

**Comment by hotroot** [comment]
Volltreffer, es waren die Fonts. Mit etwas gebastel habe ich es hinbekommen. Folgende Schritte sind nötig:
1. Offizielles JRE herunterladen und entpacken (https://java.com/de/download/). Die Architektur sollte egal sein
2. Aus dem Unterverzeichnis lib das Verzeichnis fonts und alle Dateien die mit fontconfig auf das NAS nach /var/packages/java-installer/target/lib kopieren. 
3. Berechtigungen der kopierten Dateien anpassen
   - sudo chown -R Java:Java /var/packages/java-installer/target/lib/fonts
   - sudo chown Java:Java /var/packages/java-installer/target/lib/fontconfig.*
   - sudo chmod 755 /var/packages/java-installer/target/lib/fonts
   - sudo chmod 644 /var/packages/java-installer/target/lib/fonts/*
   - sudo chmod 644 /var/packages/java-installer/target/lib/fontconfig.*

Der Nachteil dürfte sein, dass diese Schritte bei jedem Java-Update nötig sein dürften. Ist aber definitiv kein Historian-Problem mehr. Oder könntest du (technisch und Lizenzrechtlich) die benötigten Fonts direkt im Historian mitliefern?

**Comment by mdzio** [comment]
Gibt es vielleicht noch andere Java-Pakete, die getestet werden könnten?

Die Erstellung der TAR-Datei erfolgt durch das Build-Tool Apache Ant. Normalerweise sind sie mit jedem TAR-Entpacker kompatibel. 

Ich sehe gerade, dass es ein [Ant-Task für SPKs](https://github.com/rednoah/ant-spk) gibt. Ich werde das mal testen.

**Comment by mdzio** [comment]
Ich habe noch den [Unofficial Java Installer](https://github.com/rednoah/java-installer) für Synology gefunden.

**Comment by hotroot** [comment]
> Ich habe noch den [Unofficial Java Installer](https://github.com/rednoah/java-installer) für Synology gefunden.

Das ist genau der Java-Installer den ich verwende (siehe oben), da Synology mit DSM 7 die Java-Unterstützung gestrichen hat. Dieser installiert das OpenJDK von https://jdk.java.net/. In diesem JDK fehlen die Fonts. 

Zum TAR/SPK-Archiv. Ich habe mir den Befehl zum erstellen des SPKs aus den offizielle Synlogy-Build-Tools rausgefummelt. Ich habe das Gefühl, dass die Reihenfolge mit der die Dateien ins TAR-Archiv geschrieben werden wichtig ist. Wenn ich nämlich einfach nur mit `tar -cvf ccu-historian-beta.spk *` im Verzeichnis mit dem Paketinhalt mache, dann funktioniert das SPK auch nicht.

**Comment by mdzio** [comment]
Jetzt ist das SPK mit demselben Build-Tool wie der Java-Installer erstellt worden: [ccu-historian-2.7.0-4-noarch.zip](https://github.com/mdzio/ccu-historian/files/6672491/ccu-historian-2.7.0-4-noarch.zip)

Bezüglich des Java-Installers ohne Fonts kann vielleicht auch ein Issue dort erstellt werden. Vielleicht wird das Problem angegangen.

**Comment by hotroot** [comment]
Das SPK funktioniert Es ließ sich gerade problemlos installieren. Ich werde morgen mal ein Issue beim java-installer aufmachen. Vielleicht bekommen wir da ja eine Lösung.

**Comment by drsamasrd** [comment]
> 
> 
> Volltreffer, es waren die Fonts. Mit etwas gebastel habe ich es hinbekommen. Folgende Schritte sind nötig:
> 
>     1. Offizielles JRE herunterladen und entpacken (https://java.com/de/download/). Die Architektur sollte egal sein
> 
>     2. Aus dem Unterverzeichnis lib das Verzeichnis fonts und alle Dateien die mit fontconfig auf das NAS nach /var/packages/java-installer/target/lib kopieren.
> 
>     3. Berechtigungen der kopierten Dateien anpassen
>        
>        * sudo chown -R Java:Java /var/packages/java-installer/target/lib/fonts
>        * sudo chown Java:Java /var/packages/java-installer/target/lib/fontconfig.*
>        * sudo chmod 755 /var/packages/java-installer/target/lib/fonts
>        * sudo chmod 644 /var/packages/java-installer/target/lib/fonts/*
>        * sudo chmod 644 /var/packages/java-installer/target/lib/fontconfig.*
> 
> 
> Der Nachteil dürfte sein, dass diese Schritte bei jedem Java-Update nötig sein dürften. Ist aber definitiv kein Historian-Problem mehr. Oder könntest du (technisch und Lizenzrechtlich) die benötigten Fonts direkt im Historian mitliefern?

Hallo Hotroot,

ich habe deine Befehle wie beschrieben umgesetzt bekomme aber immer noch die Fehlermeldung bzgl. der physisch nicht vorhanden Schriften. Muss ich bei der Befehlszeile den Pfad auf die Schiften noch zusätzlich explizit setzen; irgendetwas fehlt noch.

**Comment by Tibinobo** [comment]
Hallo,
so, erstmal angemeldet um mich mal zu bedanken... Vorrangig bei Mathias, ohne den es den Historian gar nicht geben würde. Dann bei Hotroot, der es möglich gemacht hat, dass die Trendgrafiken unter DSM 7.0 angezeigt werden und letzlich auch bei MKaiser96, der endlich den entscheidenden Hinweis lieferte, denn Bilder sagen mehr als Worte... die fontconfigs vom unteren Bild hatte ich gar nicht alle auf dem Plan. Wir Doofis (alle bei denen es nicht funktioniert) haben natürlich die Windows-Java-Version genommen, die von Hotroot verlinkt wurde, da sind nur 2 Dateien mit fontconfig enthalten.
Also.... unter [https://java.com/de/download/manual.jsp](https://java.com/de/download/manual.jsp) die **Linux**-Datei herunterladen, entpacken, Anweisungen von Hotroot befolgen, danach den Historian stoppen und wieder starten.
also zumindest bei mir läuft es jetzt endlich!
Gruß Tino

**Comment by mdzio** [comment]
Danke. Ich habe den letzten Hinweis mit in das Wiki aufgenommen: [Paket für Synology NAS](https://github.com/mdzio/ccu-historian/wiki#paket-für-synology-nas)

**Comment by Andree174** [comment]
Hallo zusammen,

ich stehe vor dem gleichen Problem wie meine Vorredner auch schon, anscheinend fehlen auch bei mir die fonds in Java.
Mein Problem, ich komme mit Putty zwar auf die NAS aber dann hört es auch schon wieder auf!
Z.b. /var/packages/java-installer/target/lib scheint es in meiner Struktur nicht zu geben oder kann ich das so nicht eingeben?
Ich habe leider vom programmieren/software nicht all zu viel Ahnung.

Gruß
Andree

**Comment by MKaiser96** [comment]
Hallo Andree,

ich kann dir da die Software WinSCP empfehlen. Damit kannst du dich per SSH auf das NAS anmelden und kannst dann ganz bequem die Ordnerstruktur einsehen. Vom Aufbau her ähnelt es dem Total Commander.
Mit WinSCP kannst du beispielsweise auf der linken Seite den lokalen Ordner mit den fonts anzeigen lassen und auf der rechten Seite den entsprechenden Ordner deines NAS. Dann kannst du ganz einfach per Drag&Drop deine Dateien kopieren.

Viele Grüße
Markus

**Comment by Cooper57** [comment]
Hallo zusammen

Ich habe CCU-Historian in der Version V3.0.0-beta.3 auf einer Synology mit DSM 7.0.1-42218 Update 2 installiert.
Weiterhin habe ich die fonts wie von hotroot am 15,06.2021 beschrieben installiert. 
Leider bekomme ich trotzdem keine Trendkurven angezeigt. Hat irgendjemand eine Idee?
Viele Grüße
Peter

**Comment by Tibinobo** [comment]
Hast du denn auch das Java-Paket von Linux genommen, so wie es etwas weiter oben steht? Nur in diesem Paket sind die vollständigen Fonts enthalten. Das hatte Mathias auch noch mal ins Wiki geschrieben.
Gruß Tino

**Comment by Cooper57** [comment]
Oh, da habe ich wohl einen Fehler gemacht. Ich habe die Dateien aus der Windows Version auf die NAS übertragen. Werde ich ändern und das Ergebnis hier posten.
Danke für den Hinweis. Ich habe soviel darüber gelesen, dass mir das entfallen war.
Gruß Peter

**Comment by Cooper57** [comment]
Hallo Tino
Jetzt hat es geklappt. Manchmal sieht man den Wald vor lauter Bäumen nicht mehr. Das naheliegendste war der Fall.
Danke für den Schubs in die richtige Richtung.
Gruß Peter

**Comment by mdzio** [comment]
Wahrscheinlich kann in der kommenden Version des CCU-Historians auf das Installieren der Font-Dateien verzichtet werden, wenn die Trends als SVG-Grafik generiert werden (siehe auch  #323).

**Comment by mdzio** [comment]
Die Version 2.9.0 kann die Trend-Grafiken als SVG generieren. Dadurch werden die Font-Dateien nicht mehr benötigt. Allerdings gibt es einige Einschränkungen:
* Die Web-Browser-Kompatibilität ist noch nicht ganz gegeben. Der Edge-Browser stellt beispielweise eine leere Trend-Grafik überhaupt nicht dar.
* Bei großen Zeitbereichen mit vielen Zeitreiheneinträgen wird die Dateigröße der SVG-Vektorgrafik sehr hoch.

**Comment by knowhowseeker** [comment]
Ok, ich wollte trotzdem noch die Fonts installieren und habe den Unix Install auf einem Windows 11 System in Downloads gespeichert und extrahiert. Ich sehe auf WINSCP meinen Download und die Java-Installer Directories. Ich kann auf Synology in WinSCP aber kein Directory erstellen - permission denied. Ich habe die Session mit dem admin passwort (ohne 2. Faktor) eröffnet.

**Comment by knowhowseeker** [comment]
> Ok, ich wollte trotzdem noch die Fonts installieren und habe den Unix Install auf einem Windows 11 System in Downloads gespeichert und extrahiert. Ich sehe auf WINSCP meinen Download und die Java-Installer Directories. Ich kann auf Synology in WinSCP aber kein Directory erstellen - permission denied. Ich habe die Session mit dem admin passwort (ohne 2. Faktor) eröffnet.

Hab's gefunden, musste mit auf WINSCP mit Root anmelden. Benutzte diese Anweisung: https://think.unblog.ch/en/enable-synology-root-login/

**Comment by Isomeer** [comment]
Moin!
Gibt es an dieser Front irgendwelche neuen Problemchen?
Habe CCU-H V4.0.1.3.0 auf DSM 7.1.1-42962 Update 6 und seit ein paar Wochen leider keine Diagramme. Webseite zeigt "Bitte warten, die Trend-Darstellung wird generiert" aber es passiert nix.
Den font-Ordner aus einem aktuellen Linux-Java sowie die fontconfig-Dateien auf das NAS kopiert, Berechtigungen angepasst, CCUH (und auch das ganze NAS) neu gestartet aber leider hält sich das Problem beständig.
Hat jemand einen Ansatz, was ich falsch mache?

**Comment by Cooper57** [comment]
Hallo Isomeer

 

Ich nutze eine CCU3 und habe „nur“ den CCU-Historian auf einer Synology mit DSM7.2.2 – 72806 Update 1 installiert. Bei mir werden die Trends dargestellt.

Insofern kann ich nicht nachvollziehen, was bei dir falsch läuft.

 

Von: Isomeer ***@***.***> 
Gesendet: Sonntag, 24. November 2024 17:26
An: mdzio/ccu-historian ***@***.***>
Cc: Cooper57 ***@***.***>; Comment ***@***.***>
Betreff: Re: [mdzio/ccu-historian] CCU-Historian kann auf der neuesten Synology DSM 7.0 nicht installiert werden (#261)

 

Moin!
Gibt es an dieser Front irgendwelche neuen Problemchen?
Habe CCU-H V4.0.1.3.0 auf DSM 7.1.1-42962 Update 6 und seit ein paar Wochen leider keine Diagramme. Webseite zeigt "Bitte warten, die Trend-Darstellung wird generiert" aber es passiert nix.
Den font-Ordner aus einem aktuellen Linux-Java sowie die fontconfig-Dateien auf das NAS kopiert, Berechtigungen angepasst, CCUH (und auch das ganze NAS) neu gestartet aber leider hält sich das Problem beständig.
Hat jemand einen Ansatz, was ich falsch mache?

**Comment by Cooper57** [comment]
Hallo

Ich habe auch den Historian in Version V4.0.1 und DSM 7.2.2-72806 Update 3 sowie die fonts aus der Linux Version jre1.8.0_321 von Januar 2022 installiert. Seit August 2024 mussten bei sämtlichen DSM Updates (7-4.0.1.3.0 | 7.2.2 – 72806  bis Update 3), zumindest bei mir, die Fonts nicht nachinstalliert werden. Insofern habe ich zunächst keine Idee.
Für die Fonts-Installation nutze ich WinSCP.

**Comment by gitHub42-User** [comment]
Es iseht aber nach irgendeinem Komponentenproblem aus -> 
Caused by: java.lang.NullPointerException: Cannot load from short array because "sun.awt.FontConfiguration.head" is null
	at org.jfree.text.TextFragment.calculateDimensions(TextFragment.java:230)

[stackTrace.txt](https://github.com/user-attachments/files/19487592/stackTrace.txt)

**Comment by Cooper57** [comment]
Dabei kann ich nicht weiterhelfen. Bin kein Linux-Experte. Vielleicht kann dir Mathias (mdzio) weiterhelfen.
Sorry

**Comment by Tibinobo** [comment]
Nur kurz die grundsätzliche Frage.... Hast du folgende Dateien auf deiner Synology? Auch mit entsprechenden Berechtigungen?
Wenn ja, dann kann ich leider auch nicht mehr beisteuern.

![Image](https://github.com/user-attachments/assets/eeb70943-4bb2-482c-ab71-94fe8f9944fb)

![Image](https://github.com/user-attachments/assets/3a21c3c8-1c83-4502-9d5a-8a34a3ff0742)

Gruß Tino

**Comment by gitHub42-User** [comment]
**SOLVED**
@mdzio : Habe einen cruden Workaround gefunden:
Auf dem NAS ist auch die Office Komponenten mit den Fonts installiert - das bringt ggf. die Suche nach Fonts durcheinander.
Ich habe jetzt stumpf in den /usr/share den Ordern fonts mit den Lucia* kopiert und den Parmater webServer.trendSvg=true laufen.
Jetzt kann Trend wieder die Grafiken darstellen....

Klingt aber alles nicht nach Logik. 
Falls du also eine korrekte Idee hast, gerne.

**Comment by mdzio** [comment]
Ich habe leider selber kein Synology NAS, sodass ich hier nicht weiterhelfen kann. Das Fehlen der Schriften bei den Java-Installationen auf dem Synology ist ärgerlich. Wenn es möglich ist, am besten das Docker-Image verwenden.

**Comment by gitHub42-User** [comment]
@mdzio Vielen Dank, vlt. hilft es auch Anderen mit diesem Problem, wenn man also die Fonts so wie grundsätzlich installiert und mit Rechten versieht, dann aber zusätzlich den gesamten fonts Ordnet nach /usr/share kopiert, klappt es bei mir jetzt.....
