### ISSUE TITLE
Datenpunkte sollten in der Default-Config inaktiv sein

### ISSUE THREAD

**Issue by Wookbert** [mdzio/ccu-historian#262]
Ich bin CCU-Historian NOOB, und mir ist gerade der erste USB-Stick unter der „Schreiblast“ der CCU-Historian zusammengeklappt. Zugegeben: War eine NoName-China-Werbe-Gurke.

Dabei ist mir aber erst bewusst geworden, wieviele Daten erfasst werden, und dass jeder Datenpunkt per se erstmal erfasst wird, ob er nun von Interesse ist, oder nicht. 

Wenn ich es richtig verstehe, werden inaktive Datenpunkte nicht erfasst. Falls dem so ist, bin ich der Meinung, dass es sinnvoller wäre, dass jeder Datenpunkt in der Default.Konfiguration erstmal inaktiv ist. Ich habe in Issue #256 gelesen, dass man das wohl durch `historian.defaultDisabled=true` in `ccu-historian.config` nachträglich so einstellen kann, besser wäre es aber, wenn das „ab Werk“ schon so gesetzt wäre (schonender für den Stick, sowohl was die Zugriffe, als auch den Speicherbedarf angeht).

Siehe in dem Kontext auch meine Issues #263 und #264.

**Comment by mdzio** [comment]
Sicherlich sollte auf die Option `historian.defaultDisabled=true` explizit nochmal hingewiesen werden, wenn ein USB-Stick verwendet wird.

Ich würde es aber nicht als Standardeinstellung nehmen, da dann zu viele Support-Anfragen kommen, der CCU-Historian würde nicht funktionieren.

**Comment by mdzio** [comment]
Dokumentation wurde ergänzt (s.a. [Paket für CCU3 und RaspberryMatic](https://github.com/mdzio/ccu-historian/wiki#paket-für-ccu3-und-raspberrymatic)).
