### ISSUE TITLE
Datenpunktkonfiguration: Möglichkeit alle sichtbaren Datenpunkte mit einem Klick zu selektieren

### ISSUE THREAD

**Issue by Wookbert** [mdzio/ccu-historian#263]
Wenn man _nachträglich_ das Gros seiner hunderten Datenpunkte auf inaktiv setzen möchte, dann hat man, wenn ich es richtig sehe, eine Klick-Arie in der Ansicht `Datenpunktkonfiguration` vor sich.

Was fehlt, ist die Möglichkeit, wie in der Ansicht `Datenpunktliste`, alle sichtbaren Datenpunkte mit einem Klick zu selektieren und die selektierten Datenpunkte kollektiv auf `inaktiv` oder `verstecken` zu setzen.

<img width="912" alt="Bildschirmfoto 2020-12-25 um 23 06 39" src="https://user-images.githubusercontent.com/3104762/103142837-38515a00-470b-11eb-8053-8ae2cb03b65d.png">

**Comment by mdzio** [comment]
Anmerkung: Mit der Skriptumgebung kann eine Massenkonfiguration ebenfalls realisiert werden. Skripte dazu sind bei den [Tipps & Tricks](https://github.com/mdzio/ccu-historian/wiki/Skripte) zu finden

**Comment by mdzio** [comment]
Es können nun von allen gefilterten Datenpunkten die Einstellungen gleicheitig gesetzt weren.
![001_18012021_191710](https://user-images.githubusercontent.com/24684496/104950933-e0340d80-59c1-11eb-8702-4162180c0e7a.png)
