### ISSUE TITLE
Option um Daten älter als x Monate/Jahre aus Datenbank automatisch zu entfernen

### ISSUE THREAD

**Issue by Wookbert** [mdzio/ccu-historian#264]
NOOB-Frage/-Request: Falls noch nicht existent, wäre es schön eine Option zu haben, dass Daten die älter als x Monate/Jahre sind, automatisch aus der Datenbank entfernt werden, damit der USB-Stick nicht irgendwann überläuft.

Einstellbar global, evtl. aber auch für einzelne Datenpunkte mit unterschiedlichen Laufzeiten ... und das kombinierbar (globaler Wert, der durch einzeln gesetzte Werte für den entsprechenden Datenpunkt ersetzt wird).

**Comment by mdzio** [comment]
Siehe auch #159.

**Comment by mdzio** [comment]
Mit dem [Skript "Alte Zeitreihendaten löschen"](https://github.com/mdzio/ccu-historian/wiki/Skripte#alte-zeitreihendaten-löschen) kann der Löschvorgang nun zumindest manuell ausgeführt werden. 

Ein automatische Ausführung des Löschvorgangs, würde ich dann allgemein mit einer neuen Funktionalität für eine geplante Ausführung von Skripten erschlagen.

**Comment by the-other-martin** [comment]
Hallo Mathias! Danke für das Skript - dadurch laufen Diagramm Darstellungen wieder flot!
Frage: Ich würde gerne das [Skript ](https://github.com/mdzio/ccu-historian/wiki/Skripte#alte-zeitreihendaten-l%C3%B6schen) automatisch auf meinem RaspberryPI laufen lassen. Wie sollte das script dazu aussehen?
etwa so: CCU Historian stop, Alte Zeitreihendaten löschen, CCU Historian start ?

**Comment by mdzio** [comment]
Ja, das sollte funktionierten. Eventuell kannst Du dann noch ein `-compact` ausführen, damit die Datenbankdatei auch kleiner wird.
Das ganze Skript kann dann noch per cron-Job regelmäßig gestartet werden.

**Comment by mdzio** [comment]
Ich arbeite gerade daran, dass Skripte (s.a. Skriptumgebung) zyklisch automatisch ausgeführt werden können (ab V3.2.0). Die Aufgabenstellung könnte dann mit einem Skript in der `ccu-historian.config` gelöst werden:

```
database.tasks.clean.enable=true
database.tasks.clean.cron="0 0 2 * * ?"
database.tasks.clean.script={
	/*
	Alte Zeitreihendaten löschen V1.0.0
	Wichtig: Vor Anwendung des Skripts ein Backup der Datenbank erstellen!
	*/
	
	// *** Konfiguration ***
	
	// Anzahl der Tage, die in der Datenbank verbleiben sollen.
	def daysToKeep = 365
	
	// Testlauf durchführen? Bei einem Testlauf wird die Datenbank nicht verändert.
	// (Ja: true, Nein: false)
	def testRun = true
	
	// *** Skript ***
	
	log.info "Alte Zeitreihendaten werden gelöscht:"
	def deleteDate=new Date()-daysToKeep
	log.info "Löschdatum: ${deleteDate.format("dd.MM.YYYY")}"
	def totalCnt=0
	database.dataPoints.each { dp ->
	    def cnt
	    if (testRun) {
	        cnt=database.getCount(dp, null, deleteDate)
	    } else {
	        cnt=database.deleteTimeSeries(dp, null, deleteDate)
	    }
	    totalCnt+=cnt
	    log.info "$dp.displayName: $cnt Einträge"
	}
	log.info "Gesamtanzahl der gelöschten Einträge: $totalCnt"
}
```

Hinweis: Damit das Skript auch die Datenbank verändert, die Zeile `def testRun = true` auf `def testRun = false` abändern.

**Comment by the-other-martin** [comment]
Hallo Mathias!
Großartig! Vielen Dank! Ich habe heute auf  V3.2.0 upgraded und das script oben auf 31 Tage gestellt.
Schöne Grüße, Martin
