### ISSUE TITLE
Datenbank archivieren aus Performancegründen

### ISSUE THREAD

**Issue by andispammonyer** [mdzio/ccu-historian#265]
Ich nutze seit einem halben Jahr nun CCU Historian auf meinem RasPi3B+ mit RaspberryMatic. Abgesehen von einem Datenbankfehler der mich 2 Monate Messdaten gekostet hat (Grund = Stecker vom RasPi gezogen oder weil er sich aufgehängt hatte), bin ich sehr zufrieden mit dem Tool und hätte einen Verbesserungsvorschlag.
Meine Datenbank ist nach nur 4 Monaten schon ziemlich groß geworden, weshalb ich bald ein Problem mit meinem USB Stick bekommen werde, auch wegen den vielen Backups.
Mir kam die Idee die Datenbank zu splitten bzw. die Möglichkeit zu haben mehrere ("identische") Datenbanken einbinden zu können.
Ich versuche mal anhand eines Beispiel das anschaulicher zu erklären.
Ich mache jetzt am 31.12.2020 einen Split und nutze in 2021 eine neue Datenbankdatei. Wenn ich allerdings eine Abfrage stellen würde, welche auch Messdaten vor 2021 beinhalten, dann könnte CCU Historian die alte Datenbank mit einbinden, aber eben erst dann und nicht wie jetzt permanent, alles in einer riesigen Datenbank.
Die Datenbank Dateinamen müssten dann einer bestimmten Namenskonvention folgen, damit CCU Historian diese finden bzw. zuordnen kann. CCU Historian müsste sich merken in welcher Datenbankdatei welcher Zeitraum abgebildet ist und wo der Speicherort der Datanbankdatei ist. 
In meinem Fall wöllte ich gerne die aktive Datenbank H2.trace.db auf dem USB Stick in meinem RasPi lagern und die älteren Datenbanken auf /mnt welcher auf mein NAS zeigt.

**Comment by mdzio** [comment]
Die Anbindung von mehreren Datenbanken ist zu aufwendig, deshalb erfolgt erst einmal keine Umsetzung.

Teile der Datenbank können nun exportiert und bei Bedarf wieder importiert werden (s.a. #289).
