### ISSUE TITLE
Keine Trend Charts nach 2.5.3 auf Synology

### ISSUE THREAD

**Issue by Mi2NaLe** [mdzio/ccu-historian#271]
Nach der manuellen Update-Installation der aktuellen SPK auf der Diskstation, werden die 48h- und Monats-Trends nur mit einem "Broken-image-link" Symbol angezeigt.

Wenn ich den Image-Link (z.B. http://192.168.1.19:8080/query/trend?dp1=141&b=-48h ) direkt aufrufe, bekomme ich:

HTTP ERROR 500
Problem accessing /query/trend. Reason:
java.lang.reflect.InvocationTargetException

... und ein paar Meter mehr Fehlermeldung.

Mit 2.5.2 gab es das Problem nicht.

**Comment by mdzio** [comment]
Funktioniert denn die Trend-Anzeige innerhalb der Web-Oberfläche vom CCU-Historian?
Bitte mal anstatt `/trend?` `/trend.gy?` in der Adresse testen.
Ansonsten noch die weiteren Fehlermeldungen als Dateianhang zur Verfügung stellen.

**Comment by Mi2NaLe** [comment]
In der Web-Oberfläche habe ich die Trend Charts vermisst (s. Bild).
Den Trend-Link habe ich da raus kopiert.
Mit .gy passiert das gleiche (s. Text-Datei)

Ich habe Java8 von Syno installiert und auf den aktuellen Stand gebracht. Für das "Statistik-Tool" (https://homematic-forum.de/forum/viewtopic.php?f=38&t=57820) brauchte ich eine höhere Version und habe Java15 von https://get.filebot.net/syno/ zusätzlich installiert. Das war aber schon vor dem Update auf 2.5.3. Mit 2.5.2. hatte alles funktioniert.

![CCU-Historian 253](https://user-images.githubusercontent.com/57563516/105479807-35fc0480-5ca5-11eb-923e-85ab564148b9.jpg)
[HTTP ERROR 500.txt](https://github.com/mdzio/ccu-historian/files/5855155/HTTP.ERROR.500.txt)

**Comment by mdzio** [comment]
Bei meinen Installationen kann ich das Problem nicht reproduzieren. Es könnte auch mit #82 (Headless Java-VM) zusammen hängen.
Ich schaue auch nochmal nach, ob versehentliche Änderungen zwischen 2.5.2 und 2.5.3 gab.

**Comment by Mi2NaLe** [comment]
Jetzt bin ich überfordert: Der CCU-Historian wird auf der DS automatisch gestartet. Wo komme ich da mit einer Kommandozeilenoption dazwischen?

Außerdem hat die DS zwischenzeitlich den Standard-Java-Pfad auf die V15 geändert. Keine Ahnung wann und durch was das verändert wurde.

**Comment by mdzio** [comment]
Da ich selber kein Synology NAS besitze, kann ich da leider nicht weiterhelfen. Es ist aber anscheinend kein grundsätzliches Problem, da sich bisher noch kein anderer Synology-Anwender gemeldet hat.

**Comment by Mi2NaLe** [comment]
ok. Hab jetzt mal auf der DS Oberfläche den CCU-Historian angehalten und von Console explizit mit der Java8 gestartet:
`/volume1/@appstore/Java8/j2sdk-image/bin/java -jar ccu-historian.jar`
Damit tut es dann!
Ich werde mich also weiter um die verschiedenen Java-Versionen kümmern. Danke für die Unterstützung bis hier!

**Comment by Heinz9** [comment]
Nun muss ich mich hier auch noch einhängen nachdem ich alles, was ich zu diesem Thema gefunden habe versucht habe umzusetzen... 
Auf meiner alten DS mit DSM6 läuft Historian seit über einem Jahr einwandfrei. Bin ein Fan dieses Produktes und bedanke mich an dieser Stelle für die vielen Stunden, die bisher in den Historian geflossen sind…
Auf meiner neuen DS läuft DSM7. Nach gefühlten 3 Tagen installieren & deinstallieren ziehe ich ein ernüchterndes Fazit. Egal wie… Historian läuft, Daten werden aufgezeichnet und können als .CSV auch dargestellt werden. Ich bekomme jedoch auf keine Weise Trend Grafiken angezeigt. Anstelle der Grafik erhalte ich immer «**Bitte warten: Die Trend-Darstellung wird generiert!**»
Der folgende Eintrag jeweils im Historian Log, sobald ich eine Trend-Grafik darstellen will:
```
SEVERE |Exception: Probable fatal error: No physical fonts found.
SEVERE |Detail: java.lang.Error: Probable fatal error: No physical fonts found. 
(jeweils gefolgt von einer Liste von Einträgen wie "at org.jfree.text.TextFragment.calculateDimensions(TextFragment.java:230)")
```
Konkret ist bei mir installiert: 

- Synology DS218+ DSM7
- Historian 3.0.0.2.3 (gefüttert von einer CCU3)
- Java Installer 2.1.6 
> -- openjdk version "17.0.1" 2021-10-19
> -- OpenJDK Runtime Environment (build 17.0.1+12-39)
> -- OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)

Die Fonts Dateien wurden gem. Beschreibung von hotroot und MKaiser96 aus dem Linux Paket «jre-8u321-linux-i586.tar» übernommen und eingepflegt und sehen soweit ich das als u*x Laie beurteilen kann, korrekt aus. Die erwähnten Verzeichnisse enthalten:
**Verzeichnis: /var/packages/java-installer/target/lib$**
```
-rw-r--r-- 1 Java Java  1678 Jan 29 18:23 fontconfig.bfc
-rw-r--r-- 1 Java Java  1938 Jan 29 18:23 fontconfig.properties.src
-rw-r--r-- 1 Java Java  4532 Jan 29 18:23 fontconfig.RedHat.5.bfc
-rw-r--r-- 1 Java Java  8841 Jan 29 18:23 fontconfig.RedHat.5.properties.src
-rw-r--r-- 1 Java Java  4250 Jan 29 18:23 fontconfig.RedHat.6.bfc
-rw-r--r-- 1 Java Java  8735 Jan 29 18:23 fontconfig.RedHat.6.properties.src
-rw-r--r-- 1 Java Java  6702 Jan 29 18:23 fontconfig.SuSE.10.bfc
-rw-r--r-- 1 Java Java 16772 Jan 29 18:23 fontconfig.SuSE.10.properties.src
-rw-r--r-- 1 Java Java  7032 Jan 29 18:23 fontconfig.SuSE.11.bfc
-rw-r--r-- 1 Java Java 16781 Jan 29 18:23 fontconfig.SuSE.11.properties.src
-rw-r--r-- 1 Java Java  4668 Jan 29 18:23 fontconfig.Turbo.bfc
-rw-r--r-- 1 Java Java  9192 Jan 29 18:23 fontconfig.Turbo.properties.src
```
**Verzeichnis: /var/packages/java-installer/target/lib/fonts$** 
```
drwxr-xr-x 1 Java Java    388 Jan 29 18:23 .
drwxr-xr-x 1 Java Java   1804 Jan 29 16:13 ..
drw-r--r-- 1 Java Java    378 Jan 29 18:23 fonts
-rw-r--r-- 1 Java Java  75144 Jan 29 16:13 LucidaBrightDemiBold.ttf
-rw-r--r-- 1 Java Java  75124 Jan 29 16:13 LucidaBrightDemiItalic.ttf
-rw-r--r-- 1 Java Java  80856 Jan 29 16:13 LucidaBrightItalic.ttf
-rw-r--r-- 1 Java Java 344908 Jan 29 16:13 LucidaBrightRegular.ttf
-rw-r--r-- 1 Java Java 317896 Jan 29 16:13 LucidaSansDemiBold.ttf
-rw-r--r-- 1 Java Java 698236 Jan 29 16:13 LucidaSansRegular.ttf
-rw-r--r-- 1 Java Java 234068 Jan 29 16:13 LucidaTypewriterBold.ttf
-rw-r--r-- 1 Java Java 242700 Jan 29 16:13 LucidaTypewriterRegular.ttf
```
Habe auch mehrmals wieder alles deinstalliert, die DS rebootet und das ganze wiederholt. Auch nach Reboot im Anschluss an Installation leider keine Verbesserung. 
Wer hat mir einen Input, der mich weiterbringt?
Vielen Dank Heinz
