### ISSUE TITLE
Datenpunktkonfiguration langsam

### ISSUE THREAD

**Issue by jht11** [mdzio/ccu-historian#275]
Obwohl der CCUHistorian sonst auf meinem PI4 sehr schnell läuft, dauert es circa 35 Sekunden bis die Datenpunktkonfiguration geladen ist. Dies erscheint gerade wegen der sonst sehr schnellen Datenbank recht langsam.

**Comment by mdzio** [comment]
Hilft denn ein Neustart des CCU-Historians?

**Comment by jht11** [comment]
Nein Mathias. 
Ich habe Gefühl das da beim Datenbankzugriff vielleicht ein Index fehlt? 


Jan

**Comment by mdzio** [comment]
Ich habe gerade ein paar Tests durchgeführt. Die Zeit für die Datenbankabfrage fällt kaum ins Gewicht. Die Erstellung der HTML-Seite nimmt den Großteil der Zeit in Anspruch. Das liegt wohl an der verwendeten Skriptsprache. Da ist auch kaum Verbesserungspotenzial.
