### ISSUE TITLE
CCU - Unsichtbare Systemvariablen - Bezeichnungen

### ISSUE THREAD

**Issue by bs0001** [mdzio/ccu-historian#277]
Hallo,

gerne würde ich die unsichtbaren CCU-Systemvariablen (z.B. svenergycounter) verwenden, um mir den Stromverbrauch der jeweiligen Geräte anzeigen zu lassen.
Leider ist es so, dass diese vom Namen her im Diagramm nicht mehr zuordnenbar sind.
So wird als Datenpunktinfo bspw. folgendes angezeigt:
svEnergyCounter_<ISE-ID>_0001D3CXXXXXXX:6

Gibt es eine Möglichkeit, diesem Datenpunkt einen Namen zu geben (z.B. Kaffeemaschine)?
Oder gibt's vielleicht eine andere Möglichkeit?

Viele Grüße
Bernd

**Comment by mdzio** [comment]
Schau Dir mal #50 an. Ein konfigurierbarer Anzeigename wird bereits vom CCU-Historian intern unterstützt.

**Comment by bs0001** [comment]
... super, vielen Dank, das hilft weiter!
Zudem habe ich mir eigene Systemvariablen angelegt und in die PrgEnergyCounter-Programme am Ende eingehängt in der CCU.
Diese lass ich dort befüllen, in dem ich den energyCounter noch durch 1000 teile und damit die Ergebnisse in kWh habe. Das liest sich besser als due Wh.

Viele Grüße
Bernd
