### ISSUE TITLE
Probleme beim Installieren+ keine Trenddarstellung

### ISSUE THREAD

**Issue by tobiasjaeger78** [mdzio/ccu-historian#280]
Hallo,
ich hatte 2 Jahre eine Pi4 für CCU-Historian laufen. Nach einem Systemausfall der CCU und Rückspielen eines Backups habe ich das System nicht mehr zum Laufen gebracht.
Da ich aber noch eine Syno habe die aktuell keinen anderen Zweck hat, dachte ich mir das es den versuch Wert wäre die zu versuchen.
Daten:
DS216se mit DSM 6.2.3-25426 Update 3
Java 8.0.212-0018
CCU-Historian 2.5.3

Mein erstes Problem war, das bei der Installation von CCU Historian die Frage kommt ob man das System selbst einrichten will?
In einem Anfall von vielleicht Selbstüberschätzung habe ich das versucht.
Das Problem ist, das dann kein ccu-historian.config file angelegt wird. Einige Versuche den File zu bearbeiten scheiterten mit vi. Erst die Installation von nano hat zumindest dieses Problem behoben. Einen selbst kreierten config file habe ich trotz alledem nicht zum Laufen gebracht.
Nach einer Neuinstallation und der Anwahl das System die nötigen Einstellungen zu machen, hat mein System endlich gestartet.
Jetzt habe ich nur das Problem mit der Darstellung der Trends.
Datenpunkte werden alle gefunden.
Im Netzt habe ich einige ältere Einträge gefunden bei denen oft die Java Version eine Rolle spielte.
Gibt es hier Erfahrungswerte, welche Java Version funktioniert?
Freu mich über jede Info. Danke vorab.

Hoffe ich habe alle nötigen Infos im Beitrag.

**Comment by malansk** [comment]
Hallo Tobias,

habe diese CCU-Historian bei mir auf der 116 laufen, Java8 Version 1.8.0.261.
Installiert seit ca. 10/2020.

Es gab vor ein paar Wochen schonmal einen Tread bzgl. Trends & Java-Version.

Mit freundlichem Gruß
Martin Lansky

Von: tobiasjaeger78<mailto:notifications@github.com>
Gesendet: Freitag, 26. Februar 2021 09:21
An: mdzio/ccu-historian<mailto:ccu-historian@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Betreff: [mdzio/ccu-historian] Probleme beim Installieren+ keine Trenddarstellung (#280)


Hallo,
ich hatte 2 Jahre eine Pi4 für CCU-Historian laufen. Nach einem Systemausfall der CCU und Rückspielen eines Backups habe ich das System nicht mehr zum Laufen gebracht.
Da ich aber noch eine Syno habe die aktuell keinen anderen Zweck hat, dachte ich mir das es den versuch Wert wäre die zu versuchen.
Daten:
DS216se mit DSM 6.2.3-25426 Update 3
Java 8.0.212-0018
CCU-Historian 2.5.3

Mein erstes Problem war, das bei der Installation von CCU Historian die Frage kommt ob man das System selbst einrichten will?
In einem Anfall von vielleicht Selbstüberschätzung habe ich das versucht.
Das Problem ist, das dann kein ccu-historian.config file angelegt wird. Einige Versuche den File zu bearbeiten scheiterten mit vi. Erst die Installation von nano hat zumindest dieses Problem behoben. Einen selbst kreierten config file habe ich trotz alledem nicht zum Laufen gebracht.
Nach einer Neuinstallation und der Anwahl das System die nötigen Einstellungen zu machen, hat mein System endlich gestartet.
Jetzt habe ich nur das Problem mit der Darstellung der Trends.
Datenpunkte werden alle gefunden.
Im Netzt habe ich einige ältere Einträge gefunden bei denen oft die Java Version eine Rolle spielte.
Gibt es hier Erfahrungswerte, welche Java Version funktioniert?
Freu mich über jede Info. Danke vorab.

Hoffe ich habe alle nötigen Infos im Beitrag.

**Comment by tobiasjaeger78** [comment]
Hi, vielen Dank für den Hinweis. Das neueste Release von Java hats gebracht.
