### ISSUE TITLE
CUxD-Datenpunkte werden nicht registriert wenn der Parameter "devices.device1.prefix=" benutzt wird

### ISSUE THREAD

**Issue by Baxxy13** [mdzio/ccu-historian#281]
Hallo Mathias,
ich "spiele" gerade mit dem Historian (V2.6.0 unter Windows) ein bisschen um die ganzen config-Parameter zu testen und zu verstehen.
Und ich denke ich bin dabei auf einen Bug gestoßen.

Grundsätzlich läuft der Historian unauffällig, keine Fehlermeldungen im Log oder sonstige Probleme.
Mit dem folgenden "devices-Abschnitt" meiner .config wird alles korrekt aufgezeichnet.

```
// Typ der Zentrale: CCU1 oder CCU2
devices.device1.type=CCU3
devices.device1.address='192.168.11.16'
// devices.device1.prefix='Pi4-'
devices.device1.timeout=2000
devices.device1.reinitTimeout=600000
devices.device1.sysVarDataCycle=60000
devices.device1.plugin1.type=CUXD
```

Starte ich nun Historian mit neuer Datenbank neu und habe dabei die Zeile...
`devices.device1.prefix='Pi4-'`
"aktiv", werden SysVars / HmIP und BidCos korrekt gefunden und mit Präfix angezeigt (z.B. Pi4-HmIP-RF).

Obwohl der Start im Log gut aussieht...
```
2021-03-25 20:16:43|INFO   |Setting up plug-in 1
2021-03-25 20:16:43|FINE   |Plug-in 1: Reading configuration option 'type': CUXD
2021-03-25 20:16:43|FINE   |Device 1: Reading configuration option 'watchdogProgram': 
2021-03-25 20:16:43|FINE   |Device 1: Reading configuration option 'watchdogCycle': 
2021-03-25 20:16:43|INFO   |Configured following interfaces: Pi4-BidCos-RF, Pi4-HmIP-RF, Pi4-SysVar, Pi4-CUxD
2021-03-25 20:16:43|INFO   |Starting interfaces

```
... fehlen die Datenpunkte von CUxD-Geräten (auch nach gut 12h warten) völlig.

**Zusammengefasst:**
"Aktiviere" ich den Präfix wird kein CUxD Datenpunkt registriert / aufgezeichnet.

Grüße
Baxxy

**Comment by mdzio** [comment]
Ich denke, dass ist ein seit langem bekannter Fehler im CUxD. Er versendet Wertänderungen an den CCU-Historian (oder andere Software) immer mit der Identifikation _CUXD_. Der CCU-Historian erwartet aber in Deinem Fall _Pi4-CUxD_.

Die Wertänderungen vom CUxD sollten in einer detaillierten Log-Datei auftauchen. (Option logSystem.fileLevel=Level.FINEST) Sie werden vom CCU-Historian nur nicht gespeichert, da er nicht wissen kann, wer diese gesendet hat. Dies ist z.B. problematisch, wenn der CCU-Historian zwei CCUs aufzeichnen soll, auf denen jeweils der CUxD installiert ist.

**Comment by Baxxy13** [comment]
Alles klar, ich habe die Problematik verstanden. 
Ich werde mal Uwe von CUxD dazu befragen.

Ist natürlich schade das man die Präfix - Option nicht nutzen kann / darf wenn man CUxD-Datenpunkte von einer oder mehreren Zentralen aufzeichnen möchte.

Meines Erachtens wäre es auch sinnvoll diese Einschränkung im Wiki zu vermerken.

**Comment by Baxxy13** [comment]
Hallo Mathias,
ich habe Antwort von Uwe erhalten.

Er kennt das Problem und sagt dazu das dieses Problem leider nicht so einfach zu beheben ist.
Er sagte aber auch das er vielleicht, wenn er mal etwas mehr Zeit hat, den Programmteil neu schreibt damit die gesendeten Daten an jeden Client dynamisch generiert werden können. 
Das lässt hoffen.

Als Workaround schlägt er vor die IP-Adresse der jeweiligen Zentrale mit in die Identifikation einzubeziehen.

Grüße
Baxxy

**Comment by mdzio** [comment]
Ich werde im Handbuch auf die Problematik hinweisen: Zurzeit können nicht mehrere CUxD auf verschiedenen CCUs aufgezeichnet werden.
Der vorgeschlagene Workaround lässt sich ebenfalls nicht einfach in den CCU-Historian einbauen.

**Comment by mdzio** [comment]
Das Handbuch ist ergänzt worden.
