### ISSUE TITLE
Bei Datenpunkten mit "Swinging Door" geht der Trend nicht bis zum aktuellen Wert

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-historian#282]
Durch den "Swinging Door" Algorithmus wird der Messwertverlauf als Geradenstücke in der Datenbank abgelegt. Wenn der aktuelle Messwert sich entlang einer Gerade entwickelt, befindet sich dieses letzte Geradenstück noch nicht in der Datenbank. Bei der Trenddarstellung fehlt dann dieser Zeitbereich. 

Mögliche Lösungen:
* Der aktuelle Messwert wird immer in der Datenbank abgespeichert und später immer wieder gelöscht, solange sich der Messwert auf einer Geraden entwickelt. Dadurch ist aber die optionale Zwischenspeicherung von Wertänderungen im Arbeitsspeicher zur Schonung des Speichermediums hinfällig.
* Der letzte Messwert wird bereits vom "Swinging Door"-Prozessor intern vorgehalten. Bei Datenbankabfragen könnte dieser automatisch angefügt werden.
* Der "Swinging Door" Algorithmus könnte nur auf ältere Einträge (z.B. 24h) angewendet werden. Bis zum aktuellen Zeitpunkt liegen dann Rohdaten in der Datenbank.

**Comment by MichaelN0815** [comment]
Ich glaube, ich bin gerade über diesen "Design-Flaw" gestolpert:
https://homematic-forum.de/forum/viewtopic.php?f=38&t=68885

**Comment by MKaiser96** [comment]
Hallo Mathias,

gibt es bzgl. der Problematik Entwicklungsfortschritte? Ich habe aktuell einen Datenpunkt, der tagsüber Leistung misst und nachts ausgeschaltet ist. Daher ist die Leistung Null, aber der Graph zeigt in der Zeit nichts an. Der Graph wird erst aufgebaut, wenn wieder eine Leistung ungleich Null gemessen wird.

**Comment by mdzio** [comment]
Die eingangs erwähnten Möglichkeiten dies umzusetzen sind zu aufwändig. Es wurde nun so umgesetzt, dass wenn ein Trend angezeigt werden soll, kurz vorher der intern vorgehaltene letzte Wert des Datenpunktes in die Datenbank geschrieben wird. Dadurch werden zwar mehr Werte archiviert als nötig, dies ist aber wohl hinnehmbar.

**Comment by mdzio** [comment]
Siehe #356.
