### ISSUE TITLE
ccu übernimmt bei Installation auf dem Raspberry nicht alle Datenaus der CCU3

### ISSUE THREAD

**Issue by thommyiii** [mdzio/ccu-historian#283]
Auf dem Raspberry werden von der CCU3 keine Daten der angelernten Geräte nur die "SysVar" Werte übernommen, aber auf dem Windows Rechner werden alle Daten aus der CCU3 übernommen, (in beiden Fällen: gleiches Netztwerk wie die CCU3, die Historian Version 2.6.0 und identische Config Datei, jeweils nur auf einem Rechner gestartet).  In der CCU 3 sind bereits alle Ports offen und unter dem Punkt "Homematic XML-RPC API" ist der Vollzugriff eingerichtet.
Wo kann der Fehler sein?

**Comment by mdzio** [comment]
Ein paar Hinweise:
* Die Datenpunkte der Geräte erscheinen erst, wenn diese das erste Mal ihren Wert ändern. Bitte nach einer Stunde Laufzeit noch einmal prüfen.
* In den Konfigurationsdateien sollte jeweils die Option `devices.historianAddress` auf die IP-Adresse des jeweiligen Gerätes gesetzt werden.

**Comment by thommyiii** [comment]
Nach der Erprobung mit dem Windows-Rechner war der erste Punkt klar.
Der zweite Punkt hat den Erfolg gebracht, aber nach dem Programmstart gibt es folgende Warnmeldungen (scheint folgenlos):
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v9.Java9 (file:/media/pi/Samsung%20USB/ccu-historian-2.6.0-bin/lib/groovy-3.0.7-indy.jar) to field java.util.ArrayList.size
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v9.Java9
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

im prinzip also ok.

**Comment by mdzio** [comment]
Die Warnmeldungen sind unkritisch. Sie sollten eigentlich nicht mehr mit der V2.6.0 erscheinen (s.a. #206).

Welche Java-Version verwendest Du denn?

Aber ich schließe mal diesen Eintrag.

**Comment by thommyiii** [comment]
Hier die JavaVersionsdaten:
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-post-Raspbian-1deb10u2)
OpenJDK Server VM (build 11.0.9.1+1-post-Raspbian-1deb10u2, mixed mode)

**Comment by mdzio** [comment]
Die Ursache liegt in einer fremden Bibliothek. Ich sehe gerade, dass es von dieser eine neue Version gibt. Eventuell ist die Warnmeldung damit behoben.

**Comment by thommyiii** [comment]
Habe bis jetzt keinen vertrauenswürdigen Weg gefunden, eine neuere Version auf meinem Raspi zu installieren. mit 
sudo apt full-upgrade
sudo apt install default-jdk
bzw. 
sudo apt remove default-jdk
sudo apt install openjdk-11-jdk
bleibt es immer bei "11.0.9.." und installiert nicht das neuere "11.0.10.." oder bin ich da falsch unterwegs?

**Comment by mdzio** [comment]
Die fremde Bibliothek ist Bestandteil vom CCU-Historian. Die eingesetzte Java-Version (9 oder höher) ist egal.
Die Fehlermeldung ist unkritisch und hat keinerlei Auswirkungen auf den Betrieb des CCU-Historians.
