### ISSUE TITLE
Laufzeitfehler "No signature of method: ... clone() is ..." auf Java Version 16

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-historian#291]
Exakte Java Version: OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)

**Comment by hotroot** [comment]
mit der 2.7.0-beta2 kommen jetzt neue Werte im Historian an, aber die Trend-Anzeige scheitert noch immer mit folgender Fehlermeldung:
``Fehler: No signature of method: mdz.ccuhistorian.webapp.TrendParameters.clone() is applicable for argument types: () values: [] Possible solutions: clone(), collect(), collect(groovy.lang.Closure), collect(java.util.Collection, groovy.lang.Closure), find(), any() ``

Hier das Logfile mit den ausführlichen Fehlern:
[ccu-historian.log](https://github.com/mdzio/ccu-historian/files/6644680/ccu-historian.log)
