### ISSUE TITLE
"Invalid file format" when installing on final release of Synology DSM7.0

### ISSUE THREAD

**Issue by mike-bee** [mdzio/ccu-historian#292]
Upgraded to DSM 7.0 final today. Installation of package "ccu-historian-dsm7-2.7.0-2.3-noarch.spk" failed with message "Invalid file format" on DS1815+.
According change log CCU-Historian should be compatible with DSM7 since 2.7.0 beta 2.

![ccu-historian](https://user-images.githubusercontent.com/30027622/124354186-1204fd80-dc0b-11eb-9806-754ca68feca9.png)

**Comment by sw256** [comment]
I tried 2.7.0 beta 3 and 4 both have this error.
DSM 7.0-41890

**Comment by sw256** [comment]
Hatte noch vergessen zu erwähnen, dass ich die Punkte aus #261 (https://github.com/mdzio/ccu-historian/issues/261) bereits ausprobiert habe. Insbesondere die Java Fonts habe ich kopiert.

**Comment by mdzio** [comment]
@hotroot: Kannst Du hier vielleicht weiterhelfen?

**Comment by hotroot** [comment]
Es scheint mal wieder die Versionsnummer zu sein. Hier der entsprechende Log-Auszug:
```
==> synoscgi.log <==
2021-07-14T00:33:09+02:00 BigStation synoscgi_SYNO.Core.Package.Installation_1_upload[17823]: pkgverify.cpp:240 Failed to load pkg info, version=[2.7.0-2.3], correct-format=[^\d+(\.\d+){0,5}(-\d+)?$]
2021-07-14T00:33:09+02:00 BigStation synoscgi_SYNO.Core.Package.Installation_1_upload[17823]: pkgverify.cpp:297 Failed to verify package, spk=[/volume1/@tmp/upload_tmp.178230] result=[{"action":"prepare","beta":true,"betaIncoming":true,"error":{"code":261,"description":"invalid package info content"},"installReboot":false,"package":"ccu-historian-dsm7","packageName":"CCU-Historian","stage":"prepare","success":false}]

```

**Comment by mdzio** [comment]
Ich hatte extra in die SPK-Dokumentation für das Format der Versionsnummer hinein geschaut. Es ist aber gut, dass in der Fehlermeldung der reguläre Ausdruck zur Prüfung angegeben ist. Dann werde ich das Generieren der Versionsnummer nochmal anpassen.

**Comment by sw256** [comment]
Die Sache mit der Versionsnummer ist schon recht komisch. Es funktioniert ja auch dieses File nicht: [ccu-historian-2.7.0-4-noarch.zip](https://github.com/mdzio/ccu-historian/files/6672491/ccu-historian-2.7.0-4-noarch.zip) 
Dieses hat ja schon bei hotroot funktioniert gehabt.

**Comment by mdzio** [comment]
@sw256: Bitte mal die [Version 2.7.0-beta.4](https://github.com/mdzio/ccu-historian/releases/tag/2.7.0-beta.4) testen.

**Comment by mike-bee** [comment]
@mdzio: Funktioniert jetzt bei mir. Danks für den Fix.

**Comment by sw256** [comment]
@mdzio: Ja, hat sich bei mir nun auch installieren lassen.
DB kopieren hat auch geklappt und die alten Werte sind damit auch noch da. :)

Top, Danke. 👍
