### ISSUE TITLE
Anzahl der Backups auf 30 reduzieren

### ISSUE THREAD

**Issue by akula3** [mdzio/ccu-historian#293]
ist es möglich?
So, daß die Backups, die älter als 30 tage sind (beim täglichen Backup), automatisch gelöscht werden.
Oder nur die letzten X Backups (idealerweise über ccu-historian.config konfigurierbar) behalten, restliche automatisch löschen.

**Comment by krikk** [comment]
das mach ich mit einem shell script am linux system so:

```
# alle dateien die älter als 30 tage sind; grep auf pattern mit invertierung (-v) ; und alle gelisteten löschen
# pattern ist: alle dateien die am tag 01 erstellt werden behalten, rest löschen
rm -vf $(find /mnt/storage/ccu-historian/ -type f -mtime +30 |grep -e  '.*ccu-historian_db_backup_.*01\.gz' -v)
```

**Comment by akula3** [comment]
@krikk , danke für den Tipp!
Ich finde es schöner, wenn es vom Haus aus unterstüzt wird.

**Comment by alexhass** [comment]
Wie bringt man Historian dazu ein Backup zu erstellen? /mnt/storage/ccu-historian/ ist bei mir nicht vorhangen.

**Comment by alexhass** [comment]
Denke auch, dass dies ein Automatismus sein muss. 30 Backups sind denke ich auch viel zu viel. Denke es sollte auch möglich sein nur 1 mal pro Woche/Monat ein Backup zu machen und dann nur wenige aufzuheben. Ich hatte schon eine DB mit 4,5GB wenn ich das mit 30 multipliziere wird das auf einer normalen SD Karte schnell eng.

**Comment by alexhass** [comment]
Heute war meine SSD voll. Wäre echt super, wenn die Maintainer das Thema mal angehen könnten.

**Comment by mdzio** [comment]
Mit den neuen Feature #358 (Geplante Ausfürhung von Wartungsskripten) sollte die Anforderung nun umsetzbar sein. Ich werde dazu noch ein Skript veröffentlichen.

**Comment by alexhass** [comment]
Super. Vielen Dank!

**Comment by mdzio** [comment]
Hier ist schon das Skript. Um 2 Uhr werden unnötige Backup-Dateien entfernt. Das muss dann in die `ccu-historian.config` eingefügt werden. Dies ist erst ab V3.2 möglich.

```
database.tasks.cleanBackupFiles.enable=true
database.tasks.cleanBackupFiles.cron="0 0 2 * * ?"
database.tasks.cleanBackupFiles.script={
  // *** Konfiguration ***
  // Anzahl zu behaltener Backup-Dateien
  def keep = 30
  // *** Skript ***
  log.info "*** Alte Backup-Dateien loeschen V1.0.0 ***"
  log.info "Anzahl zu behaltener Backup-Dateien: $keep"
  log.info "Gefundene Backup-Dateien:"
  def backupFiles=[]
  new File(".").eachFileMatch(~/backup_.*\.zip/) { file ->
    backupFiles << file
    log.info file.name
  }
  backupFiles.sort({ it.name }).reverse().drop(keep).each { file ->
    log.info "Loesche $file.name"
    file.delete()    
  }
}
```
