### ISSUE TITLE
Handbuch zum Watchdog erweitern

### ISSUE THREAD

**Issue by MichaelN0815** [mdzio/ccu-historian#294]
In der Anleitung zur Einrichtugn des Watchdog
https://github.com/mdzio/ccu-historian/wiki#%C3%9Cberwachung
wird nicht erwähnt, das man auch einen weiteren Eintrag 
devices.device1.watchdogCycle=300000
setzen muss.

Vorschlag: 
1) Anleitung entsprechend erweitern
2) Default wert setzen

**Comment by mdzio** [comment]
Das Handbuch wurde auch angepasst.
