### ISSUE TITLE
Another versioning issue on Synology DSM7

### ISSUE THREAD

**Issue by mike-bee** [mdzio/ccu-historian#295]
Updating CCU-Historian from version 2.7.0 beta 4 (2.7.0.2.4) to final release 2.7.0 fails with the attached error message due to potential downgrade.
Synology's own beta versioning scheme is like 1.0.2-1007 (Synology Active Insight) or 1.1.0-0514 (Synology Hybrid Share Service) that might work better here...

Happy to support testing.

![CCU-Historian beta numbering issue](https://user-images.githubusercontent.com/30027622/134623088-571ef1a6-475c-4cb6-8477-164ac915f2dd.png)

**Comment by mdzio** [comment]
So `1.0.2-1007` is a beta version? And `1.0.2` is then a final version that can be installed over it?

**Comment by mike-bee** [comment]
Good question: I cannot tell (yet) - need to wait for the next final version update.
Though, a quick check of non-beta add-ons revealed that it rather seems to be the general Synology numbering scheme like "version-build", not only for betas. :-(
In that case I assume that only updates with a higher build number can be installed...

**Comment by mdzio** [comment]
I will give stable releases the numbering scheme `x.y.z.3.0`. This is higher than alpha- (`x.y.z.1.w`) and beta- (`x.y.z.2.w`) versions.

**Comment by mdzio** [comment]
Bitte einmal die neue [Release](https://github.com/mdzio/ccu-historian/releases) testen.

**Comment by mike-bee** [comment]
Hi Mathias
Seems to be a good idea. Update with latest release 2.7.0.3.0 worked like a charm.
Thanks
mike-bee
