### ISSUE TITLE
Kein Zugriff auf HMIP-Geräte

### ISSUE THREAD

**Issue by PumaBob1** [mdzio/ccu-historian#298]
Hallo,

ich habe CCU-Historian auf meiner CCU3 installiert. Auf der Web-Oberfläche werden mir lediglich meine CUxD-Schnittstellen angezeigt. Alle HomeMatic IP Geräte werden nicht angezeigt. Wo liegt der Fehler in meiner Konfiguration?

Vielen Dank vorab und viele Grüße

**Comment by mdzio** [comment]
Im Dateisystem der CCU3 findest Du die Log-Datei vom CCU-Historian: /var/log/ccu-historian-0.log 
Eventuell sind dort weitere Hinweise zu finden.

**Comment by mdzio** [comment]
Ich schließe mal den Beitrag. Bitte erneut kommentieren, wenn sich neue Erkenntnisse ergeben.
