### ISSUE TITLE
CCU-Historian auf DSM7.0 Fehler SEVERE |Exception: Failed to bind to 0.0.0.0/0.0.0.0:81

### ISSUE THREAD

**Issue by Stus2** [mdzio/ccu-historian#304]
Hallo Zusammen,
erstmal ein herzliches Dankeschön an dei Entwickler von CCU-Historian. Ich betreibe meinen Historian jetzt seit circa 4 Jahren auf einer Synology. Lange habe ich gezögert DSM7.0 zu installieren, es jetzt aber doch probiert. 
Ich bekomme leider beim Start des Historian folgende Fehlermeldung:

2021-11-09 09:36:50|SEVERE |Exception: Failed to bind to 0.0.0.0/0.0.0.0:81

Früher hatte ich dieses Problem wenn die Historain Adresse nicht angegeben wurde.
Meine geänderten Zeilen meiner Config sehen folgendermaßen aus:

webServer.port=81
webServer.historianAddress='192.168.2.6'
devices.historianAddress='192.168.2.6'

// Es muss im Folgenden mindestens eine Zentrale bzw. Gerät konfiguriert werden:

// Typ der Zentrale: CCU1 oder CCU2
devices.device1.type=CCU3
// IP-Adresse der Zentrale
devices.device1.address='192.168.2.10'

// Falls CUxD verwendet wird, die Kommentarzeichen (//) vor folgender Zeile entfernen:
devices.device1.plugin1.type=CUXD

Ich habe das gefühl das Java die Einstellung der Historian Adresse einfach ignoriert.
Ich bin für jede Unterstützung dankbar.
Gruß Stephan

**Comment by Stus2** [comment]
kurzes Update:
mit dem Webserver Port 8080 startet der Historian.
Ich lasse es jetzt so laufen. 
Es ist nur ärgerlich das alle gespeicherten Trend-Links jetzt im AIO Creator angepasst werden müssen.

**Comment by mdzio** [comment]
Anscheinend ist der Port 81 durch DSM 7 oder ein anderes Add-On bereits belegt.
