### ISSUE TITLE
Nach Update auf 2.7.2 keine Datenbank mehr gefunden

### ISSUE THREAD

**Issue by Wolf6660** [mdzio/ccu-historian#305]
Hi, 

hatte die Datenbank auf einem USB Stick liegen. Der USB Stick wird erkannt und die Datenbank ist aus noch vorhanden. Leider findet Historian die Datenbank nicht. Im Handbuch habe ich zwar gefunden das ich eine config bearbeiten soll aber unter /opt/ gibt es kein CCU-historian. 

an was kann das liegen?

Danke schon mal im Voraus für eure Unterstützung.

**Comment by mdzio** [comment]
Ich nehme an, dass Du den CCU-Historian als Add-On auf der CCU3 bzw. RM installiert hast. [Hier sind die zugehörigen Dateipfade zu finden.](https://github.com/mdzio/ccu-historian/wiki/CCU3-AddOn)

**Comment by Wolf6660** [comment]
Super danke für deine Antwort. Habe den Fehler gefunden es war nicht der falsche Pfad sondern der Stick war nur FAT32 formatiert und ab 4GB ist dann eben Schluss. Werde den Stick nun mit ext4 formatieren dann sollte es hoffentlich wieder funktionieren. 
Danke

**Comment by mdzio** [comment]
Siehe auch #273
