### ISSUE TITLE
config Konfiguration

### ISSUE THREAD

**Issue by CP-12** [mdzio/ccu-historian#306]
Hallo,

ich hatte auch das Problem, daß mit dem Upgrade auf Synology DSM7 Historian zunächst nicht mehr lief. Ich habe inzwischen die neueste version 2.7.1 installiert und erreiche Historian, das ich über die Packet Station auf der Synology installiert habe, auch problemlos.

Leider habe ich damals eine Neuinstallation gemacht, so daß die config Datei nicht richtig übernommen wurde.

Historian bekommt jetzt keine Datenpunkte mehr von der Raspimatic, die als Virtual machine auf der Synology läuft.

In der Datei /volume1/@appstore/ccu-historian-dsm/ccu-historian.config fand sich unter der IP Adresse der CCU die falsche. Diese habe ich mit VIM auf dem Mac versucht zu ändern. Dort steht jetzt auch die korrekte IP, aber wenn ich auf Historian gehe und auf "CCU" geht er weiter auf die vorherige ip Adresse.
Was mache ich falsch? Kann die config Datei auch woanders gespeichert sein, auf die der Historian zugreift?

Danke
CP

**Comment by mdzio** [comment]
Mit der Kommandozeilenoption __-config__ kann der Ort der Konfigurationsdatei angepasst werden. Eventuell zeigt diese auf eine andere Konfigurationsdatei.

Ansonsten bitte mal Deine Konfiguration zeigen.

**Comment by CP-12** [comment]
Hallo Mathias,

Ich bin echt zu dämlich. Ich bekomme es nicht hin. Ich hatte mir jetzt überlegt, daß ich statt der DSM Installation auf einen DockerContainer wechsele. 

Soweit so gut, aber auch den bekomme ich nicht zum laufen. Ich hatte schon mal einen funktionierend am laufen, aber das ist Jahre her und ich weiß nicht mal mehr, wie ich den historian über docker aufrufen muß. Ich nutze eine Synology und habe da Docker installiert. Eigentlich müsste doch alles richtig sein??






DAs müsste doch eigentlich so laufen? Allerdings sind in CCU-historan/config bzw. / database auch keine Daten in der Filestation einsehbar. Ist das korrekt, oder müssten hier vom Historian die Daten angelegt werden?
Ich weiß Du kannst keinen individuellen Support leisten, aber ich habe doch hier irgendwo einen Denkfehler?

Christian

**Comment by mdzio** [comment]
Bei Synology und Docker kann ich leider auch nicht weiterhelfen. Am besten fragst Du mal im [CCU-Historian-Forum](https://homematic-forum.de/forum/viewforum.php?f=38) nach Unterstützung.

**Comment by CP-12** [comment]
Hallo,

Habe meine Synology Installation wieder am laufen, warum die config Datei sich erst nicht verändern ließ bleibt mir aber weiter unklar. 
Bei Docker komme ich nicht weiter, aber es läuft ja erstmal weiter. Danke

C
