### ISSUE TITLE
Kein Chart im Trend auf Synology

### ISSUE THREAD

**Issue by johannesscherbaum** [mdzio/ccu-historian#308]
Hallo, ich habe den Historian 2.7.1 auf meiner Synology mit DSM 7 installiert. Leider zeigt mir der Historian kein Chart an, sobald ich einen Trend eines Datenpunkts anzeigen lassen will. Der CSV-Export beinhaltet aber alle Werte.

Hier steht immer folgendes:
![image](https://user-images.githubusercontent.com/5869027/143007002-306e802a-8382-4b35-bbe5-54e2f04ef338.png)

Fehlt da irgendwas auf der Synology?

**Comment by johannesscherbaum** [comment]
Hat sich erledigt, danke.

**Comment by mdzio** [comment]
Siehe auch [Kommentar bei Issue 261](https://github.com/mdzio/ccu-historian/issues/261#issuecomment-861230407)
