### ISSUE TITLE
Datenpunktliste bleibt leer

### ISSUE THREAD

**Issue by dpomt** [mdzio/ccu-historian#309]
Hallo Mathias,

habe aktuell das Problem, dass CCU Historian 2.7.0/2.7.1 keine Datenpunkte mehr anzeigt (Seite wird angezeigt, aber ohne Datenpunkte, die Seite lädt nie ganz zu Ende).

Vor ca. 2 Wochen ging es zuletzt. Hatte aber auch zu diesem Zeitpunkt immer wieder Probleme wie Fehler " Die Datenbank ist bereits geschlossen", "Java out of memory" oder lange Ladezeiten.
Meine Datenbank ist 33 GB groß - vermute dass es mit der Größe zusammenhängt. Wollte einige Datenpunkte mehr komprimieren und ggf. auch löschen, bekomme aber auch auf dieser Seite keine Datenpunkte angezeigt.

Im Log finde ich nichts besonders.
CCU Historian läuft auf einem Windows Server mit reichlich CPU und RAM.

Irgendeine Idee, wie ich wieder an die Datenpunktliste komme?

VG,
Dieter

**Comment by mdzio** [comment]
Bitte mal dem CCU-Historian etwas mehr RAM zur Verfügung stellen.
Beispiel für 4 GByte:
```
java -Xmx4g -jar ccu-historian.jar
```

Wenn die Datenbank dann wieder läuft, als erstes ein Backup mit `-createscript` erstellen und dann einmal mit `-compact` die Datenbank verkleinern.

**Comment by dpomt** [comment]
Hallo Mathias,

vielen Dank. Hat so funktioniert!

Hast mich gerettet, dachte schon die DB ist hinüber.

**Comment by mdzio** [comment]
Dann schließe ich mal den Eintrag hier.
