### ISSUE TITLE
Upgrade der internen Datenbank auf H2Database V2.0.202

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-historian#310]
Nach 2 Jahren ist endlich eine neue Release der eingebetteten Datenbank erschienen. Die neue Version verspricht eine bessere Performance und soll besser vor Datenbankkorruption schützen.

Allerdings wurde das Dateiformat geändert, sodass eine bestehende Datenbank nicht ohne Konvertieren weiter verwendet werden kann. Die Datenbank muss mit der **alten Version exportiert** und dann mit der **neuen Version importiert** werden!

**Comment by jokay** [comment]
> Allerdings wurde das Dateiformat geändert, sodass eine bestehende Datenbank nicht ohne Konvertieren weiter verwendet werden kann. Die Datenbank muss mit der **alten Version exportiert** und dann mit der **neuen Version importiert** werden!

Könnte interessant werden fürs Docker image 🧐

**Comment by mdzio** [comment]
Weitere Hinweise sind bei den [Release-Notes](https://github.com/mdzio/ccu-historian/releases/tag/3.0.0-beta.2) zu finden.

**Comment by jokay** [comment]
@mdzio also denkst du, dass der Benutzer den Export & Import selber machen soll und nicht das Docker image? :wink:

**Comment by mdzio** [comment]
Ja, ich denke schon. Über die Web-UI ist das auch relativ einfach. Ich hätte eine automatische Migration auch im CCU-Historian einbauen können, aber das war mir zu aufwändig.

**Comment by jokay** [comment]
Ok, dann mach ich das fürs Docker image auch so :+1:
