### ISSUE TITLE
Generierung des Trends als SVG

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-historian#323]
Bibliothek: JFreeSVG

**Comment by mdzio** [comment]
Durch Setzen der Konfigurationsoption `webServer.trendSvg=true` werden die Trend-Grafiken nicht mehr als PNG-Bilddatei sondern als SVG-Vektorgrafik generiert. 

Einschränkungen:
* Die Web-Browser-Kompatibilität ist noch nicht ganz gegeben. Der Edge-Browser stellt beispielweise eine leere Trend-Grafik überhaupt nicht dar.
* Bei großen Zeitbereichen mit vielen Zeitreiheneinträgen wird die Dateigröße der SVG-Vektorgrafik sehr hoch.

**Comment by MKaiser96** [comment]
Hallo,

ich habe auf meinem Synology NAS mit neuester DSM Version den CCU Historian 3.3.0 installiert. In der Config habe ich die Zeile webServer.trendSvg=true eingefügt. Leider wird mir bei der Trendgenerierung nach wie vor folgendes angezeigt.

Bitte warten: Die Trend-Darstellung wird generiert!

Das Problem tritt bei macOS und iOS jeweils mit Safari und unter Windows 11 mit Firefox auf.

Was ist hier das Problem? Ich möchte gerne die SVG Grafiken erzeugen, da ich nach jedem DSM Update die Java Schriftarten neu einfügen muss für die PNG Grafiken.
