### ISSUE TITLE
Kleine Verbesserungen für Handbuch, Default Konfig Datei

### ISSUE THREAD

**Issue by dieterbk** [mdzio/ccu-historian#325]
Bin völlig neu hier (auch wenn ich Homematic schon seit der erstenVersion benutze, vorher FS20)

Überall, insbesondere im Default Config File beim Type, wird nur zwischen CCU1 und CCU2 unterschieden. Habe einfach mal CCU3 probiert und es funktioniert. Sollte man vielleicht mal ergänzen (an einer Stelle im Handbuch gibt es schon CCU3)

**Comment by mdzio** [comment]
Im Handbuch wird die CCU3 an den relevanten Stellen bereits erwähnt.
Die Kommentare in der Konfigurationsdatei werden angepasst.
