### ISSUE TITLE
Kein Zugriff auf HM WIRED-Geräte

### ISSUE THREAD

**Issue by Uli1900** [mdzio/ccu-historian#326]
Hallo zusammen,

ich hab keinen Zugriff auf meine Homematik Wired Geräte - bzw. diese werden in der Datenpunkteliste nicht angezeigt.
ich habe nun mehrere Stunden mit der Analyse verbracht und komme einfach nicht weiter und brauche daher eure Hilfe.

Im CUXD Daemon sind die Variablen folgendermaßen gesetzt:

SUBSCRIBE-RF=1
SUBSCRIBE-WR=1

BIDCOS_RF, HMIP_RF und die SYSVAR sind vorhanden.

Selbst im sehr gut ausgearbeiteten Handbuch habe ich nichts gefunden, was mich weiterbringt (oder ich hab es aufgrund Unwissenheit überlesen).

**Was muss ich Wo** sonst noch machen damit die Geräte angezeigt werden?

Ich würde mich freuen, wenn mir jemand weiterhelfen könnte. Danke und vg

**Comment by mdzio** [comment]
Die Konfiguration des CUxD ist für den CCU-Historian irrelevant.

Ich nehme an, dass Du ein HomeMatic Wired RS485 LAN Gateway und CUxD in Betrieb hast. Dann musst Du folgende Konfigurationsoptionen in der _ccu-historian.config_ hinzufügen:
```
devices.device1.plugin1.type=CUXD
devices.device2.plugin1.type=HMWLGW
```

[Im Wiki ist es ab hier beschrieben.](https://github.com/mdzio/ccu-historian/wiki#konfiguration-der-angeschlossenen-ger%C3%A4te)

**Comment by Uli1900** [comment]
Hallo,

danke für die Antwort. Ja, ich habe das LAN Gateway, CUxD auf einer CCU3.

Wo muss ich die beiden Zeilen eintragen? 
Du hast es geschrieben: In der ccu-historian.config - aber wie kann ich auf die zugreifen? 
Kann ich das auf der Weboberfläche vom Historian machen - also in der Scriptumgebung?

**Comment by mdzio** [comment]
Hast Du den CCU-Historian als Add-On auf der CCU3 installiert?
Dann findest Du [hier die Speicherorte der Dateien](https://github.com/mdzio/ccu-historian/wiki/CCU3-AddOn#installation-als-add-on-auf-einer-ccu3-oder-raspberrymatic).
Du kannst die _ccu-historian.config_ mit einem SSH-Client (z.B. WinSCP) ändern. Zuvor muss der SSH-Zugriff auf der CCU aktiviert werden.

**Comment by Uli1900** [comment]
Ja, als addon auf der CCU 3. Ok ich probiers mal mit WinSCP. Danke

**Comment by Uli1900** [comment]
Zugriff hab ich nun auf die Datei welche nun so aussieht:

logSystem.fileLevel=Level.INFO
logSystem.fileName='/var/log/ccu-historian-%g.log'
logSystem.fileLimit=1000000
logSystem.fileCount=5
logSystem.binRpcLevel=Level.INFO
database.webEnable=true
database.webPort=8083
database.webAllowOthers=true
webServer.port=8082
webServer.historianAddress='192.168.178.30'
webServer.dir='/usr/local/addons/ccu-historian/ccu-historian/webapp'
webServer.logLevel=Level.INFO
**devices.device1.type=CCU2**
devices.device1.address='192.168.178.30'
devices.historianAddress='127.0.0.1'
**devices.device1.plugin1.type=CUXD
devices.device2.plugin2.type=HMWLGW**
database.dir='/media/usb0/ccu-historian'
historian.metaCycle=4*60*60*1000
historian.bufferTime=4*60*60*1000
base.scriptDir='/usr/local/addons/ccu-historian/ccu-historian'
webServer.menuLinks.link1.text='H2-HighChart'
webServer.menuLinks.link1.address='/custom/h2-highchart/H2-HighChart.gy'

Nun funktioniert Historian gar nicht mehr. Neustart gemacht aber es geht nichts mehr. 
Es steht auch noch CCU 2 bei mir drin (bin vor kurzem erst auf CCU 3 umgestiegen).
Was mach ich falsch?

**Comment by Uli1900** [comment]
Jetzt geht CCU Historian wieder...

Hab mal versucht aus CCU2 --> CCU 3 zu machen und beide oben genannten befehle auf device1 gesetzt.

Die Wired Komponenten werden trotzdem noch nicht angezeigt :-(

logSystem.fileLevel=Level.INFO
logSystem.fileName='/var/log/ccu-historian-%g.log'
logSystem.fileLimit=1000000
logSystem.fileCount=5
logSystem.binRpcLevel=Level.INFO
database.webEnable=true
database.webPort=8083
database.webAllowOthers=true
webServer.port=8082
webServer.historianAddress='192.168.178.30'
webServer.dir='/usr/local/addons/ccu-historian/ccu-historian/webapp'
webServer.logLevel=Level.INFO
d**evices.device1.type=CCU3**
devices.device1.address='192.168.178.30'
devices.historianAddress='127.0.0.1'
**devices.device1.plugin1.type=CUXD
devices.device1.plugin2.type=HMWLGW**
database.dir='/media/usb0/ccu-historian'
historian.metaCycle=4*60*60*1000
historian.bufferTime=4*60*60*1000
base.scriptDir='/usr/local/addons/ccu-historian/ccu-historian'
webServer.menuLinks.link1.text='H2-HighChart'
webServer.menuLinks.link1.address='/custom/h2-highchart/H2-HighChart.gy****

**Comment by mdzio** [comment]
Die Konfiguration von Dir sieht soweit gut aus. (Ich hatte in der 2. Konfigurationszeile einen Fehler drin. Den habe ich in meinem Beitrag oben korrigiert.)
Bitte einmal ein Wired-Gerät schalten. Erst bei der ersten Änderung übernimmt der CCU-Historian auch den Datenpunkt in seine Datenbank.

**Comment by Uli1900** [comment]
Datenpunkte vom wired sind jetzt da - sieht es gut aus! Danke Dir Mathias für deinen schnellen Support!
