### ISSUE TITLE
Geänderte IP-Adresse der CCU wird nicht automatisch in der Konfiguration aktualisiert

### ISSUE THREAD

**Issue by alexhass** [mdzio/ccu-historian#329]
Ich habe heute vom Januar Update auf das Februar Update 3.61.7.20220226 gewechselt.

Jetzt ist der CCU-Historian nicht mehr erreichbar. Auch ein Neustart hat nicht geholfen.

Der RaspMatic watchdog sagt "CCU-Historian Web-Seiten nicht erreichbar".

**Comment by alexhass** [comment]
Historian ist version 2.8.3

**Comment by mdzio** [comment]
Da hilft eventuell die Erstellung eines Fehlerprotokolls weiter. Die nötigen Konfigurationsoptionen sind [hier](https://github.com/mdzio/ccu-historian/wiki#erstellung-eines-fehlerprotokolls) beschrieben. Der Ort der Konfigurationsdatei bei einer Add-On-Installation ist [hier](https://github.com/mdzio/ccu-historian/wiki/CCU3-AddOn#allgemeines) beschrieben. Und wie die Konfigurationsdatei editiert werden kann, ist [hier](https://github.com/mdzio/ccu-jack/wiki/CCU-Dateitransfer-und-Konsolenzugriff) beschrieben.

**Comment by Baxxy13** [comment]
Hat sich vielleicht die IP-Adresse der Zentrale geändert?

Die aktuelle IP-Adresse wird ja nur bei der Installation (bzw. dem anschließenden Reboot) in die `ccu-historian.config` eingetragen. Ändert die sich irgendwann muss man sie händisch in der ccu-historian.config anpassen.

**Comment by alexhass** [comment]
> Hat sich vielleicht die IP-Adresse der Zentrale geändert?

Verdammt. Du hast recht. Ich habe vor ein paar Wochen eine feste Zuweisung vorgenommen die CCU aber nicht neu gestartet und das deshalb keine Fehler gesehen. Das nervt... kann man das nicht irgendwie automatisierten, dass der Historian solche DHCP Änderungen einfach mitbekommt oder localhost nehmen? 

Ich frage mich auch gerade - wie eine IPv4 Adresse mit IPv6 funktionieren soll... das ist schon vorprogrammiert, dass es da Probleme gibt. Wir sind in 2022... da muss man doch IPv4 und IPv6 supporten. Spätestens wenn der Glasfaseranschluss der Deutschen Glasfaser in 3 Monaten kommt - gibt es kein IPv4 mehr und dann muss auch alles über IPv6 erreichbar sein. Der historian kann das aber meines Wissens nicht. Fragen über Fragen... :-)

**Comment by alexhass** [comment]
`webServer.historianAddress='' `

Darf nicht leer sein, obwohl das in der Dokumentation drin steht. Blöd gefragt - die CCU3 Hardware und was die kann - dürfte doch eine zu erwartende Hardwareplatform sein. Diese hat auch nur ein "eth0"... also nicht mehrere Schnittstellen. Man weiß also woran man binden muss. Warum wird das eth0 nicht automatisch erkannt?

**Comment by alexhass** [comment]
Warum kann der java prozess nicht by default an alle Interfaces gebunden werden bzw. das macht die Software ja - aber warum braucht sie dazu die IP Adresse von eth0 in der Konfigurationsdatei?

**Comment by mdzio** [comment]
Die Optionen `devices.historianAddress` und `webServer.historianAddress` werden benötigt, damit der Web-Browser aus der CCU-Systemsteuerung auf die Web-UI des CCU-Historians weitergeleitet werden kann oder auch von der CCU-Historian-Menüleiste zur CCU oder zur Datenbankoberfläche.

Diese Konfigurationsoptionen könnten aber automatisch beim Historian-Start aktualisiert werden.

**Comment by mdzio** [comment]
Bezüglich IPv6: Im CCU-Historian sollte nichts eingebaut sein, das die Verwendung von IPv6 verhindert. Getestet habe ich es nicht. Allerdings wird die Adresse in `devices.historianAddress` an die Schnittstellenprozesse der CCU weitergegeben. Insbesondere bei den alten Prozessen BidCos-RF und BidCos-Wired bezweifele ich aber ein wenig, dass sie IPv6 unterstützen.

**Comment by Baxxy13** [comment]
Ich hatte bei mir das rc.d-Script rudimentär erweitert so das bei jedem Reboot die aktuelle IP-Adresse für...
`webServer.historianAddress`
und
`devices.device1.address`
in der `ccu-historian.config` aktualisiert wird. 
Da hält sich die "Schreiblast" auf der SD-Karte in Grenzen da man ja normalerweise nicht so oft rebootet.
Könnte man noch verfeinern indem man die IP-Adresse aus der .config mit der aktuellen IP-Adresse vergleicht und nur bei Änderung entsprechend neu schreibt.

**Comment by alexhass** [comment]
In der Doku steht man könnte die Configoption auch leer lassen und dann würde ein automatismus greifen. Der soll nur dann nicht funktionieren, wenn man mehrere Interfaces hat (was die ccu3 aber nicht hat). Leider funtioniert dieser automatismus aber nicht. Weisst du warum?

**Comment by mdzio** [comment]
Für die Automatik darf die Option entweder nicht in der Konfigurationsdatei auftauchen, muss auskommentiert sein oder muss wie folgt gesetzt werden: `devices.historianAddress=null` 
Für die Option `webServer.historianAddress` gibt es die Automatik noch nicht. Sie wird aber in der nächsten Veröffentlichung enthalten sein.

**Comment by Baxxy13** [comment]
Klappt das dann auch wenn die Zentrale mehrere IP Adressen hat?
RaspberryMatic mit aktiviertem Tailscale-VPN hat ja z.B. 2 IP-Adressen.

**Comment by mdzio** [comment]
Es sollte dann die IP-Adresse detektiert werden, die bei der Auflösung des Host-Namens zurückgegeben wird, wie z.B. auch bei `ping homematic-raspi.fritz.box`.

**Comment by alexhass** [comment]
> Für die Automatik darf die Option entweder nicht in der Konfigurationsdatei auftauchen, muss auskommentiert sein oder muss wie folgt gesetzt werden: `devices.historianAddress=null`
> Für die Option `webServer.historianAddress` gibt es die Automatik noch nicht. Sie wird aber in der nächsten Veröffentlichung enthalten sein.

Das steht in der Dokumentation aber vollkommen anders. „ Leer: Die Adresse wird automatisch ermittelt.“ und es werden zeei Anführungszeichen aufgeführt. Da komme ich nie auf die Idee, dass ich den ganzen Konfigurationsparamwter entfernen muss oder auf null einstellen soll.

Super, dass du das so schnell ändern kannst. Ich denke der default sollte so gewählt sein, dass es immer funktioniert und für Ausnahmefälle kann man es dann eintragen.

**Comment by alexhass** [comment]
> Klappt das dann auch wenn die Zentrale mehrere IP Adressen hat?
> RaspberryMatic mit aktiviertem Tailscale-VPN hat ja z.B. 2 IP-Adressen.

Hast du eine Fritzbox? Dann mach mal die labor drauf und nurz wireguard… so was feines… 😊
