### ISSUE TITLE
Synology DSM 216j Performance bricht ein bei Zwischenspeicherung

### ISSUE THREAD

**Issue by DidiTheE** [mdzio/ccu-historian#331]
Ich verwende die V3.0.0-beta.2 Version auf einem DSM216j NAS von Synology und das System läuft soweit stabil.
Um die Schreibzugriffe auf die Festplatten (etwas) zu bündeln, habe ich mit dem Zwischenspeichern experimentiert. 
Aber selbst bei lediglich 1 Minute Zwischenspeicher bricht die Performance des DSM216j komplett ein.

Zugegeben, der DSM216j ist kein Leistungswunder und mit 512MB Arbeitsspeicher auch nur dürftig bestückt.
Gibt es systemseitig Mindestanforderungen um Zwischenspeicherung zu nutzen?

**Comment by mdzio** [comment]
512 MB RAM sind zwar wenig, aber eine Zwischenspeicherung für 1 Minute sollte keine Auswirkungen auf die Performance haben. Mindestanforderungen gibt es nicht. Bei einer Installation als Add-On auf der CCU ist die Zwischenspeicherung sogar auf 4 Stunden eingestellt.

**Comment by mdzio** [comment]
Der Eintrag ist längere Zeit ohne neue Beiträge. Ich schließe ihn daher. Bei Bedarf kann er wieder geöffnet werden.
