### ISSUE TITLE
SVG-Trends: Bei Sonderzeichen wird der Trend nicht gezeichnet

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-historian#341]
Wenn z.B. ein ß im Datenpunktnamen enthalten ist, so wird der Trend nicht angezeigt.

**Comment by FUEL4EP** [comment]
Danke für den Eintrag. M.E. tritt der Fehler auch bei 'Grad Celsius' als Einheit der Achsenbeschriftung auf.

**Comment by FUEL4EP** [comment]
Siehe auch

https://homematic-forum.de/forum/viewtopic.php?f=38&t=73679&start=40#p716591

**Comment by FUEL4EP** [comment]
Thanks for your fix. 

I tried your patch. It works :-) Now SVG trend charts are correctly drawn on an iPAD or Google Chrome browser.
