### ISSUE TITLE
Grafana + CCU Historian auf CCU3/Raspberrymatic - Werte kommen verzögert

### ISSUE THREAD

**Issue by freaky-m0** [mdzio/ccu-historian#342]
Ich nutze CCU Historian (3.0.1) auf meiner RaspberryMatic und habe das ganze jetzt in Grafana visualisiert. Aufgrund der (Vor-)Einstellungen für die Werte `historian.metaCycle=4*60*60*1000` & `historian.bufferTime=4*60*60*1000,` kommen die Werte in Grafana aber nur verzögert an. 

Da ich davon ausgehe, dass das mit Hintergedanken so eingestellt wurde (USB Stick Lebenszeit), würde ich die Zyklen auch gerne so lassen. Allerdings wäre es super es hinzubekommen, dass bei einer Abfrage aus Grafana per PostgresSQL Schnittstelle dieser Puffer in die Datenbank geschrieben wird. Wenn ich vorher in CCU-Historian einen Trend abrufe, werden die Messungen ja auch in die Datenbank übernommen.

Ist das vielleicht jetzt schon möglich oder müsste hier tatsächlich eine Änderung programmiert werden?

Vielen Dank im Voraus für Info & Hilfe! :D

**Comment by mdzio** [comment]
Von den Zugriffen über die PostgreSQL-Schnittstelle bekommt der CCU-Historian nichts mit und kann daher auch gepufferte Werte vorab nicht in die Datenbank schreiben.

Als Lösung bleibt, die beiden genannten Konfigurationsoptionen anzupassen. Damit die Lebenszeit eines USB-Sticks nicht verkürzt wird, sollte eine USB-SSD für die Datenbank verwendet werden.
