### ISSUE TITLE
SQL-Abfragen funktionieren seit Umstellung auf V 3.0x nicht mehr (Feld VALUE)

### ISSUE THREAD

**Issue by bs0001** [mdzio/ccu-historian#345]
Hallo Mathias,

nachdem ich letzten Monat den Wechsel von V2.9 auf V3.01 und mittlerweile auf V3.02 vollzogen habe und soweit auch alles gut aussieht (Datenpunkt-IDs sind auch alle durch Export/Import erhalten geblieben) habe ich nun das Problem, dass ich den Monatsabschluss meiner Aprilwerte vornehmen wollte und einige Korrekturen an Werten vornehmen wollte.

Scheinbar funktionieren unter V3.0x nun die SQL-Anweisungen etwas anders.

Beispiele:
V2.9: SELECT * FROM D_SYSVAR_19147_VALUE WHERE VALUE > '60' AND TS >= '2022-02-08 00:00:00' AND TS <= '2022-05-06 00:00:00'
V3.0: SELECT * FROM D_SYSVAR_19147_VALUE WHERE "VALUE" > '60' AND TS >= '2022-02-08 00:00:00' AND TS <= '2022-05-06 00:00:00'

V2.9: SELECT Avg( VALUE) AS DURCHSCHNITTSTEMPERATUR, MIN( VALUE) AS TEMPERATUR_Min, MAX( VALUE) AS TEMPERATUR_Max
FROM   D_HMIP_RF_00XXXXAXXCXXXX_1_ACTUAL_TEMPERATURE WHERE TS >= '2022-04-01 00:00:00' AND TS <= '2022-04-30 23:59:59'
V3.0: SELECT Avg( "VALUE") AS DURCHSCHNITTSTEMPERATUR, MIN( "VALUE") AS TEMPERATUR_Min, MAX( "VALUE") AS TEMPERATUR_Max
FROM   D_HMIP_RF_00XXXXAXXCXXXX_1_ACTUAL_TEMPERATURE WHERE TS >= '2022-04-01 00:00:00' AND TS <= '2022-04-30 23:59:59'

Falls ich das bisherige SQL laufen lasse (VALUE ohne Anführungszeichen), dann erhalte ich folgende Fehlermeldung:
Syntax Fehler in SQL Befehl "SELECT Avg( [*]VALUE) AS DURCHSCHNITTSTEMPERATUR, MIN( VALUE) AS TEMPERATUR_Min, MAX( VALUE) AS TEMPERATUR_Max\000d\000aFROM   D_HMIP_RF_00XXXXAXXCXXXX_1_ACTUAL_TEMPERATURE WHERE TS >= '2022-04-01 00:00:00' AND TS <= '2022-04-30 23:59:59'"; erwartet "DISTINCT, ALL, INTERSECTS, NOT, EXISTS, UNIQUE, INTERSECTS"
Syntax error in SQL statement "SELECT Avg( [*]VALUE) AS DURCHSCHNITTSTEMPERATUR, MIN( VALUE) AS TEMPERATUR_Min, MAX( VALUE) AS TEMPERATUR_Max\000d\000aFROM   D_HMIP_RF_00XXXXAXXCXXXX_1_ACTUAL_TEMPERATURE WHERE TS >= '2022-04-01 00:00:00' AND TS <= '2022-04-30 23:59:59'"; expected "DISTINCT, ALL, INTERSECTS, NOT, EXISTS, UNIQUE, INTERSECTS"; SQL statement:
SELECT Avg( VALUE) AS DURCHSCHNITTSTEMPERATUR, MIN( VALUE) AS TEMPERATUR_Min, MAX( VALUE) AS TEMPERATUR_Max
FROM   D_HMIP_RF_00XXXXAXXCXXXX_1_ACTUAL_TEMPERATURE WHERE TS >= '2022-04-01 00:00:00' AND TS <= '2022-04-30 23:59:59' [42001-212] 42001/42001 (Hilfe)

**1. Umstellung auf bisherige Nomenklatur**
Lässt sich die Methodik irgendwie nochmal auf die alte SQL-Nomenklatur umstellen? Hintergrund ist, dass ich meine SQLs in Excel vorbereite und hierbei es nicht funktioniert, dass ich im Rahmen einer Verkettung nur ein Anführungszeichen in der Textverkettung gesetzt bekomme (auch wenn ich 3 """ hintereinander setze). Demnach müsste ich jedes SQL erst mal noch bereinigen, bevor ich es auf der CCU-H DB-Oberfläche ausführen kann.

**2. INSERT-Befehle**
Mein bisheriger Insert-Befehl sieht wie folgt aus (ein Beispiel, ich habe zahlreiche):
INSERT INTO D_SYSVAR_41178_VALUE (TS, VALUE, STATE) VALUES ('2022-03-01 00:00:00', '3', '2');
Wie müsste der zukünftig aussehen, dass er akzeptiert wird?

**3. UPDATE-Befehle**
Dieser sah bisher so aus:
UPDATE D_SYSVAR_63193_VALUE SET VALUE = '-24354' WHERE TS >= '2021-01-01 00:00:00' AND TS <= '2021-01-01 00:00:00'
Vermutlich müsste es geändert werden, dass VALUE in Anführungszeichen steht, oder?

**4. Update Wiki-Beispiele**
Wäre prima, wenn Du im [Wiki](https://github.com/mdzio/ccu-historian/wiki#beispiele-f%C3%BCr-sql-anfragen) solche Beispiele noch mit aufnehmen könntest.

Ansonsten TOP Job!!! Weiter so!

VG
Bernd

**Comment by mdzio** [comment]
Siehe auch #320.

Die Spaltenbezeichnung `VALUE` ist nun ein reservierter Bezeichner. In SQL-Ausdrücken muss er nun in doppelten Hochkommas  eingeschlossen werden: `"VALUE"`

zu 1.) 
Auf die bisherige Angabe der VALUE-Spalte ohne `"` kann nicht wieder umgestellt werden. In Excel muss es aber möglich sein, auch `"` in Zeichenketten verarbeiten zu können: z.B. ist CHAR(34) ein `"`, oder `""""` (4 hintereinander) müssten auch gehen.

zu 2.)
INSERT INTO D_SYSVAR_41178_VALUE (TS, "VALUE", STATE) VALUES ('2022-03-01 00:00:00', '3', '2');

zu 3.)
UPDATE D_SYSVAR_63193_VALUE SET "VALUE" = '-24354' WHERE TS >= '2021-01-01 00:00:00' AND TS <= '2021-01-01 00:00:00'

zu 4.)
Das Wiki werde ich ergänzen.
