### ISSUE TITLE
Featurewunsch Konfigurationsparamteter "unsichtbar"

### ISSUE THREAD

**Issue by joesch2** [mdzio/ccu-historian#346]
Der Parameter "historian.defaultDisabled=true" erleicheichtert die Inbetriebnahme dahingehend, dass die Menge der aufgezeichneten Datenpunkte insbesondere am Anfang (und für Anfänger/Einsteiger ;-) ) übersichtlich bleibt. Ich könnte mir vorstellen, dass die Datenpunkte damit nicht nur inaktiv gesetzt werden sondern zudem auch zunächst das Attribut "versteckt" bekommen. Die Seite Datenpunktliste wäre am Anfang damit noch übersichtlicher. Oder ein getrennter Konfigurationsparameter "historian.defaultInvisible=true" ;-)

Vielen Dank für das tolle Projekt :-)

VG, Jörg

**Comment by Baxxy13** [comment]
Gibt's doch schon längst. 
Einfach mal im Wiki stöbern. [Liste-aller-optionen](https://github.com/mdzio/ccu-historian/wiki#liste-aller-optionen)
`historian.defaultHidden=true`
