### ISSUE TITLE
Homematic IP Touch-Sensor HmIP-STI kanal 1 & 2 werden nicht angezeigt

### ISSUE THREAD

**Issue by AndynordSee** [mdzio/ccu-historian#347]
Guten Morgen zusammen, 

beim Homematic IP Touch-Sensor "HmIP-STI" (Geräte Firmware 1.0.0 ) wird nur der Kanal 0 angezeigt unter "Datenpunkliste". 

Kanal 1 & 2 werde nicht angezeigt. 

Die Basisstation ist eine CCU3 "3.63.9" verwendet. 

Könnt ihr das Issue nachvollziehen ?

**Comment by mdzio** [comment]
Sind denn die Kanäle verknüpft, z.B. mit einem Programm?

**Comment by AndynordSee** [comment]
Moin ne der STI ist nur angelernt

**Comment by mdzio** [comment]
Damit Nachrichten von HmIP-Tastern bei der CCU ankommen, müssen diese in einem Programm verwendet werden. Ansonsten spart sich der Taster anscheinend das Senden.

Du müsstest also ein Programm anlegen, dass durch die Tastendrücke angestoßen wird. Der Dann-Zweig kann völlig leer sein.
