### ISSUE TITLE
PostgreSQL Abfragen

### ISSUE THREAD

**Issue by Franz6405** [mdzio/ccu-historian#349]
In Grafana mache ich diverse Auswertungen der Daten von RaspberryMatic.
Seit ich von der Historian Version 2.8 auf 3.02 gewechselt habe werden bei einigen Abfragen Fehlermeldungen ausgegeben.
- Es muss bei Werteabfragen neu Value immer gross und in Anführungszeichen geschrieben werden => "VALUE". Bei den anderen Abfragen ts und State ist dies nicht der Fall, diese Abfragen können ohne "" geschrieben werden.
- Einige Befehle, welche in 2.8 noch funktionierten gehen nicht mehr: z.B.
TOP, 
extract(epoch from ts),
Round(3600 * ("VALUE" - LAG("VALUE", 1) OVER  (ORDER BY ts))/ DATEDIFF(ss, LAG(ts, 1) OVER (ORDER BY ts), ts),1) AS "Regenintensität"

Wurden nicht alle PostgreeSQL-Befehle integriert?
Werden diese in den kommenden Versionen noch ergänzt?

**Comment by mdzio** [comment]
In der V3 wurde die interne Datenbankmaschine H2Database aktualisiert. VALUE ist nun ein reserviertes Wort geworden und muss leider in " gesetzt werden.

TOP wird nicht mehr unterstützt. Stattdessen muss FETCH FIRST ROW ONLY an den SQL-Ausdruck angehängt werden.

[Der vollständige Syntax von H2Database ist hier zu finden.](https://www.h2database.com/html/commands.html)

Es werden nicht alle PostgreSQL-Befehle unterstützt, da es sich nur um eine Emulation handelt.

Die Befehle werden nicht in einer kommenden Version ergänzt, da dies komplett von der eingebetteten Datenbank abhängt.
