### ISSUE TITLE
CCU-Historian DB auf Synology ausführen (nur zu Analysezwecke, nicht zur Aufzeichnung von Datenpunkte)

### ISSUE THREAD

**Issue by bs0001** [mdzio/ccu-historian#350]
Hallo Mathias,

ich bräuchte etwas Anlaufhilfe für den CCU-Historian auf einer Sysnology unter DSM 6.2.4-25556 Update 6 mit Paket Java8 (Version 8.0.275-0021).

Bei mir läuft der CCU-Historian auf dem Raspi 3B+ mit 1GB RAM sowie CCU3 ... Von daher ist das Teil maßlos überlastet, wenn ich meinen Datenbestand analysieren möchte. Daher ziehe ich mir von Zeit zu Zeit eine Kopie meines CCU-Historian-Verzeichnisses (alles was unter /opt/ccu-historian liegt. Eine Config-Datei habe ich mir speziell hierfür angelegt, in dem dann viele Dinge auskommentiert sind (z.B. devices.device1.address=192...). Ich will die DB ja nicht weiter befüllen sondern diese nur starten, um den Datenbestand auf einer performanteren Umgebung analysieren zu können.
Auf meinem Windows-PC klappt das gut. Hab mir dafür eine Batch-Datei angelegt, welche zuvor die config-Datei so umkopiert, dass die mit den vielen Auskommentierungen verwendet wird.

Nun hätte ich aber gerne das so gelöst, dass ich bei Bedarf den CCU-Historian auf der Synology NAS starte (wenn ich mal Muße hab und was analysieren möchte) und diesen auch wieder stoppe, wenn ich fertig bin.
Von daher war meine Idee, weder ein Paket noch einen Docker-Container für CCU-Historian auf der Synology anzulegen sondern einfach nur in einem Verzeichnis die Daten abzulegen und dann bei Bedarf per Synology-Aufgabe die CCU-Historian-DB starte bzw. stoppe.

Wie muss ich das genau machen?
Ich mach mal ein Beispiel, wo die CCU-Historian-DB liegt als auch Java8.
Per Putty oder WinSCP kann ich mich auf der NAS auch anmelden.

Historian-DB: /volume1/backup/Devices/Raspberry/Pi3BP_HM_PRD/opt/latest/
Java8: /volume1/@appstore/Java8/j2sdk-image/bin
Bei dem Java-Verzeichnis bin ich mir total unsicher, ob das das korrekte ist. Scheint aber wohl zu sein.
![image](https://user-images.githubusercontent.com/46260437/172893387-f62c978a-0c57-40c6-b7a3-a7a4a2ad233a.png)

![image](https://user-images.githubusercontent.com/46260437/172893633-ade722b4-af97-4e28-9103-943a1b31d5b6.png)

Auf der NAS habe ich mir eine Aufgabe mit Skript angelegt:
Aufrufkommando: bash /volume1/backup/Devices/Raspberry/Pi3BP_HM_PRD/opt/latest/ccu-historian-start-syno.sh
![image](https://user-images.githubusercontent.com/46260437/172893794-e72756b4-419a-4493-a7ab-5d08b4b8be45.png)
```
########################################################################################
Dateiinhalt: **ccu-historian-start-syno.sh**
########################################################################################
Echo "ccu-historian starten"
sudo bash /volume1/backup/Devices/Raspberry/Pi3BP_HM_PRD/opt/latest/ccuh_syno start
########################################################################################
```

```
########################################################################################
Dateiinhalt: **ccuh_syno**
########################################################################################
#!/bin/bash
### BEGIN INIT INFO
# Provides:          ccu-historian
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop::    $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts ccu-historian
# Description:       starts ccu-historian
### END INIT INFO
(( EUID )) && echo .You need to have root priviliges.. && exit 1
PIDF=/volume1/backup/Devices/Raspberry/Pi3BP_HM_PRD/opt/latest/ccu-historian/ccu-historian.pid
CONFF=/volume1/backup/Devices/Raspberry/Pi3BP_HM_PRD/opt/latest/ccu-historian/ccu-historian.config
JAVACMD=/volume1/@appstore/Java8/j2sdk-image/bin/java
#JAVACMD=/usr/bin/java
CCUCMD=/volume1/backup/Devices/Raspberry/Pi3BP_HM_PRD/opt/latest/ccu-historian/ccu-historian.jar
RETVAL=0

start() {
            echo -n "Starting ccu-historian"
            start-stop-daemon --start --pidfile $PIDF --make-pidfile --background  --exec $JAVACMD -- -jar $CCUCMD -config $CONFF
            RETVAL=$?
}

stop() {
            echo -n "Stopping ccu-historian"
            start-stop-daemon --quiet --stop --pidfile $PIDF
            RETVAL=$?
}
case "$1" in
    start)
      start
  ;;
    stop)
      stop
  ;;
    restart)
      stop
      start
  ;;
    *)
      echo "Usage: ccu-historian {start|stop|restart}"
      exit 1
  ;;
esac
exit $RETVAL
########################################################################################
```

**Ergebnis der NAS-Aufgabe:**
/volume1/backup/Devices/Raspberry/Pi3BP_HM_PRD/opt/latest/ccu-historian-start-syno.sh: line 1: Echo: command not found
Starting ccu-historian/volume1/backup/Devices/Raspberry/Pi3BP_HM_PRD/opt/latest/ccuh_syno: line 21: start-stop-daemon: command not found

Wie genau müsste das nun laufen, damit ich den CCU-Historian gestartet bekomme?

Ich hoffe Du kannst mir hier etwas weiterhelfen und hoffe, dass ich mit dem Vorhaben nicht ganz auf dem Holzweg bin.
Die Hilfe (Wiki) hab ich mir auch schon angesehen. Diese hat mir für diesen Zweck leider nicht weiter geholfen.

Viele Grüße
Bernd

**Comment by mdzio** [comment]
Das Kommando `start-stop-daemon` gibt es anscheinend in der Synology-Umgebung nicht. Leider kann ich auch nicht mehr dazu sagen, da ich selber kein Synology-NAS besitze. 

Vielleicht kann hier jemand anderes helfen.

**Comment by mdzio** [comment]
Der Eintrag ist längere Zeit ohne neue Beiträge. Ich schließe ihn daher, bei Bedarf kann er wieder geöffnet werden.
