### ISSUE TITLE
Unsupported database file version or invalid file header in file "/media/usb1/ccu-historian/history.mv.db" [90048-214]

### ISSUE THREAD

**Issue by Uli1900** [mdzio/ccu-historian#363]
Hallo, 

ich habe vergessen vor dem Versionswechsel von V2 auf V3 die Datenbank zu sichern.

Nun bekomme ich folgende Fehlermedung:
Unsupported database file version or invalid file header in file "/media/usb1/ccu-historian/history.mv.db" [90048-214]

Wer kann mir helfen - Was kann ich tun?

Danke und vg

**Comment by mdzio** [comment]
Du kannst einfach wieder die Version 2.9.0 darüber installieren und mit dieser, [wie beschrieben](https://github.com/mdzio/ccu-historian/wiki/Migration-V3), die Migration starten.
