### ISSUE TITLE
 /historian/index.gy keine Reaktion mehr - Java Timeout

### ISSUE THREAD

**Issue by t-rood** [mdzio/ccu-historian#364]
Ich nutzte die ccuhistorian 3.3.0 im xjokay/docker-Container. Der Start war immer schon brutal langsam (>10 Min), wenn die DB aufgebaut wurde (trotz Flash-Cache im NAS), bis das der Webserver dann mal gestartet wurde. Seit dem letzten Container-Start liefert /historian/index.gy jetzt gar keinen Inhalt mehr.

Im Log steht dann
2022-10-15 16:40:24|WARNING|handleException /external/bootstrap/css/bootstrap.css java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms

Meine history.mv ist 6GB groß.

Was kann ich tun?

**Comment by t-rood** [comment]
ach ja: nach VIELEN Retries kommen dann irgendwann auch mal Daten

**Comment by mdzio** [comment]
Hast Du Mal mit der Kommandozeilenmotion -compact die Datenbank optimiert?

**Comment by t-rood** [comment]
Wie kann ich das denn in einem laufenden docker-context realisieren? Ich hab dazu keine startparameter für den container gefunden und die db ist ja ‚frisch‘ von anfang diesen jahren gewachsen, so wie sie jetzt ist. Seitdem haben sich keine ccu-devices verändert.

Ich dachte, der initiale backup/restore, der bei jedem start durchgeführt wird, sorgt für eine automatische bereinigung?

**Comment by mdzio** [comment]
Mit der Umgebungsvariable CONFIG_MAINTENANCE vom Docker-Image wird ein `-compact` angestoßen.

6 GB seit Anfang diesen Jahres sind schon sehr viele Daten. Du solltest nicht benötigte Datenpunkte deaktivieren und die [Datenvorverarbeitung](https://github.com/mdzio/ccu-historian/wiki#vorverarbeitung-aller-wertaktualisierungen) verwenden.

Unter _Werkzeuge_ → _Datenpunktkonfiguration_ wird auch in der Spalte _Anz. Einträge_ die Gesamtanzahl der Einträge und die Einträge in den letzten 24h angezeigt. Dann kann gezielt optimiert werden.

**Comment by t-rood** [comment]
ah! gut, das werde ich mir wohl mal genauer ansehen müssen - da steckt auf jeden Fall 'ne Menge Arbeit drin. Danke!

**Comment by t-rood** [comment]
sorry, ich noch mal. Ich habe die CONFIG_MAINTENANCE durchgeführt und vorher massiv Datenpunkte deaktiviert und die Vorverarbeitung entsprechend umfangreich eingestellt.

Im Log sehe ich nun dieses:

2022-11-23 22:04:44|INFO   |Summary: 14311392 entries from 18354083 dropped (77.973885 %); 1238.607 seconds
2022-11-23 22:04:44|INFO   |Recalculation completed
2022-11-23 22:04:48|INFO   |Running database maintenance 'compact' ...
2022-11-23 22:04:51|INFO   |CCU-Historian V3.3.0
2022-11-23 22:04:51|INFO   |(C)MDZ (info@ccu-historian.de)
2022-11-23 22:04:53|INFO   |Starting base services
2022-11-23 22:04:54|INFO   |Starting compaction of database
2022-11-23 22:04:54|INFO   |Dumping database to temp.sql
2022-11-23 22:12:13|INFO   |Restoring database from temp.sql
2022-11-23 22:44:26|INFO   |Compaction of database completed

aber die resultierende DB ist von 8,1GB nur auf 6,2GB geschrumpft. Wie kann das sein, wenn doch 78% Daten rausoptimiert wurden?

**Comment by mdzio** [comment]
Jeder Datenpunkt belegt immer einen Mindestgröße auf dem Datenträger für Verwaltungsstrukturen. Ich hätte auch gedacht, dass mehr Speicher freigegeben wird. Die Datenbank sollte jetzt aber schneller sein.

**Comment by t-rood** [comment]
ja, die deutlich verbesserte Geschwindigkeit kann ich bestätigen. Die Startzeit von 40 Minuten (siehe Log) ist aber dennoch ganz schön unterirdisch. Die CPU scheint da mächtig überfordert von dieser speziellen Operation, obwohl bspw. Grafana und ElasticSearch recht zügig laufen.

**Comment by mdzio** [comment]
CONFIG_MAINTENANCE musst Du natürlich wieder abschalten.

**Comment by t-rood** [comment]
Steht wieder auf "false". und vorher hatte ich diesen Wert überhaupt nicht im compose-file drin. Dennoch gilt in beiden Fällen, dass der Container beim Starten **immer** diesen Umweg über den export/compact macht. Habe den Container auch neu deployed. ich hatte dies so bislang gar nicht auf dem Schirm, dass da wohl noch zusätzlich was im Argen zu sein scheint?

**Comment by mdzio** [comment]
Hast Du eventuell noch CONFIG_KEEP_MONTHS gesetzt. Dann wird auch ein recalc und compact gemacht.

**Comment by mdzio** [comment]
Ansonsten müsstest Du ein Issue im [Docker-Repo](https://github.com/jokay/docker-ccu-historian) eröffnen.

**Comment by t-rood** [comment]
öhm... **JA!** ok, das war mir nicht klar. ;-) gelöst. Mit dem DiskSpace-Verbrauch an sich kann ich ja leben. Die Laufzeit ist wieder gut und es startet auch fix.

Vielen Dank!
