### ISSUE TITLE
Historian vewechselt plötzlich Datenreihen mit anderen Messgeräten

### ISSUE THREAD

**Issue by mkeschle** [mdzio/ccu-historian#365]
Ich habe heute den Historian als addon in der CCU-GUI installiert (raspberrymatic). dann habe ich auf iPHone die app dazu installiert. Das ging ca 8h gut, aber jetzt plötzlich spät Abends verwechselt der Historian sowohl im webbrowser wie in der iPhone app Messwertzeitreihen. Er zeigt z.B. statt den Leistungsdaten eines Schaltsteckdose den Zeitverlauf einer Variable, oder für einen anderen Schaltaktor statt dessen Leistung den Temperaturverlauf eines anderen Sensors! Mir wird mulmig... was könnte das sein?

**Comment by mdzio** [comment]
Das Phänomen wurde noch nie beobachtet.
Du wählst also im Web-Browser ein Datenpunkt aus, und in der Trendansicht wird dann ein anderer gezeigt?
Welche iPhone-App verwendest Du?

**Comment by mkeschle** [comment]
Ich verwende die 3.3.0 auf raspberrymatic. die App ist die letzte version iOS im App-store (ich sehe keine ver-nr). 
Ich hatte gleichzeitig Probleme mit den Hm-WEBUI Diagrammen, da waren Daten seit ca Juli, aber plötzlich nur noch seit gestern. Irgendetwas faul. ich habe nun inzwischen einen neuen Stick (micro-SD in USB Stick) eingesetzt und die alten Diagramm-Daten aus Backup vor einigen Tagen dort kopiert. Webui-Diagramme funktionieren wieder und auch der ccu-Historian (aber nur Daten seit neu-Installation). Mal sehen ob's jetzt stabil läuft.

**Comment by mkeschle** [comment]
Leider habe ich nun seit gestern 2230h wieder das gleiche Problem wie vor 3 Tagen mit dem ersten USB Stick: die Daten für die Diagramme sind für raspberrymatic nicht mehr lesbar, und ccu-HIstorian verwechselt Datenreihen in den Grafiken mit anderen Messpunkten (ich könnte dies mit ein paar screen-pics vom iPhone belegen. wie kann man dies hier hochladen?). Der Zeitpunkt "gestern 2230h" ist bestimmt durch die Meldung der CCU, dass diese abgestürzt war (unclean shutdown or system crashed) und selbständig neu startete. Aufgrund der zeitlichen Zusammenhänge (Problem entstand jeweils ca 24h nach der Neu-Installation von ccu-Historian, und vorher hatte ich keine solchen Probleme) vermute ich, dass der Historian das Problem ist od auslöst. 
Guter Rat scheint teuer, any Hints?

**Comment by mkeschle** [comment]
Ich habe neben dem oben beobachteten Problem auch das Folgende. Ev haben diese einen Zusammenhang:

der ccu-Historian macht mir immer die Diagramm-Daten auf dem USB-Stick der CCU (folder usb0/measurement/ ) unslesbar. Die Daten sind weiterhin auf dem Stick, aber die CCU meldet nach der Installation von ccu-Historian sowohl unter der Option Status/Bedienung, Diagramme wie auch unter Einstellungen Diagramme, dass kein USB Stick vorhanden sei.
Ich kann die Daten wieder nutzen, indem ich sie auf ein anderes Medium kopiere, den Stick neu formattiere (FAT32 oder NTFS) und dann wieder auf den Stick kopiere. Das Kopieren muss ich aber per SFTP Zugriff auf den USB Stick im Raspi (CCU ist raspberrymatic, latest version) kopiere. Wenn ich diese auf den USB Stick im Mac (oder auch am Win10 PC) kopiere scheint es die CCU auch nicht zu finden.

To Reproduce
Dieser Fehler tritt sowohl auf, wenn ich den ccu-Historian als addon in der CCU installiere (finde ich die beste Lösung - eigentlich) oder wenn ich diesen auf der Synology in Docker installiere.

Steps to reproduce the behavior:

Start the container 'jokay/docker-ccu-historian mit parameter gem. Docker.com
Execute raspberrymatic, aufruf von Diagramme
See error Messdaten für Diagramme sind nicht auffindbar. CCU meldet "kein USB Speicher vorhanden" (od ähnlich)
Environment (please complete the following information):

OS: [e.g. Debian, Windows, ...] raspberrymatic latest version 3.65.11.20221005
Docker version [e.g. 20.10.3] auf synology Paket, latest version
Docker compose version [e.g. 1.28.2] n/a
Anm: ich glaube, ich hätte mal das gleiche Problem beobachtet nach einem Zugriff des iobroker auf die CCU, bin aber nicht sicher, ob dies wegen iobroker war oder wegen ccu-Historian. Konnte dies mit iobroker nicht mehr reproduzieren, habe aber mit iobroker auch das Problem, dass das rfd Modull keinen Zugriff erhält (das CuxD Modul findet die Daten hingegen) Dies ist wohl ein ganz anderes Problem, sei hier aber mal erwähnt, ev hat es doch einen Zusammenhang, Zugriffsproblem etc. ...

**Comment by mdzio** [comment]
Ich prüfe mal, ob der CCU-Historian irgendwie die Diagrammdaten der CCU auf dem USB-Stick verändert.

**Comment by mdzio** [comment]
Das Problem konnte bisher auf keinem anderen System nachvollzogen werden. Ich schließe mal diesen Eintrag. Bei Bedarf kann er wieder geöffnet werden.
