### ISSUE TITLE
Text-Schnittstelle: avg nicht nachvollziehbar

### ISSUE THREAD

**Issue by the-other-martin** [mdzio/ccu-historian#366]
Hallo Mathias,
ich habe folgende Zeitreihe im Datenpunkt 587 und möchte den Mittelwert (und andere Aggregate) auswerten:
`
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/GROSSM~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/GROSSM~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

29.10.2022   12:34:13,769 | 2 | 2.003
-- | -- | --
29.10.2022   12:45:02,000 | 2 | 2.003
29.10.2022   13:00:05,000 | 2 | 2.003
29.10.2022   13:15:01,000 | 2 | 2.003
29.10.2022   13:30:02,000 | 2 | 2.003
29.10.2022   13:45:02,000 | 2 | 2.003
29.10.2022   14:00:05,000 | 2 | 2.003
29.10.2022   14:15:01,000 | 2 | 2.003
29.10.2022   14:30:04,000 | 2 | 2.003
29.10.2022   14:45:01,000 | 2 | 2.003
29.10.2022   15:00:04,000 | 2 | 1.999
29.10.2022   15:15:02,000 | 2 | 1.999
29.10.2022   15:30:02,000 | 2 | 1.999
29.10.2022   15:45:01,000 | 2 | 1.999
29.10.2022   16:00:05,000 | 2 | 1.999
29.10.2022   16:15:02,000 | 2 | 1.999
29.10.2022   16:30:03,000 | 2 | 1.999
29.10.2022   16:45:00,000 | 2 | 1.999
29.10.2022   17:00:01,000 | 2 | 1.999
29.10.2022   17:15:01,000 | 2 | 1.999
29.10.2022   17:30:01,000 | 2 | 1.999
29.10.2022   17:45:00,000 | 2 | 1.999
29.10.2022   18:00:02,000 | 2 | 1.999
29.10.2022   18:15:00,000 | 2 | 1.999
29.10.2022   18:30:01,000 | 2 | 1.999

</body>

</html>
`

Dazu verwende ich 

`http://192.168.1.120:81/query/text.gy?dp=587&b=-6h&ag=max&ag=min&ag=avg&ag=first&ag=last`

und erhalte

`2.003 1.999 1.9877070703703703 2.003 1.999 `

Der dritte Wert müsste der Mittelwert sein, er ist allerdings niedriger als der niederste Wert - ich kann das Ergebnis nicht nachvollziehen. Liegt hier ein Fehler im Historian oder bei mir vor?

Schöne Grüße,
Martin

**Comment by mdzio** [comment]
Ich habe noch einmal ein paar Tests bei mir durchgeführt. Die Werte waren immer plausibel.

**Comment by the-other-martin** [comment]
Ich habe auch nochmal mit einem anderen Zeitraum getestet (es handelt sich um die Dieselpreise in den letzten Stunden:
![grafik](https://user-images.githubusercontent.com/44535691/198870993-bb66f186-4fca-4422-96e1-f8d7dd9abcb4.png)

mit:
[http://192.168.1.120:81/query/text.gy?dp=587&b=-5h&ag=max&ag=min&ag=avg&ag=first&ag=last](url)
erhalte ich:
`1.999 1.994 1.9373308072222224 1.999 1.994 `

D.h. der Mittelwert liegt demnachbei 1.937, obwohl der höchste Wert (indiesem Intervall) 1.999 und der niedrigste Wert 1.994 war. Das scheint nicht korrekt zu sein.

Spielen Daten vor dem abgefragten Zeitraum auch eine Rolle beim Mittelwert avg?

Schöne Grüße, Martin

**Comment by mdzio** [comment]
Mir ist im Diagramm aufgefallen, dass die Daten nur bis 10:00 Uhr gehen aber der Abfragezeitraum bis 10:08 Uhr. Eventuell hat dies einen Einfluss.
Trage mal bitte als `Ende` 4h45m ein, damit die letzten 15 Minuten nicht berücksichtigt werden. In der Abfrage-URL muss der Parameter `&e=4h45m` hinzugefügt werden.

**Comment by the-other-martin** [comment]
![grafik](https://user-images.githubusercontent.com/44535691/198958080-d4fe0459-d975-45ca-882c-711d0574bf9d.png)

Ich habe eben eine aktuelle Grafik der letzten fünf Stunden erstellt, als Ende für die Text-Schnittstelle 9:30 eingetragen:
`http://192.168.1.120:81/query/text.gy?dp=587&b=-5h&ag=max&ag=min&ag=avg&ag=first&ag=last&e=8h45m`
Ergebnis:
`1.994 1.994 1.1226746036190476 1.994 1.994 `

Anmerkung: Die Daten zum Dieselpereis werden alle 15 Minuten über CCU3 script mittels abgefragt und in die Systemvariable geschrieben. 
Anmerkung 2: Mir ist eben aufgefallen, dass die CCU3 und CCU Historian noch mit der Sommerzeit läuft - siehe auch Diagramm, aber das scheint ein anderes Problem zu sein.
Zum Vergleich habe ich auf einen sehr kurzen Zeitraum eingeschränkt:
`http://192.168.1.120:81/query/text.gy?dp=587&ag=max&ag=min&ag=avg&ag=first&ag=last&b=8h00m&e=8h45m`
Ergebnis:
`-Infinity Infinity NaN NaN NaN `
Anmerkung 3: Noch etwas:
`http://192.168.1.120:81/query/text.gy?dp=587&ag=max&ag=min&ag=avg&ag=first&ag=last&b=-2h&e=-1h`
Ergebnis:
![grafik](https://user-images.githubusercontent.com/44535691/198959722-60ac4f75-6578-4d06-9fc3-148d6ea56d37.png)

**Comment by mdzio** [comment]
Zur Abfrage: `http://192.168.1.120:81/query/text.gy?dp=587&b=-5h&ag=max&ag=min&ag=avg&ag=first&ag=last&e=8h45m` 
`b=-5h`: Die Abfrage startet 5h in der Vergangenheit.
`e=8h45m`: Das Ende ist -5h+8h45m=+3h45m **in der Zukunft**.
Das Ergebnis ist dann einigermaßen plausibel.

Zur Abfrage: `http://192.168.1.120:81/query/text.gy?dp=587&ag=max&ag=min&ag=avg&ag=first&ag=last&b=8h00m&e=8h45m`
Das ist ein Zeitbereich in der Zukunft (+8h bis +16h45m). Dort sind garantiert keine Daten.

Zur Abfrage: `http://192.168.1.120:81/query/text.gy?dp=587&ag=max&ag=min&ag=avg&ag=first&ag=last&b=-2h&e=-1h`
Der Start ist 2h zurück und das Ende ist 3h zurück. Das ist nicht erlaubt.

**Wenn der Parameter `e`, wie oben, relativ (als Zeitdauer) angegeben wird, dann wird vom Beginnzeitpunkt an gerechnet.**

Die Parameter `b` und `e` sind[ hier noch einmal genau beschrieben](https://github.com/mdzio/ccu-historian/wiki#export-von-zeitreihen).

**Comment by mdzio** [comment]
Warum der zurückgegebene Zeitstempel von `mints` vor dem abgefragten Zeitbereich liegt, ist für mich jetzt nicht erklärbar.
Ich konnte es bei meinen Tests auch nicht reproduzieren.

**Comment by the-other-martin** [comment]
Ich habe es eben nochmal versucht, das Ergebnis scheint nun plausibel:
`2.004018982320442 2022-11-01 10:59:49 1.993 2022-11-02 10:00:07 1.998833137954354 2.004018982320442 1.993  `

**Comment by mdzio** [comment]
Ich schließe dann mal diesen Eintrag. Bei Bedaraf kann er wiedereröffnet werden.

**Comment by the-other-martin** [comment]
Danke für Deinen Support!
Schöne Grüße, Martin
