### ISSUE TITLE
docker xjokay/ccu-historian stoppt immer sofort automatisch

### ISSUE THREAD

**Issue by mkeschle** [mdzio/ccu-historian#367]
Hi all
ich habe das docker image xjokay/ccu-historian im docker auf synology sowie in einem völlig unabhängig davon aufgesetzten Raspberry PI 3B (1G Ram, 32GB SD Card, mit docker, portainer, keine weiteren containers) aufgesetzt. In beiden Fällen war zwar die Installation des image erfolgreich, ohne Fehlermeldungen, aber der ccu-Historian stoppte am Ende des Startprozesses, d.h. nach jeweils 30'-60', um dann im docker der synology sofort den Startprozess automatisch wieder zu beginnen (auf dem Raspi musste ich manuell re-starten), bis ich diesen Zyklus manuell stoppe. Die Beobachtung ist wiederholbar mit verschiedensten Versuchen. 
Ich habe die Folders gem. Instruktionen im portainer gemappt, die ports mal manuell 1 zu 1, mal auch automatisch im portainer (dann im host random-ports) gemappt. 
Ich fand bisher noch keinen Grund für den stop, woran könnte das liegen? laufen die anderen instanzen mit dem neuesten image?

**Comment by mdzio** [comment]
Am besten erstellst Du einen Eintrag im [Docker-Projekt](https://github.com/jokay/docker-ccu-historian).

Der CCU-Historian erstellt auch eine Log-Datei. Sind Fehlermeldungen dort zu finden?

**Comment by mkeschle** [comment]
Danke für den Hinweis, habe dies unter dem docker project
https://github.com/jokay/docker-ccu-historian/issues/243
gepostet mit ein paar Details mehr und dem Protokoll von heute dazu.

**Comment by mdzio** [comment]
Ich schließe den Eintrag dann hier.
