### ISSUE TITLE
CCU-Historian 3.2.0.3.0: manuelle Installation Synology DSM 7.1.1 schlägt fehl

### ISSUE THREAD

**Issue by Zehlendorf** [mdzio/ccu-historian#368]
Guten Tag,

bin absoluter Neuling was CCU-Historian betrifft. Habe ccu-historian-dsm7-3.2.0.3.0-noarch.spk downgeloadet und versucht, manuell auf DSM 7.1.1 zu installieren. Wenn ich nach auswählen der Datei auf "weiter" klicke, erhalte ich die Fehlermeldung: "Vorgang fehlgeschlagen. Bitte melden Sie sich erneut im DSM an und versuchen es erneut."

Mache ich etwas falsch?

Danke,
Ludwig

<img width="717" alt="Bildschirmfoto 2022-11-19 um 06 35 49" src="https://user-images.githubusercontent.com/118588102/202836266-850a19b6-dafc-45aa-a01e-efaa8fdd9868.png">

**Comment by mdzio** [comment]
Da ich selber kein Synology NAS besitze, kann ich da nicht weiterhelfen. Eventuell kann jemand mit einem Synology NAS dazu etwas sagen.

**Comment by Zehlendorf** [comment]
Vielen Dank für die Antwort. Ich hatte auch an den Support von Synology geschrieben und habe folgende Antwort erhalten: „Leider können wir Sie bei der Installation von Dritthersteller Paketen nicht unterstützen, da dies aus unserem Supportbereich fällt. In diesem Fall müssten Sie sich an den Hersteller des Paketes wenden.
Wir können Sie nur bei der Installation unsere Pakete unterstützten."

Jetzt habe ich den Historian erst mal auf meinem Mac installiert. Weitere Fragen folgen.

Vielen Dank,
Ludwig

**Comment by mdzio** [comment]
Da längere Zeit keine Rückmeldung mehr kam, schließe ich diesen Eintrag. Bei Bedarf kann er wieder geöffnet werden.
