### ISSUE TITLE
ccu-historian unter Monterey:  kann "http://localhost:8082" nicht aufrufen

### ISSUE THREAD

**Issue by Zehlendorf** [mdzio/ccu-historian#370]
Guten Tag,

ich haben den ccu-historian unter MacOs Monterey installiert und "database.webEnable=true" gesetzt. "history.mv.db" ist vorhanden und wächst kontinuierlich. In Safari bekomme ich beim Aufrufe von "http://localhost:8082" die Fehlermeldung "Kann keine Verbindung zum Server aufbauen". 
Was mache ich falsch?

Danke,
Ludwig

**Comment by mdzio** [comment]
Die normale CCU-Historian Web-Oberfläche auf Port 80 funktioniert?

Muss eventuell noch die Firewall von MacOS konfiguriert werden?

**Comment by mdzio** [comment]
Da längere Zeit keine Rückmeldung mehr kam, schließe ich diesen Eintrag. Bei Bedarf kann er wieder geöffnet werden.
