### ISSUE TITLE
Kein Zugriff auf CCU-Datenpunkte

### ISSUE THREAD

**Issue by fant42** [mdzio/ccu-historian#371]
Hallo,

auf zwei verschiedenen Systemen erscheinen bei einer CCU-Historian-Neuinstallation nur die SysVar-Variablen, aber keine anderen Datenpunkte. CCU ist einmal ein PC mit RaspiMatic und einmal ein Pi mit RaspiMatic, beide mit einer Funkkarte, versteht sich. Es geht weder mit noch Authentifizierungspasswort.

Ist das ein bekanntes Problem? RasperryMatic ist in beiden Fällen die Version 3.65.11.20221005, Historian ist 3.3.0 von hier.

Danke.

**Comment by mdzio** [comment]
Vielleicht helfen folgende Themen weiter:
* [Firewall-Einstellungen](https://github.com/mdzio/ccu-historian/wiki#firewall-einstellungen)
* [Nach dem allerersten Start des CCU-Historians werden keine Gerätedatenpunkte aufgelistet](https://github.com/mdzio/ccu-historian/wiki/Tipps-&-Tricks#nach-dem-allerersten-start-des-ccu-historians-werden-keine-gerätedatenpunkte-aufgelistet)
* [Wertänderungen von Gerätedatenpunkte werden nicht aufgezeichnet](https://github.com/mdzio/ccu-historian/wiki/Tipps-&-Tricks#wertänderungen-von-gerätedatenpunkte-werden-nicht-aufgezeichnet)

**Comment by fant42** [comment]
Jetzt geht es!

Der entscheidende Hinweis war:

Wertänderungen von Gerätedatenpunkte werden nicht aufgezeichnet

Der CCU-Historian muss der CCU die eigene IP-Adresse mitteilen, damit die CCU Wertänderungen an den CCU-Historian schicken kann. Die Ermittlung der eigenen IP-Adresse funktioniert je nach eingesetzter Java VM oder eingesetztem Betriebssystem unter Umständen nicht. Dies wurde z.B. unter Ubuntu oder verschiedenen Java VMs für Embedded-Systeme (z.B. NAS) berichtet.

In diesem Fall muss in der Konfigurationsdatei die IP-Adresse des CCU-Historian-Rechners manuell angegeben werden:

devices.historianAddress='IP-Adresse'
webServer.historianAddress='IP-Adresse'

Vielen Dank - Klasse Support! Alle Daumen hoch!
