### ISSUE TITLE
Add-On-Installation: Start-Skript soll Konfigurationsdatei nicht anpassen

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-historian#372]
Das Start-Skript `/usr/local/etc/config/rc.d/ccu-historian` modifiziert unter Umständen die Konfigurationsdatei `/usr/local/addons/ccu-historian/ccu-historian.config` vor dem Start des CCU-Historians. Beispielsweise wird die IP-Adresse `webServer.historianAddress` aktualisiert, wenn die IP-Adresse der CCU geändert worden ist.

[Dies ist manchmal nicht sinnvoll](https://homematic-forum.de/forum/viewtopic.php?f=38&t=76640) und sollte abschaltbar sein. Beispielsweise könnte eine "Kontrolldatei" `/usr/local/addons/ccu-historian/DISABLE_CONFIG_UPDATE` vom Start-Skript abgefragt werden.

**Comment by martinrieder** [comment]
Ich möchte hinzufügen, dass eine konfigurierbare Verzögerung des Starts wünschenswert wäre. Manche Kanäle liefern nämlich nach dem CCU-Neustart ungültige Werte, die dadurch ignoriert würden.

**Comment by mdzio** [comment]
> Ich möchte hinzufügen, dass eine konfigurierbare Verzögerung des Starts wünschenswert wäre. Manche Kanäle liefern nämlich nach dem CCU-Neustart ungültige Werte, die dadurch ignoriert würden.

Für einen verzögerten Start folgende Zeile am Ende der Konfigurationsdatei `ccu-historian.config` hinzufügen:
```
sleep 60000
```
Dadurch wird der Start um 60.000 Millisekunden, also 60 Sekunden, verzögert.
