### ISSUE TITLE
Gerät "IP Heizkörperthermostat - kompakt Typ: HmIP-eTRV-C" fehlt in DatenpunktListe 

### ISSUE THREAD

**Issue by Icke2022** [mdzio/ccu-historian#373]
Hallo mdzio,
habe heute CCU Historian auf einer Synology installiert. Beim Einrichten der Trenddiagramme mußte ich feststellen, das mein Homematic IP Heizkörperthermostat - kompakt Typ: HmIP-eTRV-C nicht in der Datenpunktliste auftaucht. Egal ob ich nach Teilen oder der gesamten Seriennummer suche. Ist diesbezüglich etwas bekannt oder mache ich etwas falsch?

Gruss icke2022

**Comment by mdzio** [comment]
Das Problem wurde bisher nicht gemeldet.

Allerdings kann es auch einige Zeit dauern, bis es in der Datenpunktliste auftaucht. Das Gerät erscheint erst, wenn es die erste Wertänderung gesendet hat.

**Comment by Icke2022** [comment]
Aha, danke für die Info. Mittlerweile ist der HmIP-eTRV-C in den Datenpunkten aufgetaucht.
Gehe ich richtig in der Annahme, dass der Historian alle verfügbaren Datenpunkte des jeweiligen Gerätes erfasst? 
Ich vermisse die Angabe, wie weit das Ventil geöffnet ist. Allerdings konnte ich in der Datenpunktbeschreibung auch nichts entsprechendes finden.

**Comment by mdzio** [comment]
Alle Datenpunkte eines Gerätes, von denen das Gerät Wertänderungen übermittelt, werden im CCU-Historian aufgenommen und aufgezeichnet.
Wird denn die Ventilstellung in der CCU-Oberfläche irgendwo angezeit?

**Comment by Icke2022** [comment]
"Wird denn die Ventilstellung in der CCU-Oberfläche irgendwo angezeit?"
Ja, im Raspberrymatic wird die Information angezeigt. 
![geraet](https://user-images.githubusercontent.com/120517300/207802337-8c5c852e-148b-4083-b375-9d6ac09c9f83.PNG)

Auch kann ich im Raspberrymatic, für ein Diagramm, diesen Wert auswählen.
![diagramm](https://user-images.githubusercontent.com/120517300/207802537-da00b99f-877a-4ccb-b5b6-a1852e4ec24e.PNG)

Doch im Historian werden nur folgende Werte angeboten:
![Historian](https://user-images.githubusercontent.com/120517300/207802725-3fe555b9-34fb-40d5-9e2a-5e87b36aa4fc.PNG)

Der Wert VALUE_STATE ist nur ein Rückgabewert für verschiedene Status des HmIP-eTRV-C. Nicht des Öffnungswertes.

**Comment by mdzio** [comment]
VALVE_STATE müsste doch der Ventilöffnungsgrad sein?

**Comment by Icke2022** [comment]
> VALVE_STATE müsste doch der Ventilöffnungsgrad sein?

Dachte ich auch. Ist aber nicht so. Lt. HmIP_Device_Doku ist es:

![grafik](https://user-images.githubusercontent.com/120517300/207984944-2fe7ad12-171f-4291-a181-c1657e3948f3.png)

**Comment by Icke2022** [comment]
Würde auch mit dem Wert passen, den ich gemeldet bekomme. INT = 4 "ADATION DONE"

**Comment by mdzio** [comment]
Ich besitze so ein Gerät nicht. Am besten fragst Du mal im [HomeMatic-Forum](https://homematic-forum.de/forum/index.php) nach, wie dieser Datenpunkt heißt.

**Comment by Baxxy13** [comment]
Es ist der Datenpunkt: `LEVEL`
So wie bei allen anderen IP-Heizkörperthermostaten auch.

**Comment by mdzio** [comment]
Danke Baxxy. Dann schließe ich mal diesen Eintrag hier.
