### ISSUE TITLE
Vorschlag : Namen der Backups inkl. Versionsnummer möglich ?

### ISSUE THREAD

**Issue by g56-git** [mdzio/ccu-historian#375]
Moin,
Ich hatte gerade mein RaspberryMatic wie auch Historian Backup mal aufgeräumt ...
Dabei fiel mir auf, dass 

- bei RM IMMER die Version im Namen der Backup-Datei vorhanden ist
- beim Historian NIE die Version im Namen der Backup-Datei vorhanden ist

Ist es nicht so, dass im Historian ein Backup auch nur in der Version zurückgespielt werden soll, in der das Backup auch erstellt wurde ?

meine Vorschläge wären z.B.

1. zumindest einen neuen Platzhalter zu definieren, z.B. "%V" für die aktuell installierte Version, damit durch die config der Backup-Name eindeutig einer Version zuzuordnen ist.
2. evtl. bei einem Update automatisch ein Backup der ALTEN Version anzustoßen VOR dem Update ... macht RM ja auch.

Wäre dies umsetzbar mit vertretbarem Aufwand ? Ich würde mich jedenfalls sehr freuen, natürlich auch über jegliche Kommentare.

vG.

**Comment by mdzio** [comment]
Die Versionsnummer bei der Backuperstellung ist beim CCU-Historian nicht so kritisch, wie bei RaspberryMatic.

Generell können V1-Backups in V1 und V2 zurückgespielt werden, V2-Backups in V2 und V3, usw.

Der Parameter "%V" als zusätzliche Informationen ist aber vielleicht sinnvoll. Ich schaue mit das mal an.

Deswegen und weil ein Backup je nach Datenbankgröße längere Zeit dauern kann, ist ein automatisches Backup bei einem Update nicht sinnvoll.

**Comment by g56-git** [comment]
"sorry for the late reply" ...
vielen Dank für Deine Antwort.

jep, da müßte ich unterscheiden können, ob mein Backup von vor 2 Jahren noch ein V1/2/3-Backup ist, sollte jedoch kein Problem sein, ich weis ja ungefähr, was ich wann installiert habe und zudem gibt es ja die Versionshistorie :-)

ok, dass mit dem automatischen Backup sehe ich auch so. Es gibt halt User mit "huge" Datenbanken, meine ist nach 2,5 Jahren grad mal ca. 200 MB, da geht das Backup noch sehr zügig. Ich kann daher gut mit dem guten, alten IT-Prinzip leben : vor nem manuellen Update/Upgrade mach ich selbst ein manuelles Backup.

Und das mit dem "%V" wäre schön, wenn du das mit geringem Aufwand einbauen könntest ... ist nicht essentiell, eher optional .

vielen Dank + vG
