### ISSUE TITLE
Duty Cycle value for CCU3 is not tracked.

### ISSUE THREAD

**Issue by Denis1983** [mdzio/ccu-historian#376]
It would be nice to track Duty Cycle value for CCU
But it is not tracked in any table.

<img width="545" alt="Screenshot 2022-12-27 at 11 31 11" src="https://user-images.githubusercontent.com/5038510/209653640-c725975b-12ad-4802-9695-c5c59804f0c9.png">

**Comment by mkeschle** [comment]
I see these values as sysvar values, tracked for my raspberrymatic and both my LAN-Gateways. Are you sure they are not tracked in your case?

**Comment by Denis1983** [comment]
Where do I find them exactly?
How to use them in the SQL query?
I have normal CCU3.

<img width="867" alt="Screenshot 2022-12-27 at 18 13 35" src="https://user-images.githubusercontent.com/5038510/209699689-77800d92-eba7-4ef7-a4cd-6aca9f582d43.png">

**Comment by mkeschle** [comment]
Hm, don't really know, I find them in my regular list of datapoint, see screenshot.
<img width="1150" alt="Bildschirmfoto 2022-12-27 um 19 00 41" src="https://user-images.githubusercontent.com/79287862/209705072-efd0e4a5-68ce-477a-899c-ebdf50c625ff.png">

**Comment by Baxxy13** [comment]
Don't know exactly but i think CCU3 hasn't a SysVar for Duty Cycle. RaspberryMatic has it.

**Comment by mkeschle** [comment]
Well, possible. That might then be a reason to upgrade to raspberrymatic! :-) 
As far asbI know CCU3 allows to run raspberrymatic instead os the original OS.

**Comment by Denis1983** [comment]
That works in raspberrymatic.
