### ISSUE TITLE
Wertetabellen über DATA_POINTS auslesen?

### ISSUE THREAD

**Issue by alekob** [mdzio/ccu-historian#378]
Da die Namen der Wertetabellen etwas kryptisch sind, möchte ich diese (später in Grafana) über DATA_POINTS auslesen, in etwa wie folgt:

SELECT *  FROM data_points.table_name WHERE data_points.room = 'Balkon' AND data_points.display_name='Wetterstation:1' AND data_points.identifier = 'HUMIDITY';

Dies klappt leider nicht: Schema "DATA_POINTS" not found; SQL statement

Wenn überhaupt, wie ist die Werteabfrage über DATA_POINTS gedacht?

**Comment by mdzio** [comment]
Dieser Ausdruck, der den Tabellennamen zurück gibt, funktioniert:
`SELECT table_name FROM data_points WHERE data_points.room = 'Balkon' AND data_points.display_name='Wetterstation:1' AND data_points.identifier = 'HUMIDITY';`

**Comment by mdzio** [comment]
Ich schließe mal den Eintrag, da längere Zeit keine Rückmeldung mehr kam. Bei Bedarf kann er wieder geöffnet werden.
