### ISSUE TITLE
Wiederherstellen der DB auf Synology Hilfe

### ISSUE THREAD

**Issue by Trapper12** [mdzio/ccu-historian#381]
Hi,
ich habe den historian als Paket auf der Synology laufen DSM 6.
Hatte Stromausfall, das hat wohl die Datenbank beschädigt.
Habe keine Anleitung zum Wiederherstellen auf einer Synology gefunden und gedacht, ich könnte das über eine win Version machen und dann die wiederhergestellte Datenbank in das Synology Verzeichnis kopieren. Klappt aber wohl nicht :-)

Habe die 3.02.bin.zip geladen und in ein Verzeichnis auf einem Windows Rechner entpackt. Habe dann den Ordner data hinzugefügt und hier die history.mv.db von der Synology reinkopiert. Habe dann gemäß Wiki recovered.
Der Befehl: java -cp lib\h2-2.1.212.jar org.h2.tools.Recover -dir data -db history
bringt folgendes Ergebnis
![Bild1](https://user-images.githubusercontent.com/34746380/224324084-4dab176b-731a-47da-ba6b-a3fc32d90a2d.png)
In dem Verzeichnis data wird die history.mv.txt angelegt, jedoch nicht die history.h2.sql. Alles Weitere funktioniert dann natürlich nicht mehr.
Brauche Hilfe

Gruß
Klaus

**Comment by mdzio** [comment]
Das Datenbank ist wohl so stark beschädigt, dass das Recovery-Tool diese nicht mehr herstellen kann.

**Comment by Trapper12** [comment]
> Das Datenbank ist wohl so stark beschädigt, dass das Recovery-Tool diese nicht mehr herstellen kann.
> 
> Generell ist aber eine Reparatur der Datenbank unter Windows für andere Systeme möglich.

Hi, Danke für die Antwort. Du siehst keine Möglichkeit der Wiederherstellung?
Gruß
Klaus

**Comment by mdzio** [comment]
Welche Fehlermeldung kommt denn, wenn Du den CCU-Historian mit der defekten Datenbank unter Windows startest?

**Comment by Trapper12** [comment]
> Welche Fehlermeldung kommt denn, wenn Du den CCU-Historian mit der defekten Datenbank unter Windows startest?

Nach ca 10 min Fehlermeldung "Datei beschädigt" und recover Empfehlung.
![Historian Fehler](https://user-images.githubusercontent.com/34746380/225262606-ef9a8a7d-f082-4907-8c43-2652a3c3a0ff.png)

**Comment by mdzio** [comment]
Die Datenbank ist wohl nicht mehr zu retten.

**Comment by Trapper12** [comment]
> Die Datenbank ist wohl nicht mehr zu retten.

Ja, das dachte ich mir. Trotzdem Danke
