### ISSUE TITLE
Postgres als DB Alternative?

### ISSUE THREAD

**Issue by zell-mbc** [mdzio/ccu-historian#382]
Gibt es Überlegungen Alternativen zur H2 Datenbak anzubieten?
Hintergrund meiner Frage ist das ich derzeit meinen Server für Tests immer wieder mal schnell durchstarte. Und dabei zerschiesst es mir regelmäsig die H2 Datenbank.

Dank Backup ist das Problem schnell behoben, aber Daten gehen immer verloren weil ich nicht gleich merke das es wieder klemmt. Die Postgres Datenbanken die parallel zu ccu-historian laufen machen keine Probleme.

**Comment by mdzio** [comment]
Die eingebettete H2-Datenbank ist bereits sehr verzahnt mit dem CCU-Historian. Ein Herauslösen ist also etwas aufwändiger und einige Funktionen des CCU-Historians stehen dann nicht mehr zur Verfügung.

Das wurde bereits auch im Eintrag #36 gewünscht. Daher schließe ich mal diesen Eintrag.
