### ISSUE TITLE
Generierung der Trend Grafik als SVG funktioniert nicht

### ISSUE THREAD

**Issue by MKaiser96** [mdzio/ccu-historian#383]
Hallo,

ich habe auf meinem Synology NAS mit neuester DSM Version den CCU Historian 3.3.0 installiert. In der Config habe ich die Zeile webServer.trendSvg=true eingefügt. Leider wird mir bei der Trendgenerierung nach wie vor folgendes angezeigt.

Bitte warten: Die Trend-Darstellung wird generiert!

Das Problem tritt bei macOS und iOS jeweils mit Safari und unter Windows 11 mit Firefox auf.

Was ist hier das Problem? Ich möchte gerne die SVG Grafiken erzeugen, da ich nach jedem DSM Update die Java Schriftarten neu einfügen muss für die PNG Grafiken.

**Comment by freaky-m0** [comment]
Interessant, ich habe bei mir in der Konfiguration nichts verändert (was ist denn Standard?) und habe das gleiche Problem. Es ging einfach irgendwann nicht mehr. Mein CCU Historian läuft aber auf einer Raspberrymatic.

**Comment by freaky-m0** [comment]
Ich habe heute auf die Version 3.3.1 aktualisiert und der Fehler ist weg. @MKaiser96

**Comment by MKaiser96** [comment]
Danke für den Hinweis. Mit der neuen Version 3.3.1 funktioniert nun auch bei mir die Trenddarstellung als Vektorgrafik auf der Diskstation.

**Comment by MKaiser96** [comment]
Hallo,

ich habe auf meinem Synology NAS das neueste DSM installiert und den CCU-Historian. Bisher lief er mit der Version 3.3.1 problemlos. Heute habe ich nach längerer Zeit mal wieder in den CCU-Historian reingeschaut und ich kann keine Trendgrafiken mehr erzeugen. Es erscheint immer die Meldung: "Bitte warten: Die Trend-Darstellung wird generiert!".

Ich lasse mir die Grafiken als SVG Grafik generieren. Dies habe ich in der Config konfiguriert:
webServer.trendSvg=true

Das hat bis vor kurzem einwandfrei funktioniert. Zur Sicherheit habe ich auf CCU-Historian 3.4.0 aktualisiert, aber der Fehler besteht weiterhin.

**Comment by mdzio** [comment]
Bei der Meldung "Die Trend-Darstellung wird generiert!" bitte testweise mal 5 Minuten warten. 

Die Trends funktionieren mit der Einstellung `webServer.trendSvg=false`?

**Comment by mdzio** [comment]
Bisher gibt es keine Rückmeldung. Deshalb wird der Eintrag geschlossen.

Allgemein wird die Darstellung als SVG auch nicht weiter gepflegt. Zeitlich ist dies nicht möglich.
