### ISSUE TITLE
erweiterte Nutzung der H2-DB für Grafana

### ISSUE THREAD

**Issue by ergorion** [mdzio/ccu-historian#386]
Bei mir läuft der CCU-Historian und protokolliert alle Werte schön in die H2-Datenbank, die von Grafana über den PostGres-Zugriff ausgelesen werden. Funktioniert einwandfrei. Vielen Dank schon mal.

Nun wollte ich für mein Heizungsmonitoring keinen eigenen Datenbank-Server aufbauen und habe daher in der H2 eine neue Datenbank parallel zu jdbc:h2:/database/history angelegt: jdbc:h2:/database/heizung

Damit habe ich eine saubere Trennung der Datenbanken (auch mit eigenen Nutzern). Nun muss ich aber feststellen, dass diese zweite Datenbank nicht in Grafana über Postgres verfügbar ist. 
H2 meldet: org.h2.message.dbexception: Schema "PG_CATALOG" not found [90079-214]
Grafana meldet: db query error: EOF
Und im Web-UI von H2 für die zweite DB fehlt auch wirklich der Folder PG_CATALOG.

Lange Rede, kurzer Sinn: gibt es eine Möglichkeit, auch für die zweite Datenbank die Option des Postgres-Zugriffs freizuschalten? Die Optionen database.pgEnable etc. klingen eigentlich nach globalen Einstellungen...

Danke für jedweden Hinweis.

**Comment by mdzio** [comment]
Wie hast Du die zweite Datenbank angelegt? Über die Web-UI der Datenbank?

Ich denke, dass der eingebettete Datenbank-Server im CCU-Historian nur eine Datenbank bedienen kann. Die zweite Datenbank müsste gesondert auf einem anderen Port gestartet werden, damit sie über das PostgreSQL abgefragt werden kann.

**Comment by ergorion** [comment]
Hallo, Mathias!

Mittlerweile bin ich etwas schlauer... 
> Ich denke, dass der eingebettete Datenbank-Server im CCU-Historian nur eine Datenbank bedienen kann. 

Ne, das funktioniert eigentlich recht zuverlässig. Und wie Du schon richtig vermutet hast:
> Wie hast Du die zweite Datenbank angelegt? Über die Web-UI der Datenbank?
habe ich einfach in der Web-UI eine zweite DB angegeben, und dann legt H2 diese zweite Datenbank an (steht auch so in der Doku von H2).
Wenn man sich normal darauf verbinden will, funktioniert alles einwandfrei.
Problematisch wird's anscheinend nur, wenn man Besonderheiten wie Postgres-Zugriff möchte. Und hier habe ich mittlerweile herausgefunden:
Wenn ich in der Web-UI beim Einloggen in die zweite DB im Connect-String: jdbc:h2:/database/heizung;MODE=PostgreSQL
angebe, dann setzt H2 intern wohl die notwendigen Einstellungen, so dass der Zugriff mittels Postgres geht. Grafana ist glücklich. Aber leider nur vorübergehend, nach dem nächsten Neustart von H2 ist das wieder weg. Aber das ließe sich über einen Script-Aufruf lösen.

Vielen Dank noch mal für Deine Zeit, ich schließe das Thema jetzt.
