### ISSUE TITLE
H2 DB console (WebUI) funktioniert nicht, benötige Hilfe

### ISSUE THREAD

**Issue by dl6lr** [mdzio/ccu-historian#389]
Installation 3.3.1 auf Debian Bullseye AMD64. Keine Besonderheiten in der Konfiguration. Das System ist headless, Zugriff über Webbrowser und ssh. Zugriff auf die DB und den PG-Mode über config erlaubt:

// database.dir='./data'
// database.name='history'
// database.user='sa'
// database.password='ccu-historian'
database.backup='./backup/%Y-w%W.zip'
database.webEnable=true
database.webPort=8082
database.webAllowOthers=true
// database.tcpEnable=false
// database.tcpPort=9092
// database.tcpAllowOthers=false
database.pgEnable=true
// database.pgPort=5435
database.pgAllowOthers=true
// database.tasks ... (s.a. https://github.com/mdzio/ccu-historian/wiki#automatische-ausführung-von-skripten)
webServer.port=8080

Der Zugriff von extern auf die Weboberfläche Port 8080 funktioniert. Insgesamt läuft soweit alles. Der Klick auf den Menüpunkt 
Werkzeuge/Datenbank
bringt den URL 127.0.0.1:8082, aber der ist hier falsch. Nach Ersatz von localhost durch den DNS-Namen t630 und Aufruf von http://t630:8082 bekomme ich als Antwort "Host t630 not found". Das verwirrte mich zuerst insofern als es tatsächlich eine gültige HTTP-Response mit Responsecode 404 ist und den Content "Host t630 not found" enthält und keine Meldung vom Browser ist. Ersetze ich den Namen durch die IP-Adresse, erhalte ich diese in der Antwort zurück. Nach Stoppen von ccu-historian ist auch der Port nicht erreichbar.

Der Kommunikationsmitschnitt ist:
`GET / HTTP/1.1 
Host: t630:8082 
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0 
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8 
Accept-Language: de,en-US;q=0.7,en;q=0.3 
Accept-Encoding: gzip, deflate 
Connection: keep-alive 
Upgrade-Insecure-Requests: 1

HTTP/1.1 404 Not Found 
Content-Length: 19 
 
Host t630 not found`

Über ssh mit w3m lokal getestet, erhalte ich "Bad request". Hier kann ich keinen trace beisteuern.
Ziel soll sein den Zugriff aus Grafana zu machen. Dazu soll ein eingeschränkter Nur-Lese-Benutzer eingerichtet werden.

Das Problem trat mit 3.3.0 bereits auf, gerade habe ich daher auf 3.3.1 aktualisiert. Irgendwelche Hinweise?

**Comment by mdzio** [comment]
Bitte mal die Optionen `webServer.historianAddress` und `devices.historianAddress` auf die IP-Adresse des Historian-Rechners setzen.

**Comment by dl6lr** [comment]
Erstmal vielen Dank für die schnelle Hilfe!
Das funktioniert tatsächlich, allerdings leider nur mit der IP-Adresse. Der Name wird allerdings korrekt aufgelöst, sowohl domainlos nur als t630 oder als t630.fritz.box. Kann man das noch irgendwie hinbekommen? Weil auch noch die Umstellung auf IPv6 hier ansteht, da wird es unübersichtlich mit den Adressen...

`bernd@t630:~/ccu-historian$ nslookup
> t630
Server:         192.168.178.1
Address:        192.168.178.1#53

Name:   t630.fritz.box
Address: 192.168.178.23
> t630.fritz.box
Server:         192.168.178.1
Address:        192.168.178.1#53

Name:   t630.fritz.box
Address: 192.168.178.23
> exit
`

**Comment by mdzio** [comment]
Ich habe dort selber auch noch nie einen Netzwerknamen eingetragen. Den Eintrag schließe ich dann mal.
