### ISSUE TITLE
Synology Packet mit MariaDB

### ISSUE THREAD

**Issue by GoProAndy** [mdzio/ccu-historian#392]
Hallo,
ich überlege mir gerade den ccu-historian auf meiner Synology zu installieren. 

Frage vorab:
kann ich statt der bulit in DB auch eine Synology MariaDB verwenden?

danke und lg
Andy

**Comment by mdzio** [comment]
Der CCU-Historian verwendet eine eingebettete Datenbank. Dies ist die H2Database. Eine externe Datenbank kann nicht verwendet werden, da der CCU-Historian stark auf die H2Database optimiert ist.
