### ISSUE TITLE
Historian AddOn-Update lässt Dateien der Vorgängerversion im AddOn-Verzeichnis zurück

### ISSUE THREAD

**Issue by Baxxy13** [mdzio/ccu-historian#397]
Bei einem regulären AddOn-Update über die Systemsteuerung werden aktualisierte Dateien, speziell nach `/usr/local/addons/ccu-historian/ccu-historian/lib` kopiert. 
Die Dateien der Vorgängerversion(en) werden aber nicht gelöscht und verbleiben somit im Verzeichnis bis man sie entweder händisch entfernt oder den Weg über Historian-Deinstallation + Neuinstallation geht.
Dieses "liegenlassen" der alten obsoleten Dateien führt dann zu immer größer werdenden Backups.

Ich habe mal den Test gemacht und folgende Versionen nacheinander installiert.
3.01 / 3.1.0 / 3.2.0 / 3.3.0 / 3.4.0
Dazu dann jeweils ein Backup erstellt:
16,8MB / 19,2MB / 24,3MB / 24,9MB / 31,8MB

Ja, es sind nur ein paar MB, aber die Backupgröße hat sich von 3.0.1 zu 3.4.0 quasi verdoppelt.
RaspberryMatic hält per default 30 Backups vor, das wären mit der 3.0.1 dann etwa 500MB und mit der 3.4.0 dann etwa 950MB.

Räume ich nun das lib-Verzeichnis auf (20 Dateien mit etwa 16MB können weg) dann schrumpft auch mein Backup wieder auf angenehme 17,1MB, also nur etwa 0,3MB größer als das 3.0.1er Backup.

Lange Rede kurzer Sinn...
Es wäre schön wenn bei einem Historian-Update die alten obsoleten Dateien gelöscht würden.

**Comment by mdzio** [comment]
Da die Dateien im lib-Verzeichnis eine Versionsnummer im Dateinamen haben, werden sie bei einem Update nicht ersetzt, sondern die neue Version wird hinzugefügt. Dadurch wird das Backup immer größer. Das Update-Skript sollte aber einfach angepasst werden können.
