### ISSUE TITLE
Data-Source-Plug-In für Grafana

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-historian#40]

**Comment by mdzio** [comment]
Eine Anbindung an Grafana ist mit dem Grafana PostgreSQL-Plug-In und der CCU-Historian PostgreSQL-Schnittstelle nun möglich.

**Comment by Omega236** [comment]
Hallo,
ich habe es geschaft die DB in Grafana einzubinden.
![grafik](https://user-images.githubusercontent.com/25373047/38175445-f5002ac0-35dc-11e8-8f36-019d182e6ce3.png)

Aber irgendwie gibt es probleme bei der DatumsKonvertierung. Ich musste nun alles in Grafana auf UTC umstellen (da sonst alles 1h zu spät ist) und meine SQL abfrage muss ich etwas umgehen da der $__timeFilter nicht funktioniert.
Akteull sieht meine SQL Abfrage so aus:
`SELECT
  $__time(ts),
  value as temp
FROM
  D_BIDCOS_RF_NEQ0170584_4_ACTUAL_TEMPERATURE
WHERE
  ts >= dateadd( SECOND, $__unixEpochFrom() -3600, '1970-1-1' ) and ts <= dateadd( SECOND, $__unixEpochTo() -3500, '1970-1-1')`
das funktioniert schon mal brauchbar, aber ich bekomme die Änderung vor und nach dem Zeitraum nicht mit, damit bleibt es bis zur ersten änderung im Zeitraum nicht definiert. Bei Temperatur kann ich natürlich einfach den SQL-Zeitraum vergrößern, aber bei z.B. Licht kann es auch mal sein dass das Licht 3 Tage nicht angeschaltet wird.

Mit einer Max(TS) < __unixEpochFrom im Where ist die Abfrage zu langsam und dauert rund 10 Sekunden. Hat hier jemand einen Tipp?

und hat jemand einen Schöneren Syntax für die SQL abfrage damit auch das UTC Problem gelöst ist?

**Comment by mdzio** [comment]
Bei mir werden die Zeitstempel korrekt angezeigt. In Grafana habe ich die Zeitzone auf "Default" gesetzt, und ich verwende folgenden SQL-Ausdruck:
`select
  $__time(ts),
  value as Temp
from
  D_HMIP_RF_00XXXXXXXXXXXX_1_ACTUAL_TEMPERATURE
where 
  datediff('second', '1970-01-01', ts) between $__unixEpochFrom() and $__unixEpochTo()
order by
  ts`

Grafana läuft bei mir unter Win10.

**Comment by Omega236** [comment]
Hallo,

leider habe ich auch mit deiner Abfrage das Problem dass obwohl es erst 19:54 ist in Grafana schon Daten bis 20:54 drin stehn (auf UTC stellen behebt das Problem), aber immerhin muss man nicht 3600 abziehen um auf die richtige zeit zu kommen, das versuch ich noch rauszufinden warum. aber leider ist die Abfrage zu langsam.
Ich nutze einen Raspberry und deine Abfrage für einen Tag dauert ~12500ms, meine ~35ms.

**Comment by mdzio** [comment]
Siehe auch #86

**Comment by mdzio** [comment]
Die Umrechnung der Zeitstempel (Lokalzeit <-> Unixsekunden) für Grafana ist mit den Standardmitteln der H2Database nicht möglich.

**Comment by mdzio** [comment]
Es wurden zwei neue SQL-Funktionen UNIX_TO_TS und TS_TO_UNIX implementiert, die die korrekte Umrechnung durchführen. Sie sind auch sehr performant.
