### ISSUE TITLE
Überprüfung auf neue Version im Add-On anpassen

### ISSUE THREAD

**Issue by pennynet** [mdzio/ccu-historian#403]
Liebe Leute,

habe auf 3.5.0 aktualisiert, werde aber immer wieder darauf hingewiesen, dass eine neues Update vorliege. Habe ich da was falsch gemacht? Vielleicht muss ja nur das "v" im Namen der Update-Datei auf dem Server verschwinden (siehe screenshots)?

Grüße
[screenshots.pdf](https://github.com/mdzio/ccu-historian/files/13801168/screenshots.pdf)

**Comment by Baxxy13** [comment]
Passiert halt. 
[Selbsthilfe](https://homematic-forum.de/forum/viewtopic.php?f=38&t=81135#p790741)

**Comment by pennynet** [comment]
Passt, danke!

**Comment by mdzio** [comment]
Ich habe die Versionskennzeichnung auf GitHub angepasst. Mit einem "v" am Anfang entspricht sie nun dem Git-Standard. 

Die Update-Überprüfung beim Add-On muss noch angepasst werden.
