### ISSUE TITLE
Interpolierte Darstellung eines FLOAT-Wertes trotz eingestellter Delta-Kompression

### ISSUE THREAD

**Issue by 0x6e657775736572** [mdzio/ccu-historian#406]
Hallo,

ich hoffe ich habe nichts übersehen aber ist es so gewollt, dass ein POWER-Wert trotz Delta-Kompression als interpolierter Graph angezeigt wird? Ich habe einen recht hohen relativen Schwellwert wodurch es zu sehr verzerrten Graphen kommt.

LG

**Comment by mdzio** [comment]
Das Problem kann ich bei mir nicht nachstellen. Bitte noch einmal prüfen und folgendes Skript in der Skriptumgebung des CCU-Historian ausführen:
```
database.getDataPoint(new DataPointIdentifier("BidCos-RF.LEQxxxxxxx:2.POWER"))
```
(xxxxxxx durch die tatsächliche Seriennummer ersetzen.)

Die Ausgabe dann hier wieder zeigen.

**Comment by 0x6e657775736572** [comment]
Danke für die Rückmeldung. Ich hätte mein Anliegen wohl besser noch präziser schildern sollen: Die interpolierte Darstellung betrifft nur den Graph in H2-HighChart. Dort werden, so wie es scheint, alle Linien zwischen zwei Datenpunkten geglättet.

Mittels welches Befehls, lässt sich diese Verarbeitung nur auf Swinging-Door-Datenpunkte anwenden?

Ich erinnere mich, dass eine frühere Version von H2-HighChart dies so nicht gemacht hat. Float-Datenpunkte wurden dann auch in HighChart eckig und linear dargestellt, genau so wie in der Trend-Darstellung.

LG

**Comment by mdzio** [comment]
Ja, da musst Du Dich an @wakr70 wenden, bzw. [hier](https://github.com/wakr70/CCU-Historian-HC) ein Ticket aufmachen. Dann schließe ich den Eintrag.
