### ISSUE TITLE
Fehlermeldung in der Meldungsanalyse und Datenpunktkonfiguration

### ISSUE THREAD

**Issue by ghost** [mdzio/ccu-historian#407]
Ich habe bei meine Installation (Docker) jetzt schon etwas länger folgende Fehlermeldung:

Fehler:

Table "D_BIDCOS_RF_QEQ1118195_4_FAULT_REPORTING" not found; SQL statement: SELECT TS, "VALUE", STATE FROM D_BIDCOS_RF_QEQ1118195_4_FAULT_REPORTING WHERE TS>=? AND TS<? ORDER BY TS [42102-214]

Update habe ich schon gemacht und grundsätzlich funktioniert auch die Daten Aufzeichnung, allerdings ist die Datenpunktkonfiguration nicht vollständig geladen.

**Comment by mdzio** [comment]
Anscheinend ist die Datenbank etwas beschädigt. Es wird auf eine Tabelle verweisen, die anscheinend nicht mehr existiert. Dies kann passieren, wenn die Datenbank beispielsweise durch einen Stromausfall beschädigt wird.

Eventuell hilft das Recovery-Werkzeug, um die Datenbank zu reparieren. [Eine Anleitung ist hier zu finden.](https://github.com/mdzio/ccu-historian/wiki/Tipps-&-Tricks#wiederherstellung-einer-defekten-datenbank)

Alternativ könnte über die Datenbank-Konsole (_Werkzeuge_ → _Datenbank_) versucht werden, die falschen Einträge zu entfernen. Das einzugebende Kommando müsste wie folgt aussehen:
```
DELETE FROM DATA_POINTS WHERE TABLE_NAME='D_BIDCOS_RF_QEQ1118195_4_FAULT_REPORTING'
``` 
Vorher natürlich ein Backup erstellen.

**Comment by mdzio** [comment]
Steht das Problem weiterhin an? Dieser Eintrag kann dann bei Bedarf weider eröffnet werden.
