### ISSUE TITLE
JSON-RPC 

### ISSUE THREAD

**Issue by wakr70** [mdzio/ccu-historian#411]
Hallo Mathias,

ich teste derzeit die Expression und verwende da gerne auch die methode "executeScript" über die JSON-RPC Schnittstelle. Leider bekommt man da nur für Result immer einen String. 

Gibt es auch die Möglichkeit, hier eine json zubekommen wie bei methode "getTimeSeriesRaw" ?

{"id":"1109_1711821635351","result":{"timestamps":[1711216999000,1711217723000,],"values":[145.0,143.0,],"states":[6,6],"dataPoint": ...}

{"id":123,"result":"2024-03-23 20:00:00.000, 6386.27, 2\n2024-03-23 21:00:00.000, 6916.036568055555, 2\n"}

LG wak

**Comment by mdzio** [comment]
Dafür gibt es bereits die neue Methode `calculateTimeSeries`. [Die Dokumentation ist hier zu finden.](https://github.com/mdzio/ccu-historian/wiki#calculatetimeseries-zeitreihenberechnung-ausführen)

`executeScript` kann immer nur Text zurückgeben.

**Comment by wakr70** [comment]
Danke für den Tip, hab ich noch nicht gekannt, Doku lesen hilft ! Muß ich mal testen, ob das auch so funktioniert mit längeren Formeln, wie execute Script!

**Comment by wakr70** [comment]
Hallo Mathias, habe es jetzt einwenig getestet und funktioniert super!

Eines konnte ich aber nicht lösen, da ja der .READ(...) jetzt automatisch am Ende ist, kann ich die Zeitreihe nicht mehr bearbeiten. 

Oder gibt es eine Möglichkeit bei einem Counter den Delta von einem Tag auf den anderen zu ermitteln, um daraus Tagesverbräuche zu ermitteln?

**Comment by mdzio** [comment]
Das kannst Du so folgendermaßen erreichen:
* Als erstes eventuelle Zählerrückstellungen korrigieren: `dp.counter()`
* Den Zählerwert jeweils am Tagesanfang ermitteln. Das ist immer der kleinste Wert: `.minimum(daily())`
* Dann differenzieren: `.differentiate()`
* `differentiate()` gibt die Änderungsgeschwindigkeit pro Stunde aus. Für die Tagesdifferenz muss dann noch mit 24 multipliziert werden: `*24`

Insgesamt also: `(dataPoint(xy).counter().minimum(daily()).differentiate()*24).read(begin, end)`

Getestet habe ich es nochn nicht.

**Comment by wakr70** [comment]
Danke für den Hinweis, mit differentiate konnte ich bisher noch nix anfangen, das sieht schon elegander aus, wie meine Lösung
:-)
