### ISSUE TITLE
Fehler bei Installation

### ISSUE THREAD

**Issue by JohnnyTribi** [mdzio/ccu-historian#415]
Ich wollte die neue Version 4.0.0 installieren. Aktuell habe ich 3.6.0 installiert. Wenn ich die Datei über den Browser installieren möchte bekomme ich folgende Meldung: 

Error (101)
Ein unerwarteter Fehler ist während der Addon-Installation aufgetreten. Bei der hochgeladenen Datei handelt es sich entweder nicht um ein Addon-Archiv, ist defekt oder ist für eine andere Hardware vorgesehen. Bitte versuchen Sie es erneut oder kontaktieren Sie den Autor des Addons.

Was könnte ich tun?

**Comment by mdzio** [comment]
Soll der CCU-Historian als Add-On auf der CCU installiert werden?
Hast Du dafür die Datei ccu-historian-addon-4.0.0.tar.gz verwendet?

**Comment by JohnnyTribi** [comment]
RaspberryMatic ist aktuell: 3.75.6.20240316
Hardware ist CCU 3
CCU-Historian ist direkt installiert.
CCU3/RaspberryMatic/YAHM/piVCCU-Distribution: ccu-historian-addon-v4.0.0.tar.gz

CCU Historian läuft schon seit ein paar Monaten bei mir in diese Konstellation. Im Moment läuft bei mir 3.6.0

**Comment by mdzio** [comment]
Besteht das Problem weiterhin? Dann kann dieser Eintrag noch einmal geöffnet werden.
