### ISSUE TITLE
unable to run 4.0.0 with current jre

### ISSUE THREAD

**Issue by Elbe122** [mdzio/ccu-historian#418]
Starting ccu-historian.exe 4.0.0 throws the following error: Exception in thread "main" java.lang.UnsupportedClassVersionError: mdz/ccuhistorian/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

I am no expert, but it looks like the new ccu-historian requires java 11 and the current jre ist java 8. So far I am unable to find jre 11.

**Comment by mdzio** [comment]
The CCU Historian should work with all Java versions from 11 to 21. You can find corresponding JREs for many platforms on [Adoptium](https://adoptium.net).
