### ISSUE TITLE
Docker-Image für eine einfache Installation auf unterschiedlichsten Plattformen

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-historian#42]
* Docker ist u.a. für Raspberry Pi, Linux, Windows und den NAS von Synology und QNAP verfügbar.

**Comment by tzahari** [comment]
Hallo mdzio,
Ich erstelle bereits die Docker Images siehe https://github.com/tzahari/CCU-Historian-for-Docker
Diese sind auf Docker Hub unter https://hub.docker.com/r/tzahari/ccu-historian/ zu finden.
Wie wollen wir mit den Thema Docker Images weitermachen?
Viele Grüße Thomas

**Comment by mdzio** [comment]
Hallo Thomas,

dass Du ein Docker-Image für den CCU-Historian zur Verfügung stellst, finde ich gut. Ich bin auch bereits vor längerer Zeit darauf gestoßen.

Die Idee ist nun, dass mit jeder neuen Version vom CCU-Historian **automatisch** eine neue Version des Docker-Images erstellt wird. Dies wird erst jetzt langsam möglich, da das Bauen vom CCU-Historian immer weiter automatisiert wird. Ein erstes Ergebnis ist, dass die Distribution für RasberryMatic/YAHM ohne manuellen Eingriff gleichzeitig erstellt wird.

Dies könnte so umgesetzt werden, dass die Build-Skripte für das Docker-Image auf das [Build-System Apache Ant](https://ant.apache.org) umgestellt werden. Dieses wird zum Bauen des CCU-Historians verwendet.

Gruß
Mathias

**Comment by mdzio** [comment]
Ja, ich werde dann das Bauen des Docker-Images in mein CCU-Historian-Repository integrieren. Dein Repository habe ich bereits geforked. Es wird aber noch etwas dauern, bis ich es integriert habe.

Es ist Schade, dass Du das Projekt aufgeben musst. Aber das Problem mit der Zeit kann ich sehr gut nachvollziehen. Vielen Dank für die Vorarbeit!

Viele Grüße
Mathias

**Comment by x-jokay** [comment]
Hellu

Da @tzahari das docker-image nicht mehr weiterführt, habe ich vorläufig selber eins aufgesetzt.

[xjokay/ccu-historian](https://hub.docker.com/r/xjokay/ccu-historian)

Es wäre gut, wenn es ein offizielles docker-image gäbe, erstellt aus diesem repo.

Vielleicht kann ich dabei behilflich sein?

**Comment by mdzio** [comment]
Seit einigen Wochen arbeitet auch Sascha Müller an automatisch erstellten Docker Images: [sacomedv/ccu-historian](https://hub.docker.com/r/sacomedv/ccu-historian)

Er stellt einen Build-Server zur Verfügung. Für alle freigegeben Versionen und sogar für jeden Commit werden automatisch Docker-Images erstellt.

Dass ich selber ein "offizielles" Docker-Image anbiete, halte ich daher für nicht mehr notwendig. Ich kann dann mehr Zeit in die Weiterentwicklung des CCU-Historians stecken.

Mitstreiter werden immer gesucht. Ich kann gerne einen Kontakt zwischen Euch herstellen.

**Comment by x-jokay** [comment]
Gut zu wissen, danke für die Info.

Leider kann ich für das docker-image `sacomedv/ccu-historian` kein repo finden.
Scheint wohl closed-source zu sein? :wink:

**Comment by TheMiller2015** [comment]
Hallo! Das Repo ist öffentlich und sollte unter diesem Link für alle aufrufbar sein (https://hub.docker.com/r/sacomedv/ccu-historian). Die Images werden vollautomatisch gebaut und sind daher immer aktuell und getagged (master, dev, beta, [spezifische version]). Über eine Rückmeldung, ob die Images erreichbar sind, würde ich mich freuen. Wir versuchen, die Images noch mit weiteren Funktionen auszustatten. Spezielle Images für die Raspberrys (arm) werden wir auch zur Verfügung stellen, in absehbarer Zeit.

**Comment by x-jokay** [comment]
Unter `repo` verstehe ich eigentlich ein repository mit dem source code (für alle verfügbar und der Möglichkeit `PRs` machen zu können) so wie GitHub oder Gitlab das ermöglicht und nicht unbedingt das fertig erstellte docker image ohne Dockerfile und ohne Reproduzierbarkeit durch jedermann 😉

**Comment by mdzio** [comment]
Aus Zeitgründen habe ich mich entschieden, erst einmal das Bauen eines Docker-Images nicht mit in das Haupt-Repository aufzunehmen. Ich kann aktuell nicht die Pflege eines "offiziellen" Docker-Images übernehmen. Die Docker-Images sollten in ihren separaten Repositories weiter gepflegt werden.

**Comment by f00f** [comment]
Für alle, die auf der Suche sind: das einzig noch gepflegte Image scheint das von @x-jokay zu sein.
Danke schonmal, ich probier's gleich mal aus.

**Comment by mdzio** [comment]
Da es ein gut gepflegtes Docker-Image gibt, will ich diesen Eintrag schließen. Und mit etwa 50.000 Pulls ist es auch recht beliebt. Vielen Dank an @x-jokay.

**Comment by x-jokay** [comment]
@mdzio Ich würde nach wie vorne gerne das Build für den Docker container im offiziellen Repo sehen 😉 

Ich habe heute noch das Builden via [GitHub action](https://github.com/x-jokay/docker-ccu-historian/blob/main/.github/workflows/dockerhub.yml) für ein Multi-Platform build eingerichtet, so dass jetzt alle diese Platforms supported sind:

- linux/amd64
- linux/arm/v7
- linux/arm64/v8
- linux/ppc64le
- linux/s390x

Somit läuft es nun auch auf einem RaspberryPi.

**Comment by mdzio** [comment]
@x-jokay Gut, dann machen wir das. Soll ich Dich für das Repo als Collaborator eintragen? Dann kannst Du alles in das Verzeichnis `dist-docker` packen.

**Comment by mdzio** [comment]
@jokay Es wurde bemerkt, dass Dein Docker-Image auf GitHub und Docker-Hub archiviert worden ist. Ich nehme an, dass das für unbestimmte Zeit ist. Auf jeden Fall danke ich Dir für die Bereitstellung des Docker-Images über die Jahre.

**Comment by mdzio** [comment]
@jokay Ja, das muss ich mal angehen.
