### ISSUE TITLE
Mindestgröße von Diagrammen nicht kompatibel mit Mobilgeräten

### ISSUE THREAD

**Issue by martinrieder** [mdzio/ccu-historian#420]
Wenn ich mir neue Diagramme auf dem Handy generiere, dann wird die Breite des Diagramms auf 640px gesetzt. Damit sind diese ungefähr doppelt so breit wie mein Display (hochkant) und ich muss scrollen. Natürlich ist das sehr von der Hardware abhängig, aber ich sehe keine Notwendigkeit für diese Beschränkung in den folgenden beiden Zeilen im Script am Ende der Datenpunktliste:
```javascript
const tw=Math.max(640, vw-64);
const th=Math.max(240, vh-240);
```
Die Höhe und Breite des Diagramms lassen sich nachträglich ändern. So stelle ich bei meinem Gerät meist 320 x 660 ein. Bisher konnte ich dabei keine Probleme mit der Darstellung des Diagramms feststellen. Ich schlage vor, den Wert 640 ebenfalls auf 240 zu setzen, womit das Diagramm quadratisch wird. Damit sollte es quasi unabhängig von der Bildschirmausrichtung passen.

Zusätzliche Frage: Die aktuelle Implementierung diese Scripts bewirkt, dass man die darin enthaltenen Funktionen erst nutzen kann, sobald die komplette Seite geladen ist. Das scheint mir auch, als wäre das so gewollt, wobei ich auch hier die technische Notwendigkeit nicht sehe. Muss dieses Script immer am Ende der Seite ausgeführt werden oder könnte man es auch in eine externe Datei auslagern, die dann asynchron geladen wird?

**Comment by mdzio** [comment]
Ich werde mal die Mindestbreite auch auf 240 Pixel reduzieren.

Das Skript referenziert die Datenpunkttabelle. Es muss also erst nach dem Laden der Tabelle ausgeführt werden.

**Comment by martinrieder** [comment]
Wow, die vielen Dank! Mit so einer schnellen Reaktion hatte ich nicht gerechnet.
