### ISSUE TITLE
Kanalname wird nicht angezeigt

### ISSUE THREAD

**Issue by Lemmis** [mdzio/ccu-historian#423]
Hallo!

Nach einer frischen Installation des CCU-Historians auf meiner CCU3 werden die Kanalnamen nur nach ihrer Adresse angezeigt, nicht jedoch deren vergebene Kanalnamen oder als Fallback der DeviceName. Ich habe in der Dokumentation leider nichts diesbezüglich gefunden, deshalb bin ich mir auch nicht sicher, ob es sich nicht lediglich um ein Konfigurationsproblem handelt.
Für ein Beispiel hier einmal ein Screenshot der CCU-Historian:
![ccu_screenshot](https://github.com/user-attachments/assets/01383e9f-0385-4cc2-9bf1-20d9bbb6f3a2)
Und hier das Ergebnis, welches die XML-Schnittstelle für das Device zurück liefert:
![state xml](https://github.com/user-attachments/assets/dccdfb98-549a-4e1b-b032-74e24928dce6)

Ist dies ein gewolltes Verhalten? Wenn nicht, und ich einfach etwas in der Konfiguration übersehen habe, bitte ich um Entschuldigung!
Danke und viele Grüße

**Comment by mdzio** [comment]
Die Kanalnamen sollten inzwischen angezeigt werden. Siehe auch: [Gerätedatenpunkte werden nur mit der Seriennummer und nicht mit dem Kanalnamen aufgelistet](https://github.com/mdzio/ccu-historian/wiki/Tipps-&-Tricks#ger%C3%A4tedatenpunkte-werden-nur-mit-der-seriennummer-und-nicht-mit-dem-kanalnamen-aufgelistet)
