### ISSUE TITLE
jsonrpc does not work as expected for ccu-historian-dsm7-4.0.1.3.0-noarch.spk

### ISSUE THREAD

**Issue by alpha0x1omega** [mdzio/ccu-historian#425]
When I run jsonrpc for setting value with dsm7-4.0.1.3.0-noarch.spk, I get as response "method not found". After switching back to dsm7-3.4.0.3.0-noarch.spk it works again

**Comment by mdzio** [comment]
This functionality was removed in v3.6.0, see issue #405.
