### ISSUE TITLE
Schnelle Änderungen von Werten

### ISSUE THREAD

**Issue by ojnde** [mdzio/ccu-historian#428]
Ich habe Änderungen von false nach true, die nur für wenige Sekunden true bleiben. In der Mehrzahl der Fälle, werden sie vom Historian nicht registriert. Kann man irgendwo Abfrageintervalle definieren?

**Comment by mdzio** [comment]
Ich nehme an, dass es sich um Systemvariablen handelt. Diese werden zyklisch abgefragt. Die Option zum Setzen der Zykluszeit ist `devices.device1.sysVarDataCycle=30000`. Der Wert ist in Millisekunden. Ein Wert unter 3000 verursacht aber eine höhere CPU-Last auf der CCU.

[Siehe auch Handbuch.](https://github.com/mdzio/ccu-historian/wiki#optionen-f%C3%BCr-eine-ccu123-und-raspberrymatic-mit-funkmodul)

**Comment by mdzio** [comment]
Ich schließe den Eintrag mal hier. Wenn noch Fragen offen sind, einfach hier wieder einen Beitrag erstellen.
