### ISSUE TITLE
Delta-Kompression auch bei einer bestehen Datenbank hinterher einschalten 

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-historian#429]
Hallo zusammen,

nur kurz dazu eine Frage: Kann ich die Delta-Kompression auch bei einer bestehen Datenbank hinterher einschalten und die so die Datenbank verkleinern? Ich habe das am Anfang verschlafen und eine jetzt eine Datenbank, die "mikrige" 300GB groß ist. Ich habe das Skript, das die Datenpunkte entsprechend umkonfiguriert, bereits laufen lassen.

Danke für das großartige Tool!

FantOEM

_Originally posted by @FantOEM in https://github.com/mdzio/ccu-historian/issues/421#issuecomment-2395305594_

**Comment by FantOEM** [comment]
Danke fürs Verschieben, da gebe ich Dir Recht.

**Comment by mdzio** [comment]
Das kann nachträglich über die Kommandozeilenoption `-recalc` erfolgen. Danach sollte auch noch einmal ein `-compact` durchgeführt werden, um die Datenbank zu verkleinern.

[Siehe auch Handbuch "Startparameter"](https://github.com/mdzio/ccu-historian/wiki/#startparameter)

**Comment by FantOEM** [comment]
Ich probiere hier schon eine ganze Weile dran rum. Aber die Datenbank bleibt riesig, da ändert sich nichts.

**Comment by mdzio** [comment]
Hast Du denn auch ein `-recalc` und `-compact` durchgeführt?

**Comment by FantOEM** [comment]
Ja, ich nutze diese Befehle:

(java -jar ./ccu-historian/ccu-historian.jar -config ./ccu-historian/ccu-historian.config -recalc) && (java -jar ./ccu-historian/ccu-historian.jar -config ./ccu-historian/ccu-historian.config -compact)

Vorher wird der ccuhistorian beendet.

**Comment by mdzio** [comment]
Je nach Einstellung des Log-Levels (z.B. Level.DEBUG) müssten dann auch entsprechende Meldungen im Log auftauchen.
Beispiele:
```
Starting recalculation of compressed data points
```
oder
```
Starting compaction of database
```

Wenn diese Meldungen auftauchen und die Datenbank nicht kleiner wird, dann muss bei den Kompressionen der einzelnen Datenpunkte noch etwas angepasst werden (z.B. Delta erhöhen).

**Comment by FantOEM** [comment]
Ich habe es so gemacht (natürlich mit def testRun=false):

<
*
Autokonfiguration Deltakompression V1.0.0
Wichtig: Vor Anwendung des Skripts ein Backup der Datenbank erstellen!
*/

// *** Konfiguration ***

// Testlauf durchführen? Bei einem Testlauf wird die Datenbank nicht verändert.
// (Ja: true, Nein: false)
def testRun=true

// Sollen bereits konfigurierte Vorverarbeitungen überschrieben werden? 
// (Ja: true, Nein: false)
def overrideAll=true

// Sollen auch nicht geänderte Datenpunkte aufgelistet werden?
// (Ja: true, Nein: false)
def logNotChanged=false

// *** Skript ***
println "*** Autokonfiguration Deltakompression V1.0.0 ***"
println "Testlauf: ${testRun?"Ja":"Nein"}"
println "Alle überschreiben: ${overrideAll?"Ja":"Nein"}"
println "Alle auflisten: ${logNotChanged?"Ja":"Nein"}"

database.dataPoints.each { dp ->
  
  def currentCompr=getPreprocType(dp)
  def currentParam=getPreprocParam(dp)
  if (currentCompr!=PreprocType.DISABLED && !overrideAll) {
    println "\n$dp.displayName"
    println "  Vorhandene Vorverarbeitung wird nicht überschrieben: $currentCompr, $currentParam"
    return
  }
  
  def type=dp.attributes.type
  def ident=dp.id.identifier
  def compr=currentCompr
  def param=currentParam
  
  if (type=="ACTION") {
    compr=PreprocType.DISABLED
    param=0.0
	
  } else if (type in ["BOOL", "INTEGER", "ENUM", "ALARM"]) {
    compr=PreprocType.DELTA_COMPR
    param=0.5  
	
  } else if (type=="FLOAT") {
    compr=PreprocType.SWD_COMPR
    param=0.5  
	
  } else if (type=="STRING") {
    compr=PreprocType.DELTA_COMPR
    param=0.0
  }
  
  if (currentCompr!=compr || currentParam!=param) {
    println "\n$dp.displayName"
    println "  Vorverarbeitung wird abgeändert: $compr, $param"
    if (!testRun) {
      dp.attributes.preprocType=compr.ordinal()
      dp.attributes.preprocParam=(compr==PreprocType.DISABLED ? null : param)
      database.updateDataPoint(dp)
    }
  } else {
    if (logNotChanged) {
      println "\n$dp.displayName"
      println "  Vorverarbeitung muss nicht geändert werden: $compr, $param"
    }
  }
}

def getPreprocType(dp) {
  int idx=(dp.attributes.preprocType as Integer)?:PreprocType.DISABLED.ordinal()
  if (idx<0 || idx>=PreprocType.values().length) {
    throw new Exception("Invalid preprocessing type in database: "+idx)
  }
  PreprocType.values()[idx]
}

def getPreprocParam(dp) {
  (dp.attributes.preprocParam as Double)?:0.0
}
>

**Comment by FantOEM** [comment]
Sorry, irgendwie klappt die Code-Option nicht...

**Comment by mdzio** [comment]
Due hast aber schon zumindest die Option `def testRun=false` gesetzt?

**Comment by FantOEM** [comment]
Ja, habe ich.
