### ISSUE TITLE
Lokale Speicherung des aktuellen/letzten Trend-Diagram als PNG File.

### ISSUE THREAD

**Issue by cmoehler** [mdzio/ccu-historian#54]
In Zusammenhang mit der Visualisierung mittels AIO CREATOR NEO von Mediola wäre es enine enorme Vereinfachung wenn das aktuell angefragte Trend-Diagramm auch lokal als .png File gespeichert würde. Somit wäre es möglich das AIO NEO Webseitenelement, welches eine fest zugewiesene URL verlangt, auf diese PNG-Datei zeigen zu lassen. Dann könnte mit nur einer Fernbedienungsseite die Diagramme manipulieren indem man die Trendanfrage mittels http Request an Historian sendet und dann das Webseitenelement mittels Refresh neu anzeigen lässt. Richtig cool wäre es dann noch wenn schon bei der Anfrage eines neuen Diagramms (trend.gy) die PNG-Datei des letzten Charts mit einer konfigurierbaren PNG Datei überschrieben würde. So würde diese im Webseitenelement der Fernbedienung angezeigt wenn die Erzeugung des angefragten Trends etwas Zeit in Anspruch nimmt.

Ich könnte mir vorstellen, dass ich nicht der Einzige wäre welchem diese Funktionalität sehr gefallen würde.

Vorschlag/Wunsch:
- Configuration: PNG local (Ein/Aus)  -> eventuell bei Ein=Client Response aus
- [Configuration: Response an Client (Ein/Aus) OPTIONAL]
- Configuration: Chart PNG-Datei (Pfad Speicherort)
- Configuration: Name der Chart-PNG-Datei (Filename)
- Configuration: default PNG-Datei (Vollständiger Pfad auf die Datei)

- Code: Default PNG schreiben beim eintreffen einer Anfrage in der trend.gy
- Code: Chart PNG schreiben wenn das Image erzeugt wurde
- Code: Client Response Ein/Aus

**Comment by mdzio** [comment]
Die Ausführungen habe ich wie folgt verstanden. Ist das richtig?

In NEO gibt es zwei unterschiedliche Elemente mit folgenden Funktionen:
1. HTTP-Request abzusetzen
2. Web-Seite mit einer nicht veränderlichen Adresse anzeigen

Es soll also mit (1) eine Trend-Datei auf dem CCU-Historian-Web-Server generiert werden. Diese kann dann mit (2) angezeigt werden.

Mögliche Lösung:
Ein neues Skript /query/trendsave.gy, dass einen Trend generiert und lokal auf dem CCU-Historian-Rechner abspeichert. Der Dateiname kann über die Adresse mitgegeben werden. Die Datei kann im webapp-Verzeichnis des Web-Servers generiert werden, wodurch sie durch einen weiteren HTTP-Zugriff gelesen werden kann.

Es sollte aber nochmal ermittelt werden, wie viele Anwender so eine Funktionalität benötigen, eventuell durch eine Nachfrage im HomeMatic-Forum. Zu prüfen ist außerdem, ob NEO selbst nicht auch andere Möglichkeiten zur Lösung anbietet.

**Comment by cmoehler** [comment]
Ich habe diese Funktionalität bei Mediola angefragt weil ich dachte ich stehe einfach auf dem Schlauch. Hier der Link zum Beitrag im Mediola Forum: [Anfrage bei Mediola](http://answers.mediola.com/2195621/Webseiten-Element-per-Button-eine-neue-URL-zuweisen?qid=df05fe29-f935-4b6e-4ccf-585e38f08b69)

Mann könnt vermutlich so eine Funktionalität in NEO auch erreichen indem man statt eins Webseiten-Element eine Kamera-Element verwendet. Dieses lässt sich dann im Prinzip mittels http Requests steuern. Um eigene "Kameras" in NEO erstellen zu können, würde aber ein weiteres kostenpflichtigs PlugIn notwendig. Mann könnte dann für jeden Trend den man anzeigen möchte eine "Kamera-Funktion" definieren und diesen dann entsprechend mittels Button aufrufen. Ich habe das PlugIn jedoch nicht erworebven da es keine Angaben darüber gib wie viele "Kamera-Funktionen" für eine "Kamera" erstellt werden können.

Eine weitere Möglichkeit wäre, wie auch schon im Mediola Forum angeregt wurde, ein eigener Web-Server.  Dies wäre dann der nächste Schritt wenn die angefragte Funktionalität nicht in Historian selbst realisiert werden könnte.

**Comment by mdzio** [comment]
Die Funktionalität ist schon sehr speziell. Ich lasse dieses Issue mal offen, die Priorität ist allerdings niedrig.
Eventuell äußern sich noch andere NEO Benutzer dazu.

**Comment by cmoehler** [comment]
Ich denke mal die meisten NEO Benutzer gehen halt den Umwweg über einen eigenen Web-Server. Die Lösung mit dem lokalen .PNG würde diesen Aufwand elegant umgehen.
Aber gut, wenn sonst niemand den Vorteil darin sieht, baue ich mir die lokate Speicherung mit statischem Pfad hald bei mir direkt ins trend.gy ein.

**Comment by mdzio** [comment]
Wenn Du eine Lösung gefunden hast, kann ich sie gerne auf http://ccu-historian.de/index.php?n=CCU-Historian.Anleitungen vorstellen. Wenn dann noch weitere Anfragen kommen, versuche ich sie in den CCU-Historian einzubauen.

Meine Zeit ist halt sehr begrenzt. Bei den ca. 40 Verbesserungsvorschlägen muss schon stark gewichten.

**Comment by cmoehler** [comment]
Da meine Lösung mit einem statischen Pfad in der trend.gy realisiert ist, macht das wohl keinen Sinn. Auch meine Zeit ist begrenzt ;-)
