### ISSUE TITLE
Exception "Invalid BIN-RPC header start"

### ISSUE THREAD

**Issue by michaelotto** [mdzio/ccu-historian#56]
Hallo,

ich habe CCU-Historian frisch installiert (Ubuntu 16.04), CCU2, Port 2011 ist offen.

webServer.historianAddress und devices.historianAddress sind gesetzt.

Ich habe ausschließlich Systemvariablen als Datenpunkte, denn die Übermittlung der Gerätedatenpunkt funktioniert offenbar nicht. Ich bekomme folgende Exception:

2017-03-21 10:29:32|SEVERE |Exception: Invalid BIN-RPC header start: [81, 85, 73]

Einen einzigen Gerätedatenpunkt (mit dem ich nichts anfangen kann), bekomme ich allerdings:

2017-03-21 10:35:29|FINER  |Database: Getting data point with id BidCos-RF.CENTRAL.PONG
2017-03-21 10:35:29|FINE   |Database: Inserting (Tue Mar 21 10:35:29 CET 2017, hm-rpc.0, 2) into C_BIDCOS_RF_CENTRAL_PONG

Was kann da kaputt sein?

**Comment by michaelotto** [comment]
Konkretisierung:

Die Exception gibt es.

Dass ich keine Geräte sehe, liegt wohl daran, dass CCU-Historian keine Homematic IP Geräte unterstützt, bzw. keine XML-RPC-API mehr und ich praktisch nur Homematic IP habe. Schade.

**Comment by mdzio** [comment]
Um die Ursache der Exception zu klären, bitte eine detaillierte Log-Datei, wie im Handbuch Abschnitt 8.1 beschrieben, erstellen und mir zuschicken.

HomeMatic IP-Geräte werden ab V1.1 unterstützt, die zurzeit bei mir noch im Testbetrieb ist. Die Version sollte in den nächsten Tagen erscheinen.

**Comment by michaelotto** [comment]
Ich wollte mich nur kurz zurückmelden. Ich habe die neuste Beta-Version installiert. Damit kann ich den Fehler nicht mehr reproduzieren. Außerdem funktionieren alle Homematic-IP-Geräte wie gewünscht! Besten Dank und beste Grüße

**Comment by mdzio** [comment]
Vielen Dank für die Rückmeldung.
