### ISSUE TITLE
Auswahlmöglichkeit für alle angezeigten Datenpunkte

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-historian#57]
Ich habe einen Verbesserungsvorschlag zur Bediener-Oberfläche. Und zwar würde ich mir wünschen, dass in der "Übersicht Datenpunkte" nach dem Filtern alle aktuell angezeigten Datenreihen mit einem Klick ausgewählt werden können. Ich lasse mir öfter z.B. die Datenreihen Temperatur oder Setpoint oder ValveState für mehrere Räume gleichzeitig untereinander darstellen. Nach dem Filtern muss ich aber jede Datenreihe separat anklicken. Es wäre schön, wenn z. B. in der "Übersicht  Datenpunkte" ein Auswahlfeld in der Spaltenüberschrift "Ausw" ergänzt würde, mit dem alle aktuell gefilterten Datenreihen mit einem Klick ausgewählt werden können (s. Anhang, grünes Kästchen). 

Beispiel:
![zwischenablage01](https://cloud.githubusercontent.com/assets/24684496/24217137/16bfe3be-0f3f-11e7-8810-41642a51a1cd.jpg)

**Comment by mdzio** [comment]
Für die Tabellenfilterung wird eine fertige Komponente verwendet. Das Auswahlkästchen an der angegebenen stelle unterzubringen wird daher schwierig. Grundsätzlich sollte die Funktionalität möglich sein.

**Comment by drMaxxi** [comment]
Ist es in der Zwischenzeit Irgendwie möglich alle Datenbunkte auszuwählen? Es würde wirklich viel Arbeit sparen.

**Comment by mdzio** [comment]
Ja, das ist seit V2.0.0beta2 möglich.
![zwischenablage01](https://user-images.githubusercontent.com/24684496/49179975-cce20600-f353-11e8-8d5c-85a9c0d07950.png)

**Comment by drMaxxi** [comment]
Danke! Fein wäre es auch in der Datenpunktkonfiguration. Ich würde gerne das logging aller Datenpunkte bis auf das der Wetterstation deaktivieren.

**Comment by cmoehler** [comment]
Ja, das wäre für die Datenpunktkonfiguration echt hilfreich!!!
