### ISSUE TITLE
Class-Path aus manifest.mf wird mit OpenJDK nicht (richtig) verwendet / Could not initialize class org.jfree.chart.JFreeChart

### ISSUE THREAD

**Issue by tzahari** [mdzio/ccu-historian#71]
Hallo Mathias,
mir ist gerade aufgefallen, dass wenn ich CCU-Historian mit
`java -jar ccu-historian.jar`
starte, werden keine Graphen mehr angezeigt. 

Stattdessen tauchen im Logfile folgende Meldung auf:
`SEVERE |Exception: Could not initialize class org.jfree.chart.JFreeChart`

Scheinbar ignoriert OpenJDK die ClassPath Angabe in der Manifest Datei.

Viele Grüsse
Thomas

**Comment by mdzio** [comment]
Dass das OpenJDK die Class-Path-Angabe in der Manifest-Datei ignoriert, kann nicht verallgemeinert werden. Beispielsweise läuft bei mir der CCU-Historian unter OpenJDK (V1.8.0.141, CentOS Linux).

Der Class-Path kann zur Not auch über die Kommandozeile angegeben werden:
```
java -cp ccu-historian.jar;ccu-historian_lib/groovy-all-2.4.12.jar;ccu-historian_lib/bsf-2.4.0.jar;ccu-historian_lib/ivy-2.4.0.jar;ccu-historian_lib/servlet-api-2.4.jar;ccu-historian_lib/slf4j-api-1.7.25.jar;ccu-historian_lib/groovy-xmlrpc-0.8.jar;ccu-historian_lib/jetty-all-7.2.2.v20101205.jar;ccu-historian_lib/javax.servlet.jsp_2.1.0.v201004190952.jar;ccu-historian_lib/javax.el-api-1.1.2.jar;ccu-historian_lib/commons-cli-1.2.jar;ccu-historian_lib/jfreechart-1.0.19.jar;ccu-historian_lib/jcommon-1.0.23.jar;ccu-historian_lib/h2-1.4.196.jar;ccu-historian_lib/slf4j-jdk14-1.7.25.jar mdz.ccuhistorian.Main
```
