### ISSUE TITLE
Permanent hohe CPU Auslastung

### ISSUE THREAD

**Issue by Xento** [mdzio/ccu-historian#73]
Hallo 
ich nutze CCU-Hostorian schon eine Weil und ich habe bemerkt, dass die CPU Auslastung kontinuierlich auf ca 85% liegt.
Ist dies normal?
Welche Infos brauchst du noch von mir?

**Comment by Xento** [comment]
Konnte es jetzt reduzieren nachdem ich zwei Optionen eingestellt habe. Diese waren vorher auskommentiert.
Möglicherweise liegt die Auslastung an den Temperatursensoren die ich per CuxD angebunden habe.
Diese senden ja alle paar Sekunden ihre Werte.
historian.bufferCount=10000
historian.bufferTime=20*60*1000

**Comment by mdzio** [comment]
Noch ein paar Rückfragen:
* Auf welcher Hardware läuft der CCU-Historian?
* Wieviele Geräte oder Datenpunkte werden aufgezeichnet?
* Eventuell hilft auch eine detaillierte Log-Datei weiter bei der Ursachenforschung (s.a. Handbuch Abschnitt 8.1).

**Comment by Xento** [comment]
- CCU Historian läuft auf einem BananaPi mit ner SSD am Sata Anschluss.
- es sind aktuell 758 Datenpunkte
- werde später mal eine detailierte Logdatei anfertigen

Ich vermute fast, dass das Problem die durch die 8 per CuxD angebundenen Funkthermometer sind.
Diese senden ja alle 5 Sek oderso ihre Werte.
Habe bei denen auch die Delta Kompression mit 0.1 aktiviert.
Als ich dies noch nicht hatte war die Datenbank schon nach kurzerZeit über 8Gb groß.
Aktuell ist sie nur 1,7Gb groß.
Vielleicht sollte ich mal auf die Zeitliche Kompression umstellen.

**Comment by mdzio** [comment]
Bitte als Test unter "Verwaltung Datenpunkte" die vermuteten Datenpunkte auf "inaktiv" setzen. Ist dann die CPU-Auslastung dann immer noch hoch?

**Comment by Xento** [comment]
Hab die Datenpunkte auf inaktiv gesetzt, aber die Last bleibt bei ca 15% bis 20%.

**Comment by mdzio** [comment]
Eventuell hilft noch eine detaillierte Log-Datei weiter. Bitte eine, wie im Handbuch Abschnitt 8.1 beschrieben, erstellen und an die E-Mail-Adresse vom CCU-Historian schicken. Sie ist auf der ersten Seite des Handbuchs zu finden.

**Comment by Xento** [comment]
Hab den Arduino jetzt umprogrammiert so dass jeder Sensor nur ca einmal pro Minute zurückgegeben wird.
Die last ist aber immer noch bei ca 15 bis 20%. 
Ist das normal?

**Comment by mdzio** [comment]
Nein, das ist in der Regel nicht normal. Je nach Prozessor sollte die Auslastung unter 5% sein.

**Comment by Xento** [comment]
Hatte dir 2 Logdateien zu dem Problem geschickt.

**Comment by mdzio** [comment]
Laut den Log-Dateien hat der CCU-Historian immer mal wieder Pausen von einigen Sekunden. Dann sollte die CPU-Auslastung bei fast 0% sein. Wird die Last von 15% bis 20% wirklich vom CCU-Historian-Prozess erzeugt? Oder ist dies die Gesamtauslastung des Systems?

**Comment by Xento** [comment]
Ja steht so im top drin.

**Comment by Xento** [comment]
https://youtu.be/cEZH-J0Qwn4
Hier mal nen kurzes Video Zeitweise sogar über 80%

**Comment by mdzio** [comment]
Das Video ist überzeugend. Ich werde wohl mit einem Profiler in die Java-VM hineinschauen müssen, um weitere Erkenntnisse zu erlangen. Das werde ich bei Gelegenheit auf meinem System mal machen.

**Comment by mdzio** [comment]
Das Verhalten wurde ebenfalls auf [einer Synology-NAS](https://homematic-forum.de/forum/viewtopic.php?f=38&t=42800#p425803) beobachtet.

**Comment by mdzio** [comment]
Es ist anscheinend kein grundsätzliches Problem. Auf meinem Rechner (alter Core i7/Win 10/Java 10) liegt die Prozessorlast immer unter 1%. Wenn keine Wertänderungen kommen, dann liegt sie auch tatsächlich bei 0%. Eventuell liegt es an der verwendeten Java-VM.

**Comment by mdzio** [comment]
Ich habe die Prozessorbelastung ebenfalls auf einem Raspberry Pi festgestellt:
*  Raspberry Pi Model 2 B (4 Kerne, 900MHz, 1GB RAM)
* 10 Wertänderungen pro Sekunde (entspricht einer sehr großen HM-Installation)
* Belastung im Durchschnitt: 3%

Das Problem kann ich also zurzeit bei mir nicht nachstellen.

**Comment by Xento** [comment]
Habe mittlerweile meine Installation auf mein Synology NAS gezogen mit Docker.
Dort habe ich ca immer 5% Last

**Comment by mdzio** [comment]
Das hört sich schon besser an. Ich werde erst einmal die Fehlersuche auf Eis legen, bis weitere Hinweise, eventuell auch von anderen Anwendern, eintrudeln.

**Comment by joeduck** [comment]
Hallo. Gibts hier was neues? Was kann ich tun um den Fehler einzugrenzen? Sonst muss ich wieder auf docker umstellen... welches docker image empfiehlt ihr?

**Comment by mdzio** [comment]
Die meisten verwenden das folgende Docker-Image (von Thomas Zahari): https://github.com/tzahari/CCU-Historian-for-Docker

Da ich selber den Fehler nicht nachstellen kann, müsste jemand, bei dem der Fehler auftritt, mit speziellen Werkzeugen in den laufenden CCU-Historian hinein schauen. Ich weiß nicht, ob das jemand ohne Programmierer-Hintergrund hin bekommt:

1. Auf einem Desktop-Rechner das **Java SE 10 JDK** (Java 10 Development Kit) installieren.
2. Zum Start-Skript des CCU-Historians auf dem Raspberry Pi/Synology folgende Optionen hinzufügen: `-Dcom.sun.management.jmxremote -Djava.rmi.server.hostname=1.2.3.4 -Dcom.sun.management.jmxremote.port=1088 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false` (1.2.3.4 durch die IP-Adresse des Raspberry Pi/Synology ersetzen)
3. Vom **Java SE 10 JDK** das Program **Java Mission Control** (z.B. c:\Program Files\Java\jdk-8\bin\jmc.exe) starten.
4. Mit dem Raspberry Pi/Synology verbinden.
5. Seite **Threads** anzeigen. Häkchen bei **CPU Profiling** setzen. Threads nach **Total CPU Usage** sortieren.
6. Bildschirmfoto erstellen.

Dann kann das Problem weiter eingegrenzt werden. Ob die Ursache dann offensichtlich ist und behoben werden kann, ist aber nicht sicher.

**Comment by mdzio** [comment]
Keine Rückmeldung

**Comment by etofi** [comment]
Ich habe auf meinem Rasperry das gleiche Problem. Sobald ich CCU-Historian starte habe ich permanent 100% CPU Last. In TOP steht dann Java mit so hoher Auslastung.
Update von 1.b2 auf 2.0 Beta 3 hat auch nichts geändert.
Ich versuche die oben beschriebene Analyse zu machen

**Comment by mdzio** [comment]
Bitte den Wert vom "MVStore background writer" mal einige Stunden lang beobachten. Verwendest Du einen USB-Stick für die Datenbank? Es scheint so, dass der RaspberryPi für das Beschreiben vom USB-Stick generell sehr viel CPU benötigt. Bitte mal die CPU-Last während des Beschreibens des USB-Sticks mit einer großen Datei beobachten.

**Comment by etofi** [comment]
Ich kann jetzt bestätigen dass dieses Problem bei großen Datenbanken Auftritt (meine hatte 2,3 GB).
Habe mir jetzt einen raspberry 3B+ geholt und Java 9 statt wie bisher 8.
Zusätzlich haben ich den USB Stick mit ext4 formatiert.
Bisher keine Probleme, ist aber auch ein deutlich stärkerer Prozessor ;-)
Mal schauen ob das Problem dann auch wieder auftritt.

**Comment by mdzio** [comment]
Zusammenfassend kann festgestellt werden, dass die CPU-Belastung auf dem Raspberry Pi maßgeblich vom Speichermedium beeinflusst wird. Programmtechnisch kann dort nichts geändert werden.
