### ISSUE TITLE
SysVar .. minimaler Abstand für Zeitstempel...

### ISSUE THREAD

**Issue by roe1974** [mdzio/ccu-historian#75]
Ich möchte eine Variable auswerten (Bewegung Eingang)
Diese ist bei Bewegung (via http) immer für 10 Sekunden auf "true"
Ist diese zeit zu kurz, damit die Änderung in historian erkannt wird ?

lg Richard

**Comment by mdzio** [comment]
Systemvariablen werden mit der Standardeinstellung alle 30 Sekunden abgetastet. Wenn sich eine Systemvariable innerhalb dieser Zeit mehr als einmal ändert, so wird nur die letzte Wert archiviert.

Dies kann mit der Konfigurationsoption `devices.device1.sysVarDataCycle` (s.a. Abschnitt 4.2.1 im Handbuch) angepasst werden. Beispiel für eine 5 sekündliche Abtastung: `devices.device1.sysVarDataCycle=5000`

Alternativ kann der Impuls auch verlängert werden: Eine zweite Systemvariable bei Bewegung sofort setzen und nach 40 Sekunden automatisch zurücksetzen.
