### ISSUE TITLE
Darstellung von Zählwerten als Balkendiagramme

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-historian#88]
Verschiedene Zeiträume:
* Stunden/Tag (24 Balken)
* Tage/Woche (7 Balken)
* Tage/Monat
* Wochen/Jahr
* Monate/Jahr (12 Balken)

**Comment by duffy6** [comment]
Finde ich eine super-Idee!

prima wäre auch ein Diagramm mit Vergleichsfunktion für
Vortages/Vorwochen/Vormonat/Vorjahres-Zeitraum

Bsp. Gasverbrauch für selben Monat im Vorjahr

**Comment by mdzio** [comment]
Dies ist mit der [H2-HighChart-Erweiterung](https://github.com/wakr70/CCU-Historian-HC) für den CCU-Historian möglich.
