### ISSUE TITLE
Nach Änderung des Netzwerksnamens des RaspberryMatics kann der CCU-Historian nicht mehr starten

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-historian#90]
Fehlermeldung (s.a. [Forum](https://homematic-forum.de/forum/viewtopic.php?f=38&t=42841) ):
```
Caused by: java.net.UnknownHostException: HMS-2018: Name or service not known
at org.h2.util.NetUtils.getLocalAddress(NetUtils.java:252)
```

Eventuell liegt der Fehler in RaspberryMatic. Die Namensauflösung sollte funktionieren.

Ein weiteres Problem mit dem Installationspaket auf RaspberryMatic: Viele Einstellungen (z.B. IP-Adresse) werden zum Installationszeitpunkt ermittelt und in die Konfigurationsdatei des CCU-Historians eingetragen. Nach einer Änderung der IP-Adresse des RaspberryMatics kann die Web-Seite des CCU-Historians nicht mehr aufgerufen werden.

**Comment by mdzio** [comment]
Der Link zurück zur CCU wird zurzeit auf 127.0.0.1 gesetzt. Hier muss bei der Installation die IP des Raspberry Pis eingefügt werden.

**Comment by widmann-it** [comment]
Problem lässt sich auch in der Beta 2 nachvollziehen

**Comment by mdzio** [comment]
Nachfrage:
* Ist in RaspberryMatic eine feste IP konfiguriert?
* Zeigt der Router den Namen und die IP-Adresse des RaspberryMatics richtig an?

**Comment by mdzio** [comment]
jens-maus/RaspberryMatic#326 wurde erledigt. Damit sollte das Problem ab der nächsten RaspberryMatic-Release nicht mehr auftreten.
